/*
 * The Selling Partner API for Automotive.
 * The Selling Partner API for Automotive provides programmatic access to information needed by selling partners to provide compatibility information about their listed products.
 *
 * OpenAPI spec version: 2024-11-01
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';
import {EngineOutputUnit} from './EngineOutputUnit.js';

/**
 * The EngineOutput model module.
 * @module vehicles_2024-11-01/js-client.vehicles_2024-11-01.model/EngineOutput
 * @version 2024-11-01
 */
export class EngineOutput {
  /**
   * Constructs a new <code>EngineOutput</code>.
   * Engine power output of vehicle.
   * @alias module:vehicles_2024-11-01/js-client.vehicles_2024-11-01.model/EngineOutput
   * @class
   * @param value {Number} Engine power value in specified unit.
   * @param unit {module:vehicles_2024-11-01/js-client.vehicles_2024-11-01.model/EngineOutputUnit} Unit for measuring engine power.
   */
  constructor(value, unit) {
    this.value = value;
    this.unit = unit;
  }

  /**
   * Constructs a <code>EngineOutput</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:vehicles_2024-11-01/js-client.vehicles_2024-11-01.model/EngineOutput} obj Optional instance to populate.
   * @return {module:vehicles_2024-11-01/js-client.vehicles_2024-11-01.model/EngineOutput} The populated <code>EngineOutput</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      switch(typeof data) {
        case 'string':
          obj = String(data);
          break;
        case 'number':
          obj = Number(data);
          break;
        case 'boolean':
          obj = Boolean(data);
          break;
      }
      obj = obj || new EngineOutput();
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'Number');
      if (data.hasOwnProperty('unit'))
        obj.unit = EngineOutputUnit.constructFromObject(data['unit']);
    }
    return obj;
  }
}

/**
 * Engine power value in specified unit.
 * @member {Number} value
 */
EngineOutput.prototype.value = undefined;

/**
 * Unit for measuring engine power.
 * @member {module:vehicles_2024-11-01/js-client.vehicles_2024-11-01.model/EngineOutputUnit} unit
 */
EngineOutput.prototype.unit = undefined;


