/*
 * The Selling Partner API for Automotive.
 * The Selling Partner API for Automotive provides programmatic access to information needed by selling partners to provide compatibility information about their listed products.
 *
 * OpenAPI spec version: 2024-11-01
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';

/**
 * Enum class EngineOutputUnit.
 * @enum {String}
 * @readonly
 */
const EngineOutputUnit = {
  /**
   * value: "KILOWATT"
   * @const
   */
  KILOWATT: "KILOWATT",

  /**
   * value: "HORSEPOWER"
   * @const
   */
  HORSEPOWER: "HORSEPOWER",

  /**
   * Returns a <code>EngineOutputUnit</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
   * @return {module:vehicles_2024-11-01/js-client.vehicles_2024-11-01.model/EngineOutputUnit} The enum <code>EngineOutputUnit</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {EngineOutputUnit};
