/*
 * The Selling Partner API for Automotive.
 * The Selling Partner API for Automotive provides programmatic access to information needed by selling partners to provide compatibility information about their listed products.
 *
 * OpenAPI spec version: 2024-11-01
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';
import {Month} from './Month.js';
import {Year} from './Year.js';

/**
 * The MonthAndYear model module.
 * @module vehicles_2024-11-01/js-client.vehicles_2024-11-01.model/MonthAndYear
 * @version 2024-11-01
 */
export class MonthAndYear {
  /**
   * Constructs a new <code>MonthAndYear</code>.
   * Represents a month in a specific year.
   * @alias module:vehicles_2024-11-01/js-client.vehicles_2024-11-01.model/MonthAndYear
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MonthAndYear</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:vehicles_2024-11-01/js-client.vehicles_2024-11-01.model/MonthAndYear} obj Optional instance to populate.
   * @return {module:vehicles_2024-11-01/js-client.vehicles_2024-11-01.model/MonthAndYear} The populated <code>MonthAndYear</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      switch(typeof data) {
        case 'string':
          obj = String(data);
          break;
        case 'number':
          obj = Number(data);
          break;
        case 'boolean':
          obj = Boolean(data);
          break;
      }
      obj = obj || new MonthAndYear();
      if (data.hasOwnProperty('year'))
        obj.year = Year.constructFromObject(data['year']);
      if (data.hasOwnProperty('month'))
        obj.month = Month.constructFromObject(data['month']);
    }
    return obj;
  }
}

/**
 * @member {module:vehicles_2024-11-01/js-client.vehicles_2024-11-01.model/Year} year
 */
MonthAndYear.prototype.year = undefined;

/**
 * @member {module:vehicles_2024-11-01/js-client.vehicles_2024-11-01.model/Month} month
 */
MonthAndYear.prototype.month = undefined;


