/*
 * The Selling Partner API for Amazon Seller Wallet Open Banking API Spec.  For more information, refer to the [Seller Wallet Open Banking API Use Case Guide](doc:seller-wallet-open-banking-api-v2024-03-01-use-case-guide).
 * The Selling Partner API for Seller Wallet (Seller Wallet API) provides financial information that is relevant to a seller's Seller Wallet account. You can obtain financial events, balances, and transfer schedules for Seller Wallet accounts. You can also schedule and initiate transactions.
 *
 * OpenAPI spec version: 2024-03-01
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from './ApiClient.js';
import {AccountHolderAddress} from './js-client.sellerWallet_2024-03-01.model/AccountHolderAddress.js';
import {Balance} from './js-client.sellerWallet_2024-03-01.model/Balance.js';
import {BalanceListing} from './js-client.sellerWallet_2024-03-01.model/BalanceListing.js';
import {BalanceType} from './js-client.sellerWallet_2024-03-01.model/BalanceType.js';
import {BankAccount} from './js-client.sellerWallet_2024-03-01.model/BankAccount.js';
import {BankAccountHolderStatus} from './js-client.sellerWallet_2024-03-01.model/BankAccountHolderStatus.js';
import {BankAccountListing} from './js-client.sellerWallet_2024-03-01.model/BankAccountListing.js';
import {BankAccountNumberFormat} from './js-client.sellerWallet_2024-03-01.model/BankAccountNumberFormat.js';
import {BankAccountOwnershipType} from './js-client.sellerWallet_2024-03-01.model/BankAccountOwnershipType.js';
import {BankNumberFormat} from './js-client.sellerWallet_2024-03-01.model/BankNumberFormat.js';
import {BigDecimal} from './js-client.sellerWallet_2024-03-01.model/BigDecimal.js';
import {CreateTransactionResponse} from './js-client.sellerWallet_2024-03-01.model/CreateTransactionResponse.js';
import {Currency} from './js-client.sellerWallet_2024-03-01.model/Currency.js';
import {DeleteTransferSchedule} from './js-client.sellerWallet_2024-03-01.model/DeleteTransferSchedule.js';
import {Error} from './js-client.sellerWallet_2024-03-01.model/Error.js';
import {ErrorList} from './js-client.sellerWallet_2024-03-01.model/ErrorList.js';
import {Fee} from './js-client.sellerWallet_2024-03-01.model/Fee.js';
import {FeeType} from './js-client.sellerWallet_2024-03-01.model/FeeType.js';
import {FxRateDetails} from './js-client.sellerWallet_2024-03-01.model/FxRateDetails.js';
import {PaymentPreference} from './js-client.sellerWallet_2024-03-01.model/PaymentPreference.js';
import {PaymentPreferencePaymentType} from './js-client.sellerWallet_2024-03-01.model/PaymentPreferencePaymentType.js';
import {RateDirection} from './js-client.sellerWallet_2024-03-01.model/RateDirection.js';
import {RecurringFrequency} from './js-client.sellerWallet_2024-03-01.model/RecurringFrequency.js';
import {ScheduleExpression} from './js-client.sellerWallet_2024-03-01.model/ScheduleExpression.js';
import {ScheduleExpressionType} from './js-client.sellerWallet_2024-03-01.model/ScheduleExpressionType.js';
import {ScheduleTransferType} from './js-client.sellerWallet_2024-03-01.model/ScheduleTransferType.js';
import {Transaction} from './js-client.sellerWallet_2024-03-01.model/Transaction.js';
import {TransactionAccount} from './js-client.sellerWallet_2024-03-01.model/TransactionAccount.js';
import {TransactionInitiationRequest} from './js-client.sellerWallet_2024-03-01.model/TransactionInitiationRequest.js';
import {TransactionInstrumentDetails} from './js-client.sellerWallet_2024-03-01.model/TransactionInstrumentDetails.js';
import {TransactionListing} from './js-client.sellerWallet_2024-03-01.model/TransactionListing.js';
import {TransactionStatus} from './js-client.sellerWallet_2024-03-01.model/TransactionStatus.js';
import {TransactionType} from './js-client.sellerWallet_2024-03-01.model/TransactionType.js';
import {TransferRatePreview} from './js-client.sellerWallet_2024-03-01.model/TransferRatePreview.js';
import {TransferSchedule} from './js-client.sellerWallet_2024-03-01.model/TransferSchedule.js';
import {TransferScheduleFailures} from './js-client.sellerWallet_2024-03-01.model/TransferScheduleFailures.js';
import {TransferScheduleInformation} from './js-client.sellerWallet_2024-03-01.model/TransferScheduleInformation.js';
import {TransferScheduleListing} from './js-client.sellerWallet_2024-03-01.model/TransferScheduleListing.js';
import {TransferScheduleRequest} from './js-client.sellerWallet_2024-03-01.model/TransferScheduleRequest.js';
import {TransferScheduleStatus} from './js-client.sellerWallet_2024-03-01.model/TransferScheduleStatus.js';
import {AccountsApi} from './js-client.sellerWallet_2024-03-01.api/AccountsApi.js';
import {TransactionsApi} from './js-client.sellerWallet_2024-03-01.api/TransactionsApi.js';
import {TransferPreviewApi} from './js-client.sellerWallet_2024-03-01.api/TransferPreviewApi.js';
import {TransferScheduleApi} from './js-client.sellerWallet_2024-03-01.api/TransferScheduleApi.js';


/**
* The_Selling_Partner_API_for_Seller_Wallet__Seller_Wallet_API_provides_financial_information_that_is_relevant_to_a_sellers_Seller_Wallet_account__You_can_obtain_financial_events_balances_and_transfer_schedules_for_Seller_Wallet_accounts__You_can_also_schedule_and_initiate_transactions_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var TheSellingPartnerApiForAmazonSellerWalletOpenBankingApiSpecforMoreInformationReferToTheSellerWalletOpenBankingApiUseCaseGuideDocsellerWalletOpenBankingApiV20240301UseCaseGuide = require('sellerWallet_2024-03-01/index'); // See note below*.
* var xxxSvc = new TheSellingPartnerApiForAmazonSellerWalletOpenBankingApiSpecforMoreInformationReferToTheSellerWalletOpenBankingApiUseCaseGuideDocsellerWalletOpenBankingApiV20240301UseCaseGuide.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new TheSellingPartnerApiForAmazonSellerWalletOpenBankingApiSpecforMoreInformationReferToTheSellerWalletOpenBankingApiUseCaseGuideDocsellerWalletOpenBankingApiV20240301UseCaseGuide.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['sellerWallet_2024-03-01/index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new TheSellingPartnerApiForAmazonSellerWalletOpenBankingApiSpecforMoreInformationReferToTheSellerWalletOpenBankingApiUseCaseGuideDocsellerWalletOpenBankingApiV20240301UseCaseGuide.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new TheSellingPartnerApiForAmazonSellerWalletOpenBankingApiSpecforMoreInformationReferToTheSellerWalletOpenBankingApiUseCaseGuideDocsellerWalletOpenBankingApiV20240301UseCaseGuide.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module sellerWallet_2024-03-01/index
* @version 2024-03-01
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:sellerWallet_2024-03-01/ApiClient}
     */
    ApiClient,

    /**
     * The AccountHolderAddress model constructor.
     * @property {module:sellerWallet_2024-03-01/js-client.sellerWallet_2024-03-01.model/AccountHolderAddress}
     */
    AccountHolderAddress,

    /**
     * The Balance model constructor.
     * @property {module:sellerWallet_2024-03-01/js-client.sellerWallet_2024-03-01.model/Balance}
     */
    Balance,

    /**
     * The BalanceListing model constructor.
     * @property {module:sellerWallet_2024-03-01/js-client.sellerWallet_2024-03-01.model/BalanceListing}
     */
    BalanceListing,

    /**
     * The BalanceType model constructor.
     * @property {module:sellerWallet_2024-03-01/js-client.sellerWallet_2024-03-01.model/BalanceType}
     */
    BalanceType,

    /**
     * The BankAccount model constructor.
     * @property {module:sellerWallet_2024-03-01/js-client.sellerWallet_2024-03-01.model/BankAccount}
     */
    BankAccount,

    /**
     * The BankAccountHolderStatus model constructor.
     * @property {module:sellerWallet_2024-03-01/js-client.sellerWallet_2024-03-01.model/BankAccountHolderStatus}
     */
    BankAccountHolderStatus,

    /**
     * The BankAccountListing model constructor.
     * @property {module:sellerWallet_2024-03-01/js-client.sellerWallet_2024-03-01.model/BankAccountListing}
     */
    BankAccountListing,

    /**
     * The BankAccountNumberFormat model constructor.
     * @property {module:sellerWallet_2024-03-01/js-client.sellerWallet_2024-03-01.model/BankAccountNumberFormat}
     */
    BankAccountNumberFormat,

    /**
     * The BankAccountOwnershipType model constructor.
     * @property {module:sellerWallet_2024-03-01/js-client.sellerWallet_2024-03-01.model/BankAccountOwnershipType}
     */
    BankAccountOwnershipType,

    /**
     * The BankNumberFormat model constructor.
     * @property {module:sellerWallet_2024-03-01/js-client.sellerWallet_2024-03-01.model/BankNumberFormat}
     */
    BankNumberFormat,

    /**
     * The BigDecimal model constructor.
     * @property {module:sellerWallet_2024-03-01/js-client.sellerWallet_2024-03-01.model/BigDecimal}
     */
    BigDecimal,

    /**
     * The CreateTransactionResponse model constructor.
     * @property {module:sellerWallet_2024-03-01/js-client.sellerWallet_2024-03-01.model/CreateTransactionResponse}
     */
    CreateTransactionResponse,

    /**
     * The Currency model constructor.
     * @property {module:sellerWallet_2024-03-01/js-client.sellerWallet_2024-03-01.model/Currency}
     */
    Currency,

    /**
     * The DeleteTransferSchedule model constructor.
     * @property {module:sellerWallet_2024-03-01/js-client.sellerWallet_2024-03-01.model/DeleteTransferSchedule}
     */
    DeleteTransferSchedule,

    /**
     * The Error model constructor.
     * @property {module:sellerWallet_2024-03-01/js-client.sellerWallet_2024-03-01.model/Error}
     */
    Error,

    /**
     * The ErrorList model constructor.
     * @property {module:sellerWallet_2024-03-01/js-client.sellerWallet_2024-03-01.model/ErrorList}
     */
    ErrorList,

    /**
     * The Fee model constructor.
     * @property {module:sellerWallet_2024-03-01/js-client.sellerWallet_2024-03-01.model/Fee}
     */
    Fee,

    /**
     * The FeeType model constructor.
     * @property {module:sellerWallet_2024-03-01/js-client.sellerWallet_2024-03-01.model/FeeType}
     */
    FeeType,

    /**
     * The FxRateDetails model constructor.
     * @property {module:sellerWallet_2024-03-01/js-client.sellerWallet_2024-03-01.model/FxRateDetails}
     */
    FxRateDetails,

    /**
     * The PaymentPreference model constructor.
     * @property {module:sellerWallet_2024-03-01/js-client.sellerWallet_2024-03-01.model/PaymentPreference}
     */
    PaymentPreference,

    /**
     * The PaymentPreferencePaymentType model constructor.
     * @property {module:sellerWallet_2024-03-01/js-client.sellerWallet_2024-03-01.model/PaymentPreferencePaymentType}
     */
    PaymentPreferencePaymentType,

    /**
     * The RateDirection model constructor.
     * @property {module:sellerWallet_2024-03-01/js-client.sellerWallet_2024-03-01.model/RateDirection}
     */
    RateDirection,

    /**
     * The RecurringFrequency model constructor.
     * @property {module:sellerWallet_2024-03-01/js-client.sellerWallet_2024-03-01.model/RecurringFrequency}
     */
    RecurringFrequency,

    /**
     * The ScheduleExpression model constructor.
     * @property {module:sellerWallet_2024-03-01/js-client.sellerWallet_2024-03-01.model/ScheduleExpression}
     */
    ScheduleExpression,

    /**
     * The ScheduleExpressionType model constructor.
     * @property {module:sellerWallet_2024-03-01/js-client.sellerWallet_2024-03-01.model/ScheduleExpressionType}
     */
    ScheduleExpressionType,

    /**
     * The ScheduleTransferType model constructor.
     * @property {module:sellerWallet_2024-03-01/js-client.sellerWallet_2024-03-01.model/ScheduleTransferType}
     */
    ScheduleTransferType,

    /**
     * The Transaction model constructor.
     * @property {module:sellerWallet_2024-03-01/js-client.sellerWallet_2024-03-01.model/Transaction}
     */
    Transaction,

    /**
     * The TransactionAccount model constructor.
     * @property {module:sellerWallet_2024-03-01/js-client.sellerWallet_2024-03-01.model/TransactionAccount}
     */
    TransactionAccount,

    /**
     * The TransactionInitiationRequest model constructor.
     * @property {module:sellerWallet_2024-03-01/js-client.sellerWallet_2024-03-01.model/TransactionInitiationRequest}
     */
    TransactionInitiationRequest,

    /**
     * The TransactionInstrumentDetails model constructor.
     * @property {module:sellerWallet_2024-03-01/js-client.sellerWallet_2024-03-01.model/TransactionInstrumentDetails}
     */
    TransactionInstrumentDetails,

    /**
     * The TransactionListing model constructor.
     * @property {module:sellerWallet_2024-03-01/js-client.sellerWallet_2024-03-01.model/TransactionListing}
     */
    TransactionListing,

    /**
     * The TransactionStatus model constructor.
     * @property {module:sellerWallet_2024-03-01/js-client.sellerWallet_2024-03-01.model/TransactionStatus}
     */
    TransactionStatus,

    /**
     * The TransactionType model constructor.
     * @property {module:sellerWallet_2024-03-01/js-client.sellerWallet_2024-03-01.model/TransactionType}
     */
    TransactionType,

    /**
     * The TransferRatePreview model constructor.
     * @property {module:sellerWallet_2024-03-01/js-client.sellerWallet_2024-03-01.model/TransferRatePreview}
     */
    TransferRatePreview,

    /**
     * The TransferSchedule model constructor.
     * @property {module:sellerWallet_2024-03-01/js-client.sellerWallet_2024-03-01.model/TransferSchedule}
     */
    TransferSchedule,

    /**
     * The TransferScheduleFailures model constructor.
     * @property {module:sellerWallet_2024-03-01/js-client.sellerWallet_2024-03-01.model/TransferScheduleFailures}
     */
    TransferScheduleFailures,

    /**
     * The TransferScheduleInformation model constructor.
     * @property {module:sellerWallet_2024-03-01/js-client.sellerWallet_2024-03-01.model/TransferScheduleInformation}
     */
    TransferScheduleInformation,

    /**
     * The TransferScheduleListing model constructor.
     * @property {module:sellerWallet_2024-03-01/js-client.sellerWallet_2024-03-01.model/TransferScheduleListing}
     */
    TransferScheduleListing,

    /**
     * The TransferScheduleRequest model constructor.
     * @property {module:sellerWallet_2024-03-01/js-client.sellerWallet_2024-03-01.model/TransferScheduleRequest}
     */
    TransferScheduleRequest,

    /**
     * The TransferScheduleStatus model constructor.
     * @property {module:sellerWallet_2024-03-01/js-client.sellerWallet_2024-03-01.model/TransferScheduleStatus}
     */
    TransferScheduleStatus,

    /**
    * The AccountsApi service constructor.
    * @property {module:sellerWallet_2024-03-01/js-client.sellerWallet_2024-03-01.api/AccountsApi}
    */
    AccountsApi,

    /**
    * The TransactionsApi service constructor.
    * @property {module:sellerWallet_2024-03-01/js-client.sellerWallet_2024-03-01.api/TransactionsApi}
    */
    TransactionsApi,

    /**
    * The TransferPreviewApi service constructor.
    * @property {module:sellerWallet_2024-03-01/js-client.sellerWallet_2024-03-01.api/TransferPreviewApi}
    */
    TransferPreviewApi,

    /**
    * The TransferScheduleApi service constructor.
    * @property {module:sellerWallet_2024-03-01/js-client.sellerWallet_2024-03-01.api/TransferScheduleApi}
    */
    TransferScheduleApi
};
