/*
 * The Selling Partner API for CustomerFeedback
 * The Selling Partner API for Customer Feedback (Customer Feedback API) provides information about customer reviews and returns at both the item and browse node level.
 *
 * OpenAPI spec version: 2024-06-01
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from './ApiClient.js';
import {BrowseNodeAllOccurrence} from './js-client.customerFeedback_2024-06-01.model/BrowseNodeAllOccurrence.js';
import {BrowseNodeAllStarRatingImpact} from './js-client.customerFeedback_2024-06-01.model/BrowseNodeAllStarRatingImpact.js';
import {BrowseNodeOccurrence} from './js-client.customerFeedback_2024-06-01.model/BrowseNodeOccurrence.js';
import {BrowseNodeResponse} from './js-client.customerFeedback_2024-06-01.model/BrowseNodeResponse.js';
import {BrowseNodeReturnTopics} from './js-client.customerFeedback_2024-06-01.model/BrowseNodeReturnTopics.js';
import {BrowseNodeReturnTopicsResponse} from './js-client.customerFeedback_2024-06-01.model/BrowseNodeReturnTopicsResponse.js';
import {BrowseNodeReturnTrend} from './js-client.customerFeedback_2024-06-01.model/BrowseNodeReturnTrend.js';
import {BrowseNodeReturnTrendPoint} from './js-client.customerFeedback_2024-06-01.model/BrowseNodeReturnTrendPoint.js';
import {BrowseNodeReturnTrendsResponse} from './js-client.customerFeedback_2024-06-01.model/BrowseNodeReturnTrendsResponse.js';
import {BrowseNodeReviewSubtopicMetrics} from './js-client.customerFeedback_2024-06-01.model/BrowseNodeReviewSubtopicMetrics.js';
import {BrowseNodeReviewTopic} from './js-client.customerFeedback_2024-06-01.model/BrowseNodeReviewTopic.js';
import {BrowseNodeReviewTopicMetrics} from './js-client.customerFeedback_2024-06-01.model/BrowseNodeReviewTopicMetrics.js';
import {BrowseNodeReviewTopics} from './js-client.customerFeedback_2024-06-01.model/BrowseNodeReviewTopics.js';
import {BrowseNodeReviewTopicsResponse} from './js-client.customerFeedback_2024-06-01.model/BrowseNodeReviewTopicsResponse.js';
import {BrowseNodeReviewTrend} from './js-client.customerFeedback_2024-06-01.model/BrowseNodeReviewTrend.js';
import {BrowseNodeReviewTrendMetrics} from './js-client.customerFeedback_2024-06-01.model/BrowseNodeReviewTrendMetrics.js';
import {BrowseNodeReviewTrendPoint} from './js-client.customerFeedback_2024-06-01.model/BrowseNodeReviewTrendPoint.js';
import {BrowseNodeReviewTrends} from './js-client.customerFeedback_2024-06-01.model/BrowseNodeReviewTrends.js';
import {BrowseNodeReviewTrendsResponse} from './js-client.customerFeedback_2024-06-01.model/BrowseNodeReviewTrendsResponse.js';
import {BrowseNodeStarRatingImpact} from './js-client.customerFeedback_2024-06-01.model/BrowseNodeStarRatingImpact.js';
import {BrowseNodeSubtopic} from './js-client.customerFeedback_2024-06-01.model/BrowseNodeSubtopic.js';
import {BrowseNodeTrendMetrics} from './js-client.customerFeedback_2024-06-01.model/BrowseNodeTrendMetrics.js';
import {ChildAsinMentionMetrics} from './js-client.customerFeedback_2024-06-01.model/ChildAsinMentionMetrics.js';
import {ChildAsinMetrics} from './js-client.customerFeedback_2024-06-01.model/ChildAsinMetrics.js';
import {DateRange} from './js-client.customerFeedback_2024-06-01.model/DateRange.js';
import {Error} from './js-client.customerFeedback_2024-06-01.model/Error.js';
import {ErrorList} from './js-client.customerFeedback_2024-06-01.model/ErrorList.js';
import {ItemReviewBrowseNodeMetrics} from './js-client.customerFeedback_2024-06-01.model/ItemReviewBrowseNodeMetrics.js';
import {ItemReviewSubtopic} from './js-client.customerFeedback_2024-06-01.model/ItemReviewSubtopic.js';
import {ItemReviewSubtopicMetrics} from './js-client.customerFeedback_2024-06-01.model/ItemReviewSubtopicMetrics.js';
import {ItemReviewTopic} from './js-client.customerFeedback_2024-06-01.model/ItemReviewTopic.js';
import {ItemReviewTopicMetrics} from './js-client.customerFeedback_2024-06-01.model/ItemReviewTopicMetrics.js';
import {ItemReviewTopics} from './js-client.customerFeedback_2024-06-01.model/ItemReviewTopics.js';
import {ItemReviewTopicsResponse} from './js-client.customerFeedback_2024-06-01.model/ItemReviewTopicsResponse.js';
import {ItemReviewTrend} from './js-client.customerFeedback_2024-06-01.model/ItemReviewTrend.js';
import {ItemReviewTrendPoint} from './js-client.customerFeedback_2024-06-01.model/ItemReviewTrendPoint.js';
import {ItemReviewTrends} from './js-client.customerFeedback_2024-06-01.model/ItemReviewTrends.js';
import {ItemReviewTrendsResponse} from './js-client.customerFeedback_2024-06-01.model/ItemReviewTrendsResponse.js';
import {ReviewTrendMetrics} from './js-client.customerFeedback_2024-06-01.model/ReviewTrendMetrics.js';
import {CustomerFeedbackApi} from './js-client.customerFeedback_2024-06-01.api/CustomerFeedbackApi.js';


/**
* The_Selling_Partner_API_for_Customer_Feedback__Customer_Feedback_API_provides_information_about_customer_reviews_and_returns_at_both_the_item_and_browse_node_level_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var TheSellingPartnerApiForCustomerFeedback = require('customerFeedback_2024-06-01/index'); // See note below*.
* var xxxSvc = new TheSellingPartnerApiForCustomerFeedback.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new TheSellingPartnerApiForCustomerFeedback.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['customerFeedback_2024-06-01/index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new TheSellingPartnerApiForCustomerFeedback.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new TheSellingPartnerApiForCustomerFeedback.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module customerFeedback_2024-06-01/index
* @version 2024-06-01
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:customerFeedback_2024-06-01/ApiClient}
     */
    ApiClient,

    /**
     * The BrowseNodeAllOccurrence model constructor.
     * @property {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeAllOccurrence}
     */
    BrowseNodeAllOccurrence,

    /**
     * The BrowseNodeAllStarRatingImpact model constructor.
     * @property {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeAllStarRatingImpact}
     */
    BrowseNodeAllStarRatingImpact,

    /**
     * The BrowseNodeOccurrence model constructor.
     * @property {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeOccurrence}
     */
    BrowseNodeOccurrence,

    /**
     * The BrowseNodeResponse model constructor.
     * @property {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeResponse}
     */
    BrowseNodeResponse,

    /**
     * The BrowseNodeReturnTopics model constructor.
     * @property {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeReturnTopics}
     */
    BrowseNodeReturnTopics,

    /**
     * The BrowseNodeReturnTopicsResponse model constructor.
     * @property {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeReturnTopicsResponse}
     */
    BrowseNodeReturnTopicsResponse,

    /**
     * The BrowseNodeReturnTrend model constructor.
     * @property {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeReturnTrend}
     */
    BrowseNodeReturnTrend,

    /**
     * The BrowseNodeReturnTrendPoint model constructor.
     * @property {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeReturnTrendPoint}
     */
    BrowseNodeReturnTrendPoint,

    /**
     * The BrowseNodeReturnTrendsResponse model constructor.
     * @property {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeReturnTrendsResponse}
     */
    BrowseNodeReturnTrendsResponse,

    /**
     * The BrowseNodeReviewSubtopicMetrics model constructor.
     * @property {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeReviewSubtopicMetrics}
     */
    BrowseNodeReviewSubtopicMetrics,

    /**
     * The BrowseNodeReviewTopic model constructor.
     * @property {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeReviewTopic}
     */
    BrowseNodeReviewTopic,

    /**
     * The BrowseNodeReviewTopicMetrics model constructor.
     * @property {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeReviewTopicMetrics}
     */
    BrowseNodeReviewTopicMetrics,

    /**
     * The BrowseNodeReviewTopics model constructor.
     * @property {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeReviewTopics}
     */
    BrowseNodeReviewTopics,

    /**
     * The BrowseNodeReviewTopicsResponse model constructor.
     * @property {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeReviewTopicsResponse}
     */
    BrowseNodeReviewTopicsResponse,

    /**
     * The BrowseNodeReviewTrend model constructor.
     * @property {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeReviewTrend}
     */
    BrowseNodeReviewTrend,

    /**
     * The BrowseNodeReviewTrendMetrics model constructor.
     * @property {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeReviewTrendMetrics}
     */
    BrowseNodeReviewTrendMetrics,

    /**
     * The BrowseNodeReviewTrendPoint model constructor.
     * @property {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeReviewTrendPoint}
     */
    BrowseNodeReviewTrendPoint,

    /**
     * The BrowseNodeReviewTrends model constructor.
     * @property {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeReviewTrends}
     */
    BrowseNodeReviewTrends,

    /**
     * The BrowseNodeReviewTrendsResponse model constructor.
     * @property {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeReviewTrendsResponse}
     */
    BrowseNodeReviewTrendsResponse,

    /**
     * The BrowseNodeStarRatingImpact model constructor.
     * @property {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeStarRatingImpact}
     */
    BrowseNodeStarRatingImpact,

    /**
     * The BrowseNodeSubtopic model constructor.
     * @property {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeSubtopic}
     */
    BrowseNodeSubtopic,

    /**
     * The BrowseNodeTrendMetrics model constructor.
     * @property {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeTrendMetrics}
     */
    BrowseNodeTrendMetrics,

    /**
     * The ChildAsinMentionMetrics model constructor.
     * @property {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/ChildAsinMentionMetrics}
     */
    ChildAsinMentionMetrics,

    /**
     * The ChildAsinMetrics model constructor.
     * @property {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/ChildAsinMetrics}
     */
    ChildAsinMetrics,

    /**
     * The DateRange model constructor.
     * @property {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/DateRange}
     */
    DateRange,

    /**
     * The Error model constructor.
     * @property {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/Error}
     */
    Error,

    /**
     * The ErrorList model constructor.
     * @property {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/ErrorList}
     */
    ErrorList,

    /**
     * The ItemReviewBrowseNodeMetrics model constructor.
     * @property {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/ItemReviewBrowseNodeMetrics}
     */
    ItemReviewBrowseNodeMetrics,

    /**
     * The ItemReviewSubtopic model constructor.
     * @property {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/ItemReviewSubtopic}
     */
    ItemReviewSubtopic,

    /**
     * The ItemReviewSubtopicMetrics model constructor.
     * @property {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/ItemReviewSubtopicMetrics}
     */
    ItemReviewSubtopicMetrics,

    /**
     * The ItemReviewTopic model constructor.
     * @property {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/ItemReviewTopic}
     */
    ItemReviewTopic,

    /**
     * The ItemReviewTopicMetrics model constructor.
     * @property {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/ItemReviewTopicMetrics}
     */
    ItemReviewTopicMetrics,

    /**
     * The ItemReviewTopics model constructor.
     * @property {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/ItemReviewTopics}
     */
    ItemReviewTopics,

    /**
     * The ItemReviewTopicsResponse model constructor.
     * @property {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/ItemReviewTopicsResponse}
     */
    ItemReviewTopicsResponse,

    /**
     * The ItemReviewTrend model constructor.
     * @property {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/ItemReviewTrend}
     */
    ItemReviewTrend,

    /**
     * The ItemReviewTrendPoint model constructor.
     * @property {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/ItemReviewTrendPoint}
     */
    ItemReviewTrendPoint,

    /**
     * The ItemReviewTrends model constructor.
     * @property {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/ItemReviewTrends}
     */
    ItemReviewTrends,

    /**
     * The ItemReviewTrendsResponse model constructor.
     * @property {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/ItemReviewTrendsResponse}
     */
    ItemReviewTrendsResponse,

    /**
     * The ReviewTrendMetrics model constructor.
     * @property {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/ReviewTrendMetrics}
     */
    ReviewTrendMetrics,

    /**
    * The CustomerFeedbackApi service constructor.
    * @property {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.api/CustomerFeedbackApi}
    */
    CustomerFeedbackApi
};
