/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Finance202506GetSellerunsettledtransactionResponseDataTransactionsFeeTaxBreakdownFee } from './GetSellerunsettledtransactionResponseDataTransactionsFeeTaxBreakdownFee';
import { Finance202506GetSellerunsettledtransactionResponseDataTransactionsFeeTaxBreakdownTax } from './GetSellerunsettledtransactionResponseDataTransactionsFeeTaxBreakdownTax';

export class Finance202506GetSellerunsettledtransactionResponseDataTransactionsFeeTaxBreakdown {
    'fee'?: Finance202506GetSellerunsettledtransactionResponseDataTransactionsFeeTaxBreakdownFee;
    'tax'?: Finance202506GetSellerunsettledtransactionResponseDataTransactionsFeeTaxBreakdownTax;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "fee",
            "baseName": "fee",
            "type": "Finance202506GetSellerunsettledtransactionResponseDataTransactionsFeeTaxBreakdownFee"
        },
        {
            "name": "tax",
            "baseName": "tax",
            "type": "Finance202506GetSellerunsettledtransactionResponseDataTransactionsFeeTaxBreakdownTax"
        }    ];

    static getAttributeTypeMap() {
        return Finance202506GetSellerunsettledtransactionResponseDataTransactionsFeeTaxBreakdown.attributeTypeMap;
    }
}

