/*
 * Selling Partner API for Shipment Invoicing
 * The Selling Partner API for Shipment Invoicing helps you programmatically retrieve shipment invoice information in the Brazil marketplace for a selling partner’s Fulfillment by Amazon (FBA) orders.
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';
import {PaymentInformation} from './PaymentInformation.js';

/**
 * The PaymentInformationList model module.
 * @module shipmentInvoicingV0/js-client.shipmentInvoicingV0.model/PaymentInformationList
 * @version v0
 */
export class PaymentInformationList extends Array {
  /**
   * Constructs a new <code>PaymentInformationList</code>.
   * List of payment transactions
   * @alias module:shipmentInvoicingV0/js-client.shipmentInvoicingV0.model/PaymentInformationList
   * @class
   * @extends Array
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>PaymentInformationList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:shipmentInvoicingV0/js-client.shipmentInvoicingV0.model/PaymentInformationList} obj Optional instance to populate.
   * @return {module:shipmentInvoicingV0/js-client.shipmentInvoicingV0.model/PaymentInformationList} The populated <code>PaymentInformationList</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      switch(typeof data) {
        case 'string':
          obj = String(data);
          break;
        case 'number':
          obj = Number(data);
          break;
        case 'boolean':
          obj = Boolean(data);
          break;
      }
      obj = obj || new PaymentInformationList();
      ApiClient.constructFromObject(data, obj, 'PaymentInformation');
    }
    return obj;
  }
}

