/*
 * Selling Partner API for Easy Ship
 * Use the Selling Partner API for Easy Ship to build applications for sellers to manage and ship Amazon Easy Ship orders. With this API, you can get available time slots, schedule and reschedule Easy Ship orders, and print shipping labels, invoices, and warranties. To review the differences in Easy Ship operations by marketplace, refer to [Marketplace support](https://developer-docs.amazon.com/sp-api/docs/easyship-api-v2022-03-23-use-case-guide#marketplace-support).
 *
 * OpenAPI spec version: 2022-03-23
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';

/**
 * Enum class Code.
 * @enum {String}
 * @readonly
 */
const Code = {
  /**
   * value: "InvalidInput"
   * @const
   */
  invalidInput: "InvalidInput",

  /**
   * value: "InvalidTimeSlotId"
   * @const
   */
  invalidTimeSlotId: "InvalidTimeSlotId",

  /**
   * value: "ScheduledPackageAlreadyExists"
   * @const
   */
  scheduledPackageAlreadyExists: "ScheduledPackageAlreadyExists",

  /**
   * value: "ScheduleWindowExpired"
   * @const
   */
  scheduleWindowExpired: "ScheduleWindowExpired",

  /**
   * value: "RetryableAfterGettingNewSlots"
   * @const
   */
  retryableAfterGettingNewSlots: "RetryableAfterGettingNewSlots",

  /**
   * value: "TimeSlotNotAvailable"
   * @const
   */
  timeSlotNotAvailable: "TimeSlotNotAvailable",

  /**
   * value: "ResourceNotFound"
   * @const
   */
  resourceNotFound: "ResourceNotFound",

  /**
   * value: "InvalidOrderState"
   * @const
   */
  invalidOrderState: "InvalidOrderState",

  /**
   * value: "RegionNotSupported"
   * @const
   */
  regionNotSupported: "RegionNotSupported",

  /**
   * value: "OrderNotEligibleForRescheduling"
   * @const
   */
  orderNotEligibleForRescheduling: "OrderNotEligibleForRescheduling",

  /**
   * value: "InternalServerError"
   * @const
   */
  internalServerError: "InternalServerError",

  /**
   * Returns a <code>Code</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
   * @return {module:easyShip_2022-03-23/js-client.easyShip_2022-03-23.model/Code} The enum <code>Code</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {Code};
