/*
 * Selling Partner API for A+ Content Management
 * Use the A+ Content API to build applications that help selling partners add rich marketing content to their Amazon product detail pages. Selling partners can use A+ content to share their brand and product story, which helps buyers make informed purchasing decisions. Selling partners use content modules to add images and text.
 *
 * OpenAPI spec version: 2020-11-01
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';
import {ContentBadge} from './ContentBadge.js';

/**
 * The ContentBadgeSet model module.
 * @module aplusContent_2020-11-01/js-client.aplusContent_2020-11-01.model/ContentBadgeSet
 * @version 2020-11-01
 */
export class ContentBadgeSet extends Array {
  /**
   * Constructs a new <code>ContentBadgeSet</code>.
   * The set of content badges.
   * @alias module:aplusContent_2020-11-01/js-client.aplusContent_2020-11-01.model/ContentBadgeSet
   * @class
   * @extends Array
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>ContentBadgeSet</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:aplusContent_2020-11-01/js-client.aplusContent_2020-11-01.model/ContentBadgeSet} obj Optional instance to populate.
   * @return {module:aplusContent_2020-11-01/js-client.aplusContent_2020-11-01.model/ContentBadgeSet} The populated <code>ContentBadgeSet</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      switch(typeof data) {
        case 'string':
          obj = String(data);
          break;
        case 'number':
          obj = Number(data);
          break;
        case 'boolean':
          obj = Boolean(data);
          break;
      }
      obj = obj || new ContentBadgeSet();
      ApiClient.constructFromObject(data, obj, 'ContentBadge');
    }
    return obj;
  }
}

