/*
 * Selling Partner API for A+ Content Management
 * Use the A+ Content API to build applications that help selling partners add rich marketing content to their Amazon product detail pages. Selling partners can use A+ content to share their brand and product story, which helps buyers make informed purchasing decisions. Selling partners use content modules to add images and text.
 *
 * OpenAPI spec version: 2020-11-01
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';

/**
 * Enum class ContentBadge.
 * @enum {String}
 * @readonly
 */
const ContentBadge = {
  /**
   * value: "BULK"
   * @const
   */
  BULK: "BULK",

  /**
   * value: "GENERATED"
   * @const
   */
  GENERATED: "GENERATED",

  /**
   * value: "LAUNCHPAD"
   * @const
   */
  LAUNCHPAD: "LAUNCHPAD",

  /**
   * value: "PREMIUM"
   * @const
   */
  PREMIUM: "PREMIUM",

  /**
   * value: "STANDARD"
   * @const
   */
  STANDARD: "STANDARD",

  /**
   * Returns a <code>ContentBadge</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
   * @return {module:aplusContent_2020-11-01/js-client.aplusContent_2020-11-01.model/ContentBadge} The enum <code>ContentBadge</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {ContentBadge};
