/*
 * The Selling Partner API for Automotive.
 * The Selling Partner API for Automotive provides programmatic access to information needed by selling partners to provide compatibility information about their listed products.
 *
 * OpenAPI spec version: 2024-11-01
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from './ApiClient.js';
import {EngineOutput} from './js-client.vehicles_2024-11-01.model/EngineOutput.js';
import {EngineOutputUnit} from './js-client.vehicles_2024-11-01.model/EngineOutputUnit.js';
import {Error} from './js-client.vehicles_2024-11-01.model/Error.js';
import {ErrorList} from './js-client.vehicles_2024-11-01.model/ErrorList.js';
import {Month} from './js-client.vehicles_2024-11-01.model/Month.js';
import {MonthAndYear} from './js-client.vehicles_2024-11-01.model/MonthAndYear.js';
import {Pagination} from './js-client.vehicles_2024-11-01.model/Pagination.js';
import {Vehicle} from './js-client.vehicles_2024-11-01.model/Vehicle.js';
import {VehicleIdentifiers} from './js-client.vehicles_2024-11-01.model/VehicleIdentifiers.js';
import {VehicleStandard} from './js-client.vehicles_2024-11-01.model/VehicleStandard.js';
import {VehicleStatusInCatalog} from './js-client.vehicles_2024-11-01.model/VehicleStatusInCatalog.js';
import {VehiclesResponse} from './js-client.vehicles_2024-11-01.model/VehiclesResponse.js';
import {Year} from './js-client.vehicles_2024-11-01.model/Year.js';
import {AutomotiveApi} from './js-client.vehicles_2024-11-01.api/AutomotiveApi.js';
import {VehiclesApi} from './js-client.vehicles_2024-11-01.api/VehiclesApi.js';


/**
* The_Selling_Partner_API_for_Automotive_provides_programmatic_access_to_information_needed_by_selling_partners_to_provide_compatibility_information_about_their_listed_products_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var TheSellingPartnerApiForAutomotive = require('vehicles_2024-11-01/index'); // See note below*.
* var xxxSvc = new TheSellingPartnerApiForAutomotive.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new TheSellingPartnerApiForAutomotive.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['vehicles_2024-11-01/index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new TheSellingPartnerApiForAutomotive.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new TheSellingPartnerApiForAutomotive.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module vehicles_2024-11-01/index
* @version 2024-11-01
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:vehicles_2024-11-01/ApiClient}
     */
    ApiClient,

    /**
     * The EngineOutput model constructor.
     * @property {module:vehicles_2024-11-01/js-client.vehicles_2024-11-01.model/EngineOutput}
     */
    EngineOutput,

    /**
     * The EngineOutputUnit model constructor.
     * @property {module:vehicles_2024-11-01/js-client.vehicles_2024-11-01.model/EngineOutputUnit}
     */
    EngineOutputUnit,

    /**
     * The Error model constructor.
     * @property {module:vehicles_2024-11-01/js-client.vehicles_2024-11-01.model/Error}
     */
    Error,

    /**
     * The ErrorList model constructor.
     * @property {module:vehicles_2024-11-01/js-client.vehicles_2024-11-01.model/ErrorList}
     */
    ErrorList,

    /**
     * The Month model constructor.
     * @property {module:vehicles_2024-11-01/js-client.vehicles_2024-11-01.model/Month}
     */
    Month,

    /**
     * The MonthAndYear model constructor.
     * @property {module:vehicles_2024-11-01/js-client.vehicles_2024-11-01.model/MonthAndYear}
     */
    MonthAndYear,

    /**
     * The Pagination model constructor.
     * @property {module:vehicles_2024-11-01/js-client.vehicles_2024-11-01.model/Pagination}
     */
    Pagination,

    /**
     * The Vehicle model constructor.
     * @property {module:vehicles_2024-11-01/js-client.vehicles_2024-11-01.model/Vehicle}
     */
    Vehicle,

    /**
     * The VehicleIdentifiers model constructor.
     * @property {module:vehicles_2024-11-01/js-client.vehicles_2024-11-01.model/VehicleIdentifiers}
     */
    VehicleIdentifiers,

    /**
     * The VehicleStandard model constructor.
     * @property {module:vehicles_2024-11-01/js-client.vehicles_2024-11-01.model/VehicleStandard}
     */
    VehicleStandard,

    /**
     * The VehicleStatusInCatalog model constructor.
     * @property {module:vehicles_2024-11-01/js-client.vehicles_2024-11-01.model/VehicleStatusInCatalog}
     */
    VehicleStatusInCatalog,

    /**
     * The VehiclesResponse model constructor.
     * @property {module:vehicles_2024-11-01/js-client.vehicles_2024-11-01.model/VehiclesResponse}
     */
    VehiclesResponse,

    /**
     * The Year model constructor.
     * @property {module:vehicles_2024-11-01/js-client.vehicles_2024-11-01.model/Year}
     */
    Year,

    /**
    * The AutomotiveApi service constructor.
    * @property {module:vehicles_2024-11-01/js-client.vehicles_2024-11-01.api/AutomotiveApi}
    */
    AutomotiveApi,

    /**
    * The VehiclesApi service constructor.
    * @property {module:vehicles_2024-11-01/js-client.vehicles_2024-11-01.api/VehiclesApi}
    */
    VehiclesApi
};
