/*
 * Selling Partner API for Retail Procurement Shipments
 * The Selling Partner API for Retail Procurement Shipments provides programmatic access to retail shipping data for vendors.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';
import {Pagination} from './Pagination.js';
import {TransportLabel} from './TransportLabel.js';

/**
 * The TransportationLabels model module.
 * @module vendorShipments/js-client.vendorShipments.model/TransportationLabels
 * @version v1
 */
export class TransportationLabels {
  /**
   * Constructs a new <code>TransportationLabels</code>.
   * The request schema for the GetShipmentLabels operation.
   * @alias module:vendorShipments/js-client.vendorShipments.model/TransportationLabels
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>TransportationLabels</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:vendorShipments/js-client.vendorShipments.model/TransportationLabels} obj Optional instance to populate.
   * @return {module:vendorShipments/js-client.vendorShipments.model/TransportationLabels} The populated <code>TransportationLabels</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      switch(typeof data) {
        case 'string':
          obj = String(data);
          break;
        case 'number':
          obj = Number(data);
          break;
        case 'boolean':
          obj = Boolean(data);
          break;
      }
      obj = obj || new TransportationLabels();
      if (data.hasOwnProperty('pagination'))
        obj.pagination = Pagination.constructFromObject(data['pagination']);
      if (data.hasOwnProperty('transportLabels'))
        obj.transportLabels = ApiClient.convertToType(data['transportLabels'], [TransportLabel]);
    }
    return obj;
  }
}

/**
 * @member {module:vendorShipments/js-client.vendorShipments.model/Pagination} pagination
 */
TransportationLabels.prototype.pagination = undefined;

/**
 * A list of one or more ShipmentLabels.
 * @member {Array.<module:vendorShipments/js-client.vendorShipments.model/TransportLabel>} transportLabels
 */
TransportationLabels.prototype.transportLabels = undefined;


