/*
 * Selling Partner API for Retail Procurement Shipments
 * The Selling Partner API for Retail Procurement Shipments provides programmatic access to retail shipping data for vendors.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';
import {PartyIdentification} from './PartyIdentification.js';

/**
 * The VendorDetails model module.
 * @module vendorShipments/js-client.vendorShipments.model/VendorDetails
 * @version v1
 */
export class VendorDetails {
  /**
   * Constructs a new <code>VendorDetails</code>.
   * Vendor Details as part of Label response.
   * @alias module:vendorShipments/js-client.vendorShipments.model/VendorDetails
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>VendorDetails</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:vendorShipments/js-client.vendorShipments.model/VendorDetails} obj Optional instance to populate.
   * @return {module:vendorShipments/js-client.vendorShipments.model/VendorDetails} The populated <code>VendorDetails</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      switch(typeof data) {
        case 'string':
          obj = String(data);
          break;
        case 'number':
          obj = Number(data);
          break;
        case 'boolean':
          obj = Boolean(data);
          break;
      }
      obj = obj || new VendorDetails();
      if (data.hasOwnProperty('sellingParty'))
        obj.sellingParty = PartyIdentification.constructFromObject(data['sellingParty']);
      if (data.hasOwnProperty('vendorShipmentIdentifier'))
        obj.vendorShipmentIdentifier = ApiClient.convertToType(data['vendorShipmentIdentifier'], 'String');
    }
    return obj;
  }
}

/**
 * Name/Address and tax details of the selling party.
 * @member {module:vendorShipments/js-client.vendorShipments.model/PartyIdentification} sellingParty
 */
VendorDetails.prototype.sellingParty = undefined;

/**
 * Unique vendor shipment id which is not used in last 365 days
 * @member {String} vendorShipmentIdentifier
 */
VendorDetails.prototype.vendorShipmentIdentifier = undefined;


