/*
 * Selling Partner API for Retail Procurement Payments
 * The Selling Partner API for Retail Procurement Payments provides programmatic access to vendors payments data.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';

/**
 * Enum class NetCostUnitOfMeasure.
 * @enum {String}
 * @readonly
 */
const NetCostUnitOfMeasure = {
  /**
   * value: "POUNDS"
   * @const
   */
  POUNDS: "POUNDS",

  /**
   * value: "OUNCES"
   * @const
   */
  OUNCES: "OUNCES",

  /**
   * value: "GRAMS"
   * @const
   */
  GRAMS: "GRAMS",

  /**
   * value: "KILOGRAMS"
   * @const
   */
  KILOGRAMS: "KILOGRAMS",

  /**
   * Returns a <code>NetCostUnitOfMeasure</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
   * @return {module:vendorInvoices/js-client.vendorInvoices.model/NetCostUnitOfMeasure} The enum <code>NetCostUnitOfMeasure</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {NetCostUnitOfMeasure};
