/*
 * The Selling Partner API for Transfers.
 * The Selling Partner API for Transfers enables selling partners to retrieve payment methods and initiate payouts for their seller accounts. This API supports the following marketplaces: DE, FR, IT, ES, SE, NL, PL, and BE.
 *
 * OpenAPI spec version: 2024-06-01
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';
import {MarketplaceId} from './MarketplaceId.js';

/**
 * The InitiatePayoutRequest model module.
 * @module transfers_2024-06-01/js-client.transfers_2024-06-01.model/InitiatePayoutRequest
 * @version 2024-06-01
 */
export class InitiatePayoutRequest {
  /**
   * Constructs a new <code>InitiatePayoutRequest</code>.
   * The request schema for the `initiatePayout` operation.
   * @alias module:transfers_2024-06-01/js-client.transfers_2024-06-01.model/InitiatePayoutRequest
   * @class
   * @param marketplaceId {module:transfers_2024-06-01/js-client.transfers_2024-06-01.model/MarketplaceId} The identifier of the Amazon marketplace. This API supports the following marketplaces: DE, FR, IT, ES, SE, NL, PL, and BE. For a list of possible marketplace IDs, refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids).
   * @param accountType {String} The account type in the selected marketplace for which a payout must be initiated. For supported EU marketplaces, the only account type is `Standard Orders`.
   */
  constructor(marketplaceId, accountType) {
    this.marketplaceId = marketplaceId;
    this.accountType = accountType;
  }

  /**
   * Constructs a <code>InitiatePayoutRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:transfers_2024-06-01/js-client.transfers_2024-06-01.model/InitiatePayoutRequest} obj Optional instance to populate.
   * @return {module:transfers_2024-06-01/js-client.transfers_2024-06-01.model/InitiatePayoutRequest} The populated <code>InitiatePayoutRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      switch(typeof data) {
        case 'string':
          obj = String(data);
          break;
        case 'number':
          obj = Number(data);
          break;
        case 'boolean':
          obj = Boolean(data);
          break;
      }
      obj = obj || new InitiatePayoutRequest();
      if (data.hasOwnProperty('marketplaceId'))
        obj.marketplaceId = MarketplaceId.constructFromObject(data['marketplaceId']);
      if (data.hasOwnProperty('accountType'))
        obj.accountType = ApiClient.convertToType(data['accountType'], 'String');
    }
    return obj;
  }
}

/**
 * The identifier of the Amazon marketplace. This API supports the following marketplaces: DE, FR, IT, ES, SE, NL, PL, and BE. For a list of possible marketplace IDs, refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids).
 * @member {module:transfers_2024-06-01/js-client.transfers_2024-06-01.model/MarketplaceId} marketplaceId
 */
InitiatePayoutRequest.prototype.marketplaceId = undefined;

/**
 * The account type in the selected marketplace for which a payout must be initiated. For supported EU marketplaces, the only account type is `Standard Orders`.
 * @member {String} accountType
 */
InitiatePayoutRequest.prototype.accountType = undefined;


