/*
 * The Selling Partner API for Transfers.
 * The Selling Partner API for Transfers enables selling partners to retrieve payment methods and initiate payouts for their seller accounts. This API supports the following marketplaces: DE, FR, IT, ES, SE, NL, PL, and BE.
 *
 * OpenAPI spec version: 2024-06-01
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';

/**
 * Enum class PaymentMethodType.
 * @enum {String}
 * @readonly
 */
const PaymentMethodType = {
  /**
   * value: "BANK_ACCOUNT"
   * @const
   */
  BANK_ACCOUNT: "BANK_ACCOUNT",

  /**
   * value: "CARD"
   * @const
   */
  CARD: "CARD",

  /**
   * value: "SELLER_WALLET"
   * @const
   */
  SELLER_WALLET: "SELLER_WALLET",

  /**
   * Returns a <code>PaymentMethodType</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
   * @return {module:transfers_2024-06-01/js-client.transfers_2024-06-01.model/PaymentMethodType} The enum <code>PaymentMethodType</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {PaymentMethodType};
