/*
 * The Selling Partner API for FBA inbound operations.
 * The Selling Partner API for Fulfillment By Amazon (FBA) Inbound. The FBA Inbound API enables building inbound workflows to create, manage, and send shipments into Amazon's fulfillment network. The API has interoperability with the Send-to-Amazon user interface.
 *
 * OpenAPI spec version: 2024-03-20
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';
import {BoxIdentifierType} from './BoxIdentifierType.js';

/**
 * The BoxIdentifierInput model module.
 * @module fulfillmentInbound_2024-03-20/js-client.fulfillmentInbound_2024-03-20.model/BoxIdentifierInput
 * @version 2024-03-20
 */
export class BoxIdentifierInput {
  /**
   * Constructs a new <code>BoxIdentifierInput</code>.
   * Input information for updating a box identifier.
   * @alias module:fulfillmentInbound_2024-03-20/js-client.fulfillmentInbound_2024-03-20.model/BoxIdentifierInput
   * @class
   * @param externalContainerIdentifierType {module:fulfillmentInbound_2024-03-20/js-client.fulfillmentInbound_2024-03-20.model/BoxIdentifierType} 
   * @param packageId {String} Primary key to uniquely identify a Box Package.
   */
  constructor(externalContainerIdentifierType, packageId) {
    this.externalContainerIdentifierType = externalContainerIdentifierType;
    this.packageId = packageId;
  }

  /**
   * Constructs a <code>BoxIdentifierInput</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:fulfillmentInbound_2024-03-20/js-client.fulfillmentInbound_2024-03-20.model/BoxIdentifierInput} obj Optional instance to populate.
   * @return {module:fulfillmentInbound_2024-03-20/js-client.fulfillmentInbound_2024-03-20.model/BoxIdentifierInput} The populated <code>BoxIdentifierInput</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      switch(typeof data) {
        case 'string':
          obj = String(data);
          break;
        case 'number':
          obj = Number(data);
          break;
        case 'boolean':
          obj = Boolean(data);
          break;
      }
      obj = obj || new BoxIdentifierInput();
      if (data.hasOwnProperty('externalContainerIdentifier'))
        obj.externalContainerIdentifier = ApiClient.convertToType(data['externalContainerIdentifier'], 'String');
      if (data.hasOwnProperty('externalContainerIdentifierType'))
        obj.externalContainerIdentifierType = BoxIdentifierType.constructFromObject(data['externalContainerIdentifierType']);
      if (data.hasOwnProperty('packageId'))
        obj.packageId = ApiClient.convertToType(data['packageId'], 'String');
    }
    return obj;
  }
}

/**
 * The custom identifier for a certain box.
 * @member {String} externalContainerIdentifier
 */
BoxIdentifierInput.prototype.externalContainerIdentifier = undefined;

/**
 * @member {module:fulfillmentInbound_2024-03-20/js-client.fulfillmentInbound_2024-03-20.model/BoxIdentifierType} externalContainerIdentifierType
 */
BoxIdentifierInput.prototype.externalContainerIdentifierType = undefined;

/**
 * Primary key to uniquely identify a Box Package.
 * @member {String} packageId
 */
BoxIdentifierInput.prototype.packageId = undefined;


