/*
 * The Selling Partner API for Amazon Seller Wallet Open Banking API Spec.  For more information, refer to the [Seller Wallet Open Banking API Use Case Guide](doc:seller-wallet-open-banking-api-v2024-03-01-use-case-guide).
 * The Selling Partner API for Seller Wallet (Seller Wallet API) provides financial information that is relevant to a seller's Seller Wallet account. You can obtain financial events, balances, and transfer schedules for Seller Wallet accounts. You can also schedule and initiate transactions.
 *
 * OpenAPI spec version: 2024-03-01
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';
import {BankAccount} from './BankAccount.js';

/**
 * The BankAccountListing model module.
 * @module sellerWallet_2024-03-01/js-client.sellerWallet_2024-03-01.model/BankAccountListing
 * @version 2024-03-01
 */
export class BankAccountListing {
  /**
   * Constructs a new <code>BankAccountListing</code>.
   * Struct that holds collection of accounts.
   * @alias module:sellerWallet_2024-03-01/js-client.sellerWallet_2024-03-01.model/BankAccountListing
   * @class
   * @param accounts {Array.<module:sellerWallet_2024-03-01/js-client.sellerWallet_2024-03-01.model/BankAccount>} Collection that holds BankAccount 
   */
  constructor(accounts) {
    this.accounts = accounts;
  }

  /**
   * Constructs a <code>BankAccountListing</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:sellerWallet_2024-03-01/js-client.sellerWallet_2024-03-01.model/BankAccountListing} obj Optional instance to populate.
   * @return {module:sellerWallet_2024-03-01/js-client.sellerWallet_2024-03-01.model/BankAccountListing} The populated <code>BankAccountListing</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      switch(typeof data) {
        case 'string':
          obj = String(data);
          break;
        case 'number':
          obj = Number(data);
          break;
        case 'boolean':
          obj = Boolean(data);
          break;
      }
      obj = obj || new BankAccountListing();
      if (data.hasOwnProperty('accounts'))
        obj.accounts = ApiClient.convertToType(data['accounts'], [BankAccount]);
    }
    return obj;
  }
}

/**
 * Collection that holds BankAccount 
 * @member {Array.<module:sellerWallet_2024-03-01/js-client.sellerWallet_2024-03-01.model/BankAccount>} accounts
 */
BankAccountListing.prototype.accounts = undefined;


