/*
 * The Selling Partner API for Amazon Seller Wallet Open Banking API Spec.  For more information, refer to the [Seller Wallet Open Banking API Use Case Guide](doc:seller-wallet-open-banking-api-v2024-03-01-use-case-guide).
 * The Selling Partner API for Seller Wallet (Seller Wallet API) provides financial information that is relevant to a seller's Seller Wallet account. You can obtain financial events, balances, and transfer schedules for Seller Wallet accounts. You can also schedule and initiate transactions.
 *
 * OpenAPI spec version: 2024-03-01
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';

/**
 * Enum class BankAccountOwnershipType.
 * @enum {String}
 * @readonly
 */
const BankAccountOwnershipType = {
  /**
   * value: "THIRD_PARTY"
   * @const
   */
  THIRD_PARTY: "THIRD_PARTY",

  /**
   * value: "SELF"
   * @const
   */
  SELF: "SELF",

  /**
   * value: "GOVERNMENT"
   * @const
   */
  GOVERNMENT: "GOVERNMENT",

  /**
   * Returns a <code>BankAccountOwnershipType</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
   * @return {module:sellerWallet_2024-03-01/js-client.sellerWallet_2024-03-01.model/BankAccountOwnershipType} The enum <code>BankAccountOwnershipType</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {BankAccountOwnershipType};
