/*
 * The Selling Partner API for Amazon Seller Wallet Open Banking API Spec.  For more information, refer to the [Seller Wallet Open Banking API Use Case Guide](doc:seller-wallet-open-banking-api-v2024-03-01-use-case-guide).
 * The Selling Partner API for Seller Wallet (Seller Wallet API) provides financial information that is relevant to a seller's Seller Wallet account. You can obtain financial events, balances, and transfer schedules for Seller Wallet accounts. You can also schedule and initiate transactions.
 *
 * OpenAPI spec version: 2024-03-01
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';
import {TransferSchedule} from './TransferSchedule.js';

/**
 * The TransferScheduleListing model module.
 * @module sellerWallet_2024-03-01/js-client.sellerWallet_2024-03-01.model/TransferScheduleListing
 * @version 2024-03-01
 */
export class TransferScheduleListing {
  /**
   * Constructs a new <code>TransferScheduleListing</code>.
   * Struct that holds collection of transfer schedules.
   * @alias module:sellerWallet_2024-03-01/js-client.sellerWallet_2024-03-01.model/TransferScheduleListing
   * @class
   * @param transferSchedules {Array.<module:sellerWallet_2024-03-01/js-client.sellerWallet_2024-03-01.model/TransferSchedule>} Collection that holds list of Transfer Schedules 
   */
  constructor(transferSchedules) {
    this.transferSchedules = transferSchedules;
  }

  /**
   * Constructs a <code>TransferScheduleListing</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:sellerWallet_2024-03-01/js-client.sellerWallet_2024-03-01.model/TransferScheduleListing} obj Optional instance to populate.
   * @return {module:sellerWallet_2024-03-01/js-client.sellerWallet_2024-03-01.model/TransferScheduleListing} The populated <code>TransferScheduleListing</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      switch(typeof data) {
        case 'string':
          obj = String(data);
          break;
        case 'number':
          obj = Number(data);
          break;
        case 'boolean':
          obj = Boolean(data);
          break;
      }
      obj = obj || new TransferScheduleListing();
      if (data.hasOwnProperty('nextPageToken'))
        obj.nextPageToken = ApiClient.convertToType(data['nextPageToken'], 'String');
      if (data.hasOwnProperty('transferSchedules'))
        obj.transferSchedules = ApiClient.convertToType(data['transferSchedules'], [TransferSchedule]);
    }
    return obj;
  }
}

/**
 * If present, use this pagination token to retrieve the next page of supply sources, if not provided the API will return same response. The field will only be provided when the list is greater than 100.
 * @member {String} nextPageToken
 */
TransferScheduleListing.prototype.nextPageToken = undefined;

/**
 * Collection that holds list of Transfer Schedules 
 * @member {Array.<module:sellerWallet_2024-03-01/js-client.sellerWallet_2024-03-01.model/TransferSchedule>} transferSchedules
 */
TransferScheduleListing.prototype.transferSchedules = undefined;


