/*
 * Selling Partner API for Catalog Items
 * The Selling Partner API for Catalog Items helps you programmatically retrieve item details for items in the catalog.
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from './ApiClient.js';
import {Categories} from './js-client.catalogItemsV0.model/Categories.js';
import {Error} from './js-client.catalogItemsV0.model/Error.js';
import {ErrorList} from './js-client.catalogItemsV0.model/ErrorList.js';
import {ListCatalogCategoriesResponse} from './js-client.catalogItemsV0.model/ListCatalogCategoriesResponse.js';
import {ListOfCategories} from './js-client.catalogItemsV0.model/ListOfCategories.js';
import {CatalogApi} from './js-client.catalogItemsV0.api/CatalogApi.js';


/**
* The_Selling_Partner_API_for_Catalog_Items_helps_you_programmatically_retrieve_item_details_for_items_in_the_catalog_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var SellingPartnerApiForCatalogItems = require('catalogItemsV0/index'); // See note below*.
* var xxxSvc = new SellingPartnerApiForCatalogItems.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new SellingPartnerApiForCatalogItems.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['catalogItemsV0/index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new SellingPartnerApiForCatalogItems.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new SellingPartnerApiForCatalogItems.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module catalogItemsV0/index
* @version v0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:catalogItemsV0/ApiClient}
     */
    ApiClient,

    /**
     * The Categories model constructor.
     * @property {module:catalogItemsV0/js-client.catalogItemsV0.model/Categories}
     */
    Categories,

    /**
     * The Error model constructor.
     * @property {module:catalogItemsV0/js-client.catalogItemsV0.model/Error}
     */
    Error,

    /**
     * The ErrorList model constructor.
     * @property {module:catalogItemsV0/js-client.catalogItemsV0.model/ErrorList}
     */
    ErrorList,

    /**
     * The ListCatalogCategoriesResponse model constructor.
     * @property {module:catalogItemsV0/js-client.catalogItemsV0.model/ListCatalogCategoriesResponse}
     */
    ListCatalogCategoriesResponse,

    /**
     * The ListOfCategories model constructor.
     * @property {module:catalogItemsV0/js-client.catalogItemsV0.model/ListOfCategories}
     */
    ListOfCategories,

    /**
    * The CatalogApi service constructor.
    * @property {module:catalogItemsV0/js-client.catalogItemsV0.api/CatalogApi}
    */
    CatalogApi
};
