/*
 * The Selling Partner API for CustomerFeedback
 * The Selling Partner API for Customer Feedback (Customer Feedback API) provides information about customer reviews and returns at both the item and browse node level.
 *
 * OpenAPI spec version: 2024-06-01
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';
import {BrowseNodeReviewTrend} from './BrowseNodeReviewTrend.js';

/**
 * The BrowseNodeReviewTrends model module.
 * @module customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeReviewTrends
 * @version 2024-06-01
 */
export class BrowseNodeReviewTrends {
  /**
   * Constructs a new <code>BrowseNodeReviewTrends</code>.
   * The 10 most positive and most negative review topics for all items in a browse node.
   * @alias module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeReviewTrends
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>BrowseNodeReviewTrends</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeReviewTrends} obj Optional instance to populate.
   * @return {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeReviewTrends} The populated <code>BrowseNodeReviewTrends</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      switch(typeof data) {
        case 'string':
          obj = String(data);
          break;
        case 'number':
          obj = Number(data);
          break;
        case 'boolean':
          obj = Boolean(data);
          break;
      }
      obj = obj || new BrowseNodeReviewTrends();
      if (data.hasOwnProperty('positiveTopics'))
        obj.positiveTopics = ApiClient.convertToType(data['positiveTopics'], [BrowseNodeReviewTrend]);
      if (data.hasOwnProperty('negativeTopics'))
        obj.negativeTopics = ApiClient.convertToType(data['negativeTopics'], [BrowseNodeReviewTrend]);
    }
    return obj;
  }
}

/**
 * The trends of the most positive review topics. The percentage of reviews that contain the topic across all products in the requested browse node determine the topic's placement in the list. This value is `null` if there aren't enough positive reviews for the requested browse node.  **Max length:** 10
 * @member {Array.<module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeReviewTrend>} positiveTopics
 */
BrowseNodeReviewTrends.prototype.positiveTopics = undefined;

/**
 * The trends of the most negative review topics. The percentage of reviews that contain the topic across all products in the requested browse node determine the topic's placement in the list. This value is `null` if there aren't enough positive reviews for the requested browse node.  **Max length:** 10
 * @member {Array.<module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeReviewTrend>} negativeTopics
 */
BrowseNodeReviewTrends.prototype.negativeTopics = undefined;


