/*
 * The Selling Partner API for CustomerFeedback
 * The Selling Partner API for Customer Feedback (Customer Feedback API) provides information about customer reviews and returns at both the item and browse node level.
 *
 * OpenAPI spec version: 2024-06-01
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';
import {BrowseNodeReturnTrend} from './BrowseNodeReturnTrend.js';
import {DateRange} from './DateRange.js';

/**
 * The BrowseNodeReturnTrendsResponse model module.
 * @module customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeReturnTrendsResponse
 * @version 2024-06-01
 */
export class BrowseNodeReturnTrendsResponse {
  /**
   * Constructs a new <code>BrowseNodeReturnTrendsResponse</code>.
   * The response for the `getBrowseNodeReturnTrends` operation.
   * @alias module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeReturnTrendsResponse
   * @class
   * @param browseNodeId {String} The requested browse node id. A browse node id is the unique identifier of a given browse node.
   * @param displayName {String} The display name of the browse node, as visible on the Amazon retail website.
   * @param marketplaceId {String} The requested marketplace id.
   * @param countryCode {String} The two digit country code of requested marketplace id, in ISO 3166-1 alpha-2 format.
   * @param dateRange {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/DateRange} The range of dates during which the returns were made.
   * @param returnTrends {Array.<module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeReturnTrend>} The browse node return trends.
   */
  constructor(browseNodeId, displayName, marketplaceId, countryCode, dateRange, returnTrends) {
    this.browseNodeId = browseNodeId;
    this.displayName = displayName;
    this.marketplaceId = marketplaceId;
    this.countryCode = countryCode;
    this.dateRange = dateRange;
    this.returnTrends = returnTrends;
  }

  /**
   * Constructs a <code>BrowseNodeReturnTrendsResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeReturnTrendsResponse} obj Optional instance to populate.
   * @return {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeReturnTrendsResponse} The populated <code>BrowseNodeReturnTrendsResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      switch(typeof data) {
        case 'string':
          obj = String(data);
          break;
        case 'number':
          obj = Number(data);
          break;
        case 'boolean':
          obj = Boolean(data);
          break;
      }
      obj = obj || new BrowseNodeReturnTrendsResponse();
      if (data.hasOwnProperty('browseNodeId'))
        obj.browseNodeId = ApiClient.convertToType(data['browseNodeId'], 'String');
      if (data.hasOwnProperty('displayName'))
        obj.displayName = ApiClient.convertToType(data['displayName'], 'String');
      if (data.hasOwnProperty('marketplaceId'))
        obj.marketplaceId = ApiClient.convertToType(data['marketplaceId'], 'String');
      if (data.hasOwnProperty('countryCode'))
        obj.countryCode = ApiClient.convertToType(data['countryCode'], 'String');
      if (data.hasOwnProperty('dateRange'))
        obj.dateRange = DateRange.constructFromObject(data['dateRange']);
      if (data.hasOwnProperty('returnTrends'))
        obj.returnTrends = ApiClient.convertToType(data['returnTrends'], [BrowseNodeReturnTrend]);
    }
    return obj;
  }
}

/**
 * The requested browse node id. A browse node id is the unique identifier of a given browse node.
 * @member {String} browseNodeId
 */
BrowseNodeReturnTrendsResponse.prototype.browseNodeId = undefined;

/**
 * The display name of the browse node, as visible on the Amazon retail website.
 * @member {String} displayName
 */
BrowseNodeReturnTrendsResponse.prototype.displayName = undefined;

/**
 * The requested marketplace id.
 * @member {String} marketplaceId
 */
BrowseNodeReturnTrendsResponse.prototype.marketplaceId = undefined;

/**
 * The two digit country code of requested marketplace id, in ISO 3166-1 alpha-2 format.
 * @member {String} countryCode
 */
BrowseNodeReturnTrendsResponse.prototype.countryCode = undefined;

/**
 * The range of dates during which the returns were made.
 * @member {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/DateRange} dateRange
 */
BrowseNodeReturnTrendsResponse.prototype.dateRange = undefined;

/**
 * The browse node return trends.
 * @member {Array.<module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeReturnTrend>} returnTrends
 */
BrowseNodeReturnTrendsResponse.prototype.returnTrends = undefined;


