/*
 * The Selling Partner API for CustomerFeedback
 * The Selling Partner API for Customer Feedback (Customer Feedback API) provides information about customer reviews and returns at both the item and browse node level.
 *
 * OpenAPI spec version: 2024-06-01
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';

/**
 * The BrowseNodeAllStarRatingImpact model module.
 * @module customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeAllStarRatingImpact
 * @version 2024-06-01
 */
export class BrowseNodeAllStarRatingImpact {
  /**
   * Constructs a new <code>BrowseNodeAllStarRatingImpact</code>.
   * The effects of a topic on the star ratings in a browse node.
   * @alias module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeAllStarRatingImpact
   * @class
   * @param topTwentyFivePercentProducts {Number} The effect of the topic on the star rating of the top 25 percent of products in the browse node. This value can be positive or negative.
   * @param allProducts {Number} The effect of the topic on the star rating of all products in the browse node. This value can be positive or negative.
   */
  constructor(topTwentyFivePercentProducts, allProducts) {
    this.topTwentyFivePercentProducts = topTwentyFivePercentProducts;
    this.allProducts = allProducts;
  }

  /**
   * Constructs a <code>BrowseNodeAllStarRatingImpact</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeAllStarRatingImpact} obj Optional instance to populate.
   * @return {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeAllStarRatingImpact} The populated <code>BrowseNodeAllStarRatingImpact</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      switch(typeof data) {
        case 'string':
          obj = String(data);
          break;
        case 'number':
          obj = Number(data);
          break;
        case 'boolean':
          obj = Boolean(data);
          break;
      }
      obj = obj || new BrowseNodeAllStarRatingImpact();
      if (data.hasOwnProperty('topTwentyFivePercentProducts'))
        obj.topTwentyFivePercentProducts = ApiClient.convertToType(data['topTwentyFivePercentProducts'], 'Number');
      if (data.hasOwnProperty('allProducts'))
        obj.allProducts = ApiClient.convertToType(data['allProducts'], 'Number');
    }
    return obj;
  }
}

/**
 * The effect of the topic on the star rating of the top 25 percent of products in the browse node. This value can be positive or negative.
 * @member {Number} topTwentyFivePercentProducts
 */
BrowseNodeAllStarRatingImpact.prototype.topTwentyFivePercentProducts = undefined;

/**
 * The effect of the topic on the star rating of all products in the browse node. This value can be positive or negative.
 * @member {Number} allProducts
 */
BrowseNodeAllStarRatingImpact.prototype.allProducts = undefined;


