/*
 * The Selling Partner API for CustomerFeedback
 * The Selling Partner API for Customer Feedback (Customer Feedback API) provides information about customer reviews and returns at both the item and browse node level.
 *
 * OpenAPI spec version: 2024-06-01
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';
import {BrowseNodeAllOccurrence} from './BrowseNodeAllOccurrence.js';

/**
 * The BrowseNodeReviewTrendMetrics model module.
 * @module customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeReviewTrendMetrics
 * @version 2024-06-01
 */
export class BrowseNodeReviewTrendMetrics {
  /**
   * Constructs a new <code>BrowseNodeReviewTrendMetrics</code>.
   * The browse node review topic metrics.
   * @alias module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeReviewTrendMetrics
   * @class
   * @param occurrencePercentage {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeAllOccurrence} The percent of reviews that mention the topic.
   */
  constructor(occurrencePercentage) {
    this.occurrencePercentage = occurrencePercentage;
  }

  /**
   * Constructs a <code>BrowseNodeReviewTrendMetrics</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeReviewTrendMetrics} obj Optional instance to populate.
   * @return {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeReviewTrendMetrics} The populated <code>BrowseNodeReviewTrendMetrics</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      switch(typeof data) {
        case 'string':
          obj = String(data);
          break;
        case 'number':
          obj = Number(data);
          break;
        case 'boolean':
          obj = Boolean(data);
          break;
      }
      obj = obj || new BrowseNodeReviewTrendMetrics();
      if (data.hasOwnProperty('occurrencePercentage'))
        obj.occurrencePercentage = BrowseNodeAllOccurrence.constructFromObject(data['occurrencePercentage']);
    }
    return obj;
  }
}

/**
 * The percent of reviews that mention the topic.
 * @member {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeAllOccurrence} occurrencePercentage
 */
BrowseNodeReviewTrendMetrics.prototype.occurrencePercentage = undefined;


