/*
 * The Selling Partner API for CustomerFeedback
 * The Selling Partner API for Customer Feedback (Customer Feedback API) provides information about customer reviews and returns at both the item and browse node level.
 *
 * OpenAPI spec version: 2024-06-01
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';
import {BrowseNodeReviewTrendMetrics} from './BrowseNodeReviewTrendMetrics.js';
import {DateRange} from './DateRange.js';

/**
 * The BrowseNodeReviewTrendPoint model module.
 * @module customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeReviewTrendPoint
 * @version 2024-06-01
 */
export class BrowseNodeReviewTrendPoint {
  /**
   * Constructs a new <code>BrowseNodeReviewTrendPoint</code>.
   * The browse node's review metrics for a certain month.
   * @alias module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeReviewTrendPoint
   * @class
   * @param dateRange {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/DateRange} The date range of the browse node review trend metric.
   * @param browseNodeMetrics {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeReviewTrendMetrics} The browse node review trend metrics.
   */
  constructor(dateRange, browseNodeMetrics) {
    this.dateRange = dateRange;
    this.browseNodeMetrics = browseNodeMetrics;
  }

  /**
   * Constructs a <code>BrowseNodeReviewTrendPoint</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeReviewTrendPoint} obj Optional instance to populate.
   * @return {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeReviewTrendPoint} The populated <code>BrowseNodeReviewTrendPoint</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      switch(typeof data) {
        case 'string':
          obj = String(data);
          break;
        case 'number':
          obj = Number(data);
          break;
        case 'boolean':
          obj = Boolean(data);
          break;
      }
      obj = obj || new BrowseNodeReviewTrendPoint();
      if (data.hasOwnProperty('dateRange'))
        obj.dateRange = DateRange.constructFromObject(data['dateRange']);
      if (data.hasOwnProperty('browseNodeMetrics'))
        obj.browseNodeMetrics = BrowseNodeReviewTrendMetrics.constructFromObject(data['browseNodeMetrics']);
    }
    return obj;
  }
}

/**
 * The date range of the browse node review trend metric.
 * @member {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/DateRange} dateRange
 */
BrowseNodeReviewTrendPoint.prototype.dateRange = undefined;

/**
 * The browse node review trend metrics.
 * @member {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeReviewTrendMetrics} browseNodeMetrics
 */
BrowseNodeReviewTrendPoint.prototype.browseNodeMetrics = undefined;


