/*
 * The Selling Partner API for CustomerFeedback
 * The Selling Partner API for Customer Feedback (Customer Feedback API) provides information about customer reviews and returns at both the item and browse node level.
 *
 * OpenAPI spec version: 2024-06-01
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';
import {BrowseNodeTrendMetrics} from './BrowseNodeTrendMetrics.js';

/**
 * The BrowseNodeReturnTopics model module.
 * @module customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeReturnTopics
 * @version 2024-06-01
 */
export class BrowseNodeReturnTopics {
  /**
   * Constructs a new <code>BrowseNodeReturnTopics</code>.
   * Topics from returns for all items in a browse node.
   * @alias module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeReturnTopics
   * @class
   * @param topic {String} The name of the return feedback topic .
   * @param browseNodeMetrics {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeTrendMetrics} The browse node return topic metrics.
   */
  constructor(topic, browseNodeMetrics) {
    this.topic = topic;
    this.browseNodeMetrics = browseNodeMetrics;
  }

  /**
   * Constructs a <code>BrowseNodeReturnTopics</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeReturnTopics} obj Optional instance to populate.
   * @return {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeReturnTopics} The populated <code>BrowseNodeReturnTopics</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      switch(typeof data) {
        case 'string':
          obj = String(data);
          break;
        case 'number':
          obj = Number(data);
          break;
        case 'boolean':
          obj = Boolean(data);
          break;
      }
      obj = obj || new BrowseNodeReturnTopics();
      if (data.hasOwnProperty('topic'))
        obj.topic = ApiClient.convertToType(data['topic'], 'String');
      if (data.hasOwnProperty('browseNodeMetrics'))
        obj.browseNodeMetrics = BrowseNodeTrendMetrics.constructFromObject(data['browseNodeMetrics']);
    }
    return obj;
  }
}

/**
 * The name of the return feedback topic .
 * @member {String} topic
 */
BrowseNodeReturnTopics.prototype.topic = undefined;

/**
 * The browse node return topic metrics.
 * @member {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeTrendMetrics} browseNodeMetrics
 */
BrowseNodeReturnTopics.prototype.browseNodeMetrics = undefined;


