/*
 * The Selling Partner API for CustomerFeedback
 * The Selling Partner API for Customer Feedback (Customer Feedback API) provides information about customer reviews and returns at both the item and browse node level.
 *
 * OpenAPI spec version: 2024-06-01
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';

/**
 * The BrowseNodeOccurrence model module.
 * @module customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeOccurrence
 * @version 2024-06-01
 */
export class BrowseNodeOccurrence {
  /**
   * Constructs a new <code>BrowseNodeOccurrence</code>.
   * The browse node review trend occurrence metrics.
   * @alias module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeOccurrence
   * @class
   * @param allProducts {Number} The percentage of reviews of products in the browse node that mention a topic.
   */
  constructor(allProducts) {
    this.allProducts = allProducts;
  }

  /**
   * Constructs a <code>BrowseNodeOccurrence</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeOccurrence} obj Optional instance to populate.
   * @return {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeOccurrence} The populated <code>BrowseNodeOccurrence</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      switch(typeof data) {
        case 'string':
          obj = String(data);
          break;
        case 'number':
          obj = Number(data);
          break;
        case 'boolean':
          obj = Boolean(data);
          break;
      }
      obj = obj || new BrowseNodeOccurrence();
      if (data.hasOwnProperty('allProducts'))
        obj.allProducts = ApiClient.convertToType(data['allProducts'], 'Number');
    }
    return obj;
  }
}

/**
 * The percentage of reviews of products in the browse node that mention a topic.
 * @member {Number} allProducts
 */
BrowseNodeOccurrence.prototype.allProducts = undefined;


