/*
 * The Selling Partner API for CustomerFeedback
 * The Selling Partner API for Customer Feedback (Customer Feedback API) provides information about customer reviews and returns at both the item and browse node level.
 *
 * OpenAPI spec version: 2024-06-01
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';

/**
 * The BrowseNodeResponse model module.
 * @module customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeResponse
 * @version 2024-06-01
 */
export class BrowseNodeResponse {
  /**
   * Constructs a new <code>BrowseNodeResponse</code>.
   * The response for the `getItemBrowseNode` operation.
   * @alias module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeResponse
   * @class
   * @param browseNodeId {String} A browse node id is the unique identifier of a given browse node. A browse node is a location in a browse tree that is used for navigation, product classification, and website content.
   * @param displayName {String} The display name of the browse node as visible on the Amazon retail website.
   */
  constructor(browseNodeId, displayName) {
    this.browseNodeId = browseNodeId;
    this.displayName = displayName;
  }

  /**
   * Constructs a <code>BrowseNodeResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeResponse} obj Optional instance to populate.
   * @return {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeResponse} The populated <code>BrowseNodeResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      switch(typeof data) {
        case 'string':
          obj = String(data);
          break;
        case 'number':
          obj = Number(data);
          break;
        case 'boolean':
          obj = Boolean(data);
          break;
      }
      obj = obj || new BrowseNodeResponse();
      if (data.hasOwnProperty('browseNodeId'))
        obj.browseNodeId = ApiClient.convertToType(data['browseNodeId'], 'String');
      if (data.hasOwnProperty('displayName'))
        obj.displayName = ApiClient.convertToType(data['displayName'], 'String');
    }
    return obj;
  }
}

/**
 * A browse node id is the unique identifier of a given browse node. A browse node is a location in a browse tree that is used for navigation, product classification, and website content.
 * @member {String} browseNodeId
 */
BrowseNodeResponse.prototype.browseNodeId = undefined;

/**
 * The display name of the browse node as visible on the Amazon retail website.
 * @member {String} displayName
 */
BrowseNodeResponse.prototype.displayName = undefined;


