/*
 * The Selling Partner API for CustomerFeedback
 * The Selling Partner API for Customer Feedback (Customer Feedback API) provides information about customer reviews and returns at both the item and browse node level.
 *
 * OpenAPI spec version: 2024-06-01
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';
import {BrowseNodeReturnTrendPoint} from './BrowseNodeReturnTrendPoint.js';

/**
 * The BrowseNodeReturnTrend model module.
 * @module customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeReturnTrend
 * @version 2024-06-01
 */
export class BrowseNodeReturnTrend {
  /**
   * Constructs a new <code>BrowseNodeReturnTrend</code>.
   * The trend of return topic metrics for all items in the requested browse node.
   * @alias module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeReturnTrend
   * @class
   * @param topic {String} The name of the topic.
   * @param trendMetrics {Array.<module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeReturnTrendPoint>} The browse node return trend metrics.
   */
  constructor(topic, trendMetrics) {
    this.topic = topic;
    this.trendMetrics = trendMetrics;
  }

  /**
   * Constructs a <code>BrowseNodeReturnTrend</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeReturnTrend} obj Optional instance to populate.
   * @return {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeReturnTrend} The populated <code>BrowseNodeReturnTrend</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      switch(typeof data) {
        case 'string':
          obj = String(data);
          break;
        case 'number':
          obj = Number(data);
          break;
        case 'boolean':
          obj = Boolean(data);
          break;
      }
      obj = obj || new BrowseNodeReturnTrend();
      if (data.hasOwnProperty('topic'))
        obj.topic = ApiClient.convertToType(data['topic'], 'String');
      if (data.hasOwnProperty('trendMetrics'))
        obj.trendMetrics = ApiClient.convertToType(data['trendMetrics'], [BrowseNodeReturnTrendPoint]);
    }
    return obj;
  }
}

/**
 * The name of the topic.
 * @member {String} topic
 */
BrowseNodeReturnTrend.prototype.topic = undefined;

/**
 * The browse node return trend metrics.
 * @member {Array.<module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeReturnTrendPoint>} trendMetrics
 */
BrowseNodeReturnTrend.prototype.trendMetrics = undefined;


