/*
 * The Selling Partner API for CustomerFeedback
 * The Selling Partner API for Customer Feedback (Customer Feedback API) provides information about customer reviews and returns at both the item and browse node level.
 *
 * OpenAPI spec version: 2024-06-01
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';
import {ChildAsinMentionMetrics} from './ChildAsinMentionMetrics.js';

/**
 * The ChildAsinMetrics model module.
 * @module customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/ChildAsinMetrics
 * @version 2024-06-01
 */
export class ChildAsinMetrics {
  /**
   * Constructs a new <code>ChildAsinMetrics</code>.
   * The review topic metrics for other child ASINs that have the same parent ASIN. This value is `null` if there isn't any child ASIN metric data.
   * @alias module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/ChildAsinMetrics
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ChildAsinMetrics</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/ChildAsinMetrics} obj Optional instance to populate.
   * @return {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/ChildAsinMetrics} The populated <code>ChildAsinMetrics</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      switch(typeof data) {
        case 'string':
          obj = String(data);
          break;
        case 'number':
          obj = Number(data);
          break;
        case 'boolean':
          obj = Boolean(data);
          break;
      }
      obj = obj || new ChildAsinMetrics();
      if (data.hasOwnProperty('mostMentions'))
        obj.mostMentions = ChildAsinMentionMetrics.constructFromObject(data['mostMentions']);
      if (data.hasOwnProperty('leastMentions'))
        obj.leastMentions = ChildAsinMentionMetrics.constructFromObject(data['leastMentions']);
    }
    return obj;
  }
}

/**
 * The child ASIN for which reviews mention the topic the greatest number of times, and the number of times reviews mention the topic. This value is `null` if there are no child ASIN metrics.
 * @member {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/ChildAsinMentionMetrics} mostMentions
 */
ChildAsinMetrics.prototype.mostMentions = undefined;

/**
 * The child ASIN for which reviews mention the topic the least number of times, and the number of times reviews mention the topic. This value is `null` if there are no child ASIN metrics.
 * @member {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/ChildAsinMentionMetrics} leastMentions
 */
ChildAsinMetrics.prototype.leastMentions = undefined;


