/*
 * The Selling Partner API for CustomerFeedback
 * The Selling Partner API for Customer Feedback (Customer Feedback API) provides information about customer reviews and returns at both the item and browse node level.
 *
 * OpenAPI spec version: 2024-06-01
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';

/**
 * The DateRange model module.
 * @module customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/DateRange
 * @version 2024-06-01
 */
export class DateRange {
  /**
   * Constructs a new <code>DateRange</code>.
   * A date range.
   * @alias module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/DateRange
   * @class
   * @param startDate {Date} The start date of the date range in ISO-8601 date/time format.
   * @param endDate {Date} The end date of the date range in ISO-8601 date/time format.
   */
  constructor(startDate, endDate) {
    this.startDate = startDate;
    this.endDate = endDate;
  }

  /**
   * Constructs a <code>DateRange</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/DateRange} obj Optional instance to populate.
   * @return {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/DateRange} The populated <code>DateRange</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      switch(typeof data) {
        case 'string':
          obj = String(data);
          break;
        case 'number':
          obj = Number(data);
          break;
        case 'boolean':
          obj = Boolean(data);
          break;
      }
      obj = obj || new DateRange();
      if (data.hasOwnProperty('startDate'))
        obj.startDate = ApiClient.convertToType(data['startDate'], 'Date');
      if (data.hasOwnProperty('endDate'))
        obj.endDate = ApiClient.convertToType(data['endDate'], 'Date');
    }
    return obj;
  }
}

/**
 * The start date of the date range in ISO-8601 date/time format.
 * @member {Date} startDate
 */
DateRange.prototype.startDate = undefined;

/**
 * The end date of the date range in ISO-8601 date/time format.
 * @member {Date} endDate
 */
DateRange.prototype.endDate = undefined;


