/*
 * The Selling Partner API for CustomerFeedback
 * The Selling Partner API for Customer Feedback (Customer Feedback API) provides information about customer reviews and returns at both the item and browse node level.
 *
 * OpenAPI spec version: 2024-06-01
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';
import {ItemReviewTrend} from './ItemReviewTrend.js';

/**
 * The ItemReviewTrends model module.
 * @module customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/ItemReviewTrends
 * @version 2024-06-01
 */
export class ItemReviewTrends {
  /**
   * Constructs a new <code>ItemReviewTrends</code>.
   * The 10 most positive and most negative review topics for all items in a browse node.
   * @alias module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/ItemReviewTrends
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ItemReviewTrends</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/ItemReviewTrends} obj Optional instance to populate.
   * @return {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/ItemReviewTrends} The populated <code>ItemReviewTrends</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      switch(typeof data) {
        case 'string':
          obj = String(data);
          break;
        case 'number':
          obj = Number(data);
          break;
        case 'boolean':
          obj = Boolean(data);
          break;
      }
      obj = obj || new ItemReviewTrends();
      if (data.hasOwnProperty('positiveTopics'))
        obj.positiveTopics = ApiClient.convertToType(data['positiveTopics'], [ItemReviewTrend]);
      if (data.hasOwnProperty('negativeTopics'))
        obj.negativeTopics = ApiClient.convertToType(data['negativeTopics'], [ItemReviewTrend]);
    }
    return obj;
  }
}

/**
 * A list of the most positive review topics. The percentage of reviews that contain the topic determines the topic's placement in the list. This value is `null` if there are not enough positive reviews for the specified ASIN.  **Max length:** 10
 * @member {Array.<module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/ItemReviewTrend>} positiveTopics
 */
ItemReviewTrends.prototype.positiveTopics = undefined;

/**
 * A list of the most negative review topics. The percentage of reviews that contain the topic determines the topic's placement in the list. This value is `null` if there are not enough negative reviews for the specified ASIN.  **Max length:** 10
 * @member {Array.<module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/ItemReviewTrend>} negativeTopics
 */
ItemReviewTrends.prototype.negativeTopics = undefined;


