/*
 * The Selling Partner API for CustomerFeedback
 * The Selling Partner API for Customer Feedback (Customer Feedback API) provides information about customer reviews and returns at both the item and browse node level.
 *
 * OpenAPI spec version: 2024-06-01
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';
import {ItemReviewTrendPoint} from './ItemReviewTrendPoint.js';

/**
 * The ItemReviewTrend model module.
 * @module customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/ItemReviewTrend
 * @version 2024-06-01
 */
export class ItemReviewTrend {
  /**
   * Constructs a new <code>ItemReviewTrend</code>.
   * The trend of review topic metrics for the requested item.
   * @alias module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/ItemReviewTrend
   * @class
   * @param topic {String} The name of the item review topic.
   * @param trendMetrics {Array.<module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/ItemReviewTrendPoint>} The item's review trend metrics for the past six months.
   */
  constructor(topic, trendMetrics) {
    this.topic = topic;
    this.trendMetrics = trendMetrics;
  }

  /**
   * Constructs a <code>ItemReviewTrend</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/ItemReviewTrend} obj Optional instance to populate.
   * @return {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/ItemReviewTrend} The populated <code>ItemReviewTrend</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      switch(typeof data) {
        case 'string':
          obj = String(data);
          break;
        case 'number':
          obj = Number(data);
          break;
        case 'boolean':
          obj = Boolean(data);
          break;
      }
      obj = obj || new ItemReviewTrend();
      if (data.hasOwnProperty('topic'))
        obj.topic = ApiClient.convertToType(data['topic'], 'String');
      if (data.hasOwnProperty('trendMetrics'))
        obj.trendMetrics = ApiClient.convertToType(data['trendMetrics'], [ItemReviewTrendPoint]);
    }
    return obj;
  }
}

/**
 * The name of the item review topic.
 * @member {String} topic
 */
ItemReviewTrend.prototype.topic = undefined;

/**
 * The item's review trend metrics for the past six months.
 * @member {Array.<module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/ItemReviewTrendPoint>} trendMetrics
 */
ItemReviewTrend.prototype.trendMetrics = undefined;


