/*
 * The Selling Partner API for CustomerFeedback
 * The Selling Partner API for Customer Feedback (Customer Feedback API) provides information about customer reviews and returns at both the item and browse node level.
 *
 * OpenAPI spec version: 2024-06-01
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';
import {BrowseNodeOccurrence} from './BrowseNodeOccurrence.js';
import {BrowseNodeStarRatingImpact} from './BrowseNodeStarRatingImpact.js';

/**
 * The ItemReviewBrowseNodeMetrics model module.
 * @module customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/ItemReviewBrowseNodeMetrics
 * @version 2024-06-01
 */
export class ItemReviewBrowseNodeMetrics {
  /**
   * Constructs a new <code>ItemReviewBrowseNodeMetrics</code>.
   * The browse node review topic metrics.
   * @alias module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/ItemReviewBrowseNodeMetrics
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ItemReviewBrowseNodeMetrics</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/ItemReviewBrowseNodeMetrics} obj Optional instance to populate.
   * @return {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/ItemReviewBrowseNodeMetrics} The populated <code>ItemReviewBrowseNodeMetrics</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      switch(typeof data) {
        case 'string':
          obj = String(data);
          break;
        case 'number':
          obj = Number(data);
          break;
        case 'boolean':
          obj = Boolean(data);
          break;
      }
      obj = obj || new ItemReviewBrowseNodeMetrics();
      if (data.hasOwnProperty('occurrencePercentage'))
        obj.occurrencePercentage = BrowseNodeOccurrence.constructFromObject(data['occurrencePercentage']);
      if (data.hasOwnProperty('starRatingImpact'))
        obj.starRatingImpact = BrowseNodeStarRatingImpact.constructFromObject(data['starRatingImpact']);
    }
    return obj;
  }
}

/**
 * The percentage of reviews that mention the topic. This value is `null` if reviews do not mention the topic frequently enough.
 * @member {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeOccurrence} occurrencePercentage
 */
ItemReviewBrowseNodeMetrics.prototype.occurrencePercentage = undefined;

/**
 * The effect of the topic on the star rating of items in the browse node. This value is `null` if the topic does not affect the star rating of the browse node.
 * @member {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeStarRatingImpact} starRatingImpact
 */
ItemReviewBrowseNodeMetrics.prototype.starRatingImpact = undefined;


