/*
 * The Selling Partner API for CustomerFeedback
 * The Selling Partner API for Customer Feedback (Customer Feedback API) provides information about customer reviews and returns at both the item and browse node level.
 *
 * OpenAPI spec version: 2024-06-01
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';

/**
 * The ItemReviewTopicMetrics model module.
 * @module customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/ItemReviewTopicMetrics
 * @version 2024-06-01
 */
export class ItemReviewTopicMetrics {
  /**
   * Constructs a new <code>ItemReviewTopicMetrics</code>.
   * The item review topic metrics.
   * @alias module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/ItemReviewTopicMetrics
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ItemReviewTopicMetrics</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/ItemReviewTopicMetrics} obj Optional instance to populate.
   * @return {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/ItemReviewTopicMetrics} The populated <code>ItemReviewTopicMetrics</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      switch(typeof data) {
        case 'string':
          obj = String(data);
          break;
        case 'number':
          obj = Number(data);
          break;
        case 'boolean':
          obj = Boolean(data);
          break;
      }
      obj = obj || new ItemReviewTopicMetrics();
      if (data.hasOwnProperty('numberOfMentions'))
        obj.numberOfMentions = ApiClient.convertToType(data['numberOfMentions'], 'Number');
      if (data.hasOwnProperty('occurrencePercentage'))
        obj.occurrencePercentage = ApiClient.convertToType(data['occurrencePercentage'], 'Number');
      if (data.hasOwnProperty('starRatingImpact'))
        obj.starRatingImpact = ApiClient.convertToType(data['starRatingImpact'], 'Number');
    }
    return obj;
  }
}

/**
 * The number of times that reviews mention the topic. This value is `null` if reviews do not mention the topic frequently enough.
 * @member {Number} numberOfMentions
 */
ItemReviewTopicMetrics.prototype.numberOfMentions = undefined;

/**
 * The percentage of customer reviews that mention the topic. This value is `null` if reviews do not mention the topic frequently enough.
 * @member {Number} occurrencePercentage
 */
ItemReviewTopicMetrics.prototype.occurrencePercentage = undefined;

/**
 * The effect of the topic on the star rating of the ASIN. This value can be positive or negative. This value is `null` if the topic does't affect the star rating of the ASIN.
 * @member {Number} starRatingImpact
 */
ItemReviewTopicMetrics.prototype.starRatingImpact = undefined;


