/*
 * The Selling Partner API for CustomerFeedback
 * The Selling Partner API for Customer Feedback (Customer Feedback API) provides information about customer reviews and returns at both the item and browse node level.
 *
 * OpenAPI spec version: 2024-06-01
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';
import {BrowseNodeTrendMetrics} from './BrowseNodeTrendMetrics.js';
import {DateRange} from './DateRange.js';
import {ReviewTrendMetrics} from './ReviewTrendMetrics.js';

/**
 * The ItemReviewTrendPoint model module.
 * @module customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/ItemReviewTrendPoint
 * @version 2024-06-01
 */
export class ItemReviewTrendPoint {
  /**
   * Constructs a new <code>ItemReviewTrendPoint</code>.
   * The review metrics for a certain month.
   * @alias module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/ItemReviewTrendPoint
   * @class
   * @param dateRange {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/DateRange} The date range of the item review trend metric.
   * @param asinMetrics {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/ReviewTrendMetrics} The ASIN's review trend metrics.
   */
  constructor(dateRange, asinMetrics) {
    this.dateRange = dateRange;
    this.asinMetrics = asinMetrics;
  }

  /**
   * Constructs a <code>ItemReviewTrendPoint</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/ItemReviewTrendPoint} obj Optional instance to populate.
   * @return {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/ItemReviewTrendPoint} The populated <code>ItemReviewTrendPoint</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      switch(typeof data) {
        case 'string':
          obj = String(data);
          break;
        case 'number':
          obj = Number(data);
          break;
        case 'boolean':
          obj = Boolean(data);
          break;
      }
      obj = obj || new ItemReviewTrendPoint();
      if (data.hasOwnProperty('dateRange'))
        obj.dateRange = DateRange.constructFromObject(data['dateRange']);
      if (data.hasOwnProperty('asinMetrics'))
        obj.asinMetrics = ReviewTrendMetrics.constructFromObject(data['asinMetrics']);
      if (data.hasOwnProperty('parentAsinMetrics'))
        obj.parentAsinMetrics = ReviewTrendMetrics.constructFromObject(data['parentAsinMetrics']);
      if (data.hasOwnProperty('browseNodeMetrics'))
        obj.browseNodeMetrics = BrowseNodeTrendMetrics.constructFromObject(data['browseNodeMetrics']);
    }
    return obj;
  }
}

/**
 * The date range of the item review trend metric.
 * @member {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/DateRange} dateRange
 */
ItemReviewTrendPoint.prototype.dateRange = undefined;

/**
 * The ASIN's review trend metrics.
 * @member {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/ReviewTrendMetrics} asinMetrics
 */
ItemReviewTrendPoint.prototype.asinMetrics = undefined;

/**
 * The parent ASIN's review trend metrics. This value is `null` if there isn't enough topic data for the parent ASIN.
 * @member {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/ReviewTrendMetrics} parentAsinMetrics
 */
ItemReviewTrendPoint.prototype.parentAsinMetrics = undefined;

/**
 * The browse node's review trend metrics. This value is `null` if there isn't enough topic data for the browse node.
 * @member {module:customerFeedback_2024-06-01/js-client.customerFeedback_2024-06-01.model/BrowseNodeTrendMetrics} browseNodeMetrics
 */
ItemReviewTrendPoint.prototype.browseNodeMetrics = undefined;


