/*
 * The Selling Partner API for Finances
 * The Selling Partner API for Finances helps you obtain financial information relevant to a seller's business. You can obtain financial events for a given order or date range without having to wait until a statement period closes.
 *
 * OpenAPI spec version: 2024-06-19
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';
import {Breakdown} from './Breakdown.js';
import {Contexts} from './Contexts.js';
import {Currency} from './Currency.js';
import {ItemRelatedIdentifiers} from './ItemRelatedIdentifiers.js';

/**
 * The Item model module.
 * @module finances_2024-06-19/js-client.finances_2024-06-19.model/Item
 * @version 2024-06-19
 */
export class Item {
  /**
   * Constructs a new <code>Item</code>.
   * Additional information about the items in Transaction.
   * @alias module:finances_2024-06-19/js-client.finances_2024-06-19.model/Item
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Item</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:finances_2024-06-19/js-client.finances_2024-06-19.model/Item} obj Optional instance to populate.
   * @return {module:finances_2024-06-19/js-client.finances_2024-06-19.model/Item} The populated <code>Item</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      switch(typeof data) {
        case 'string':
          obj = String(data);
          break;
        case 'number':
          obj = Number(data);
          break;
        case 'boolean':
          obj = Boolean(data);
          break;
      }
      obj = obj || new Item();
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('relatedIdentifiers'))
        obj.relatedIdentifiers = ItemRelatedIdentifiers.constructFromObject(data['relatedIdentifiers']);
      if (data.hasOwnProperty('totalAmount'))
        obj.totalAmount = Currency.constructFromObject(data['totalAmount']);
      if (data.hasOwnProperty('breakdowns'))
        obj.breakdowns = ApiClient.convertToType(data['breakdowns'], [Breakdown]);
      if (data.hasOwnProperty('contexts'))
        obj.contexts = Contexts.constructFromObject(data['contexts']);
    }
    return obj;
  }
}

/**
 * Description of items in the transaction
 * @member {String} description
 */
Item.prototype.description = undefined;

/**
 * Related business identifiers of the item.
 * @member {module:finances_2024-06-19/js-client.finances_2024-06-19.model/ItemRelatedIdentifiers} relatedIdentifiers
 */
Item.prototype.relatedIdentifiers = undefined;

/**
 * The total amount of the item.
 * @member {module:finances_2024-06-19/js-client.finances_2024-06-19.model/Currency} totalAmount
 */
Item.prototype.totalAmount = undefined;

/**
 * A list of breakdowns that detail how the total amount is calculated for the transaction.
 * @member {Array.<module:finances_2024-06-19/js-client.finances_2024-06-19.model/Breakdown>} breakdowns
 */
Item.prototype.breakdowns = undefined;

/**
 * Additional Information about the item.
 * @member {module:finances_2024-06-19/js-client.finances_2024-06-19.model/Contexts} contexts
 */
Item.prototype.contexts = undefined;


