/*
 * Selling Partner API for Catalog Items
 * The Selling Partner API for Catalog Items helps you programmatically retrieve item details for items in the catalog.
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from "../ApiClient.js";
import {ListCatalogCategoriesResponse} from '../js-client.catalogItemsV0.model/ListCatalogCategoriesResponse.js';

/**
* Catalog service.
* @module catalogItemsV0/js-client.catalogItemsV0.api/CatalogApi
* @version v0
*/
export class CatalogApi {

    /**
    * Constructs a new CatalogApi. 
    * @alias module:catalogItemsV0/js-client.catalogItemsV0.api/CatalogApi
    * @class
    * @param {module:catalogItemsV0/ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:catalogItemsV0/ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Returns the parent categories to which an item belongs, based on the specified ASIN or SellerSKU.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 2 |  The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](doc:usage-plans-and-rate-limits-in-the-sp-api).
     * @param {String} marketplaceId A marketplace identifier. Specifies the marketplace for the item.
     * @param {Object} opts Optional parameters
     * @param {String} opts.ASIN The Amazon Standard Identification Number (ASIN) of the item.
     * @param {String} opts.sellerSKU Used to identify items in the given marketplace. SellerSKU is qualified by the seller's SellerId, which is included with every operation that you submit.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:catalogItemsV0/js-client.catalogItemsV0.model/ListCatalogCategoriesResponse} and HTTP response
     */
    listCatalogCategoriesWithHttpInfo(marketplaceId, opts) {
      opts = opts || {};
      let postBody = null;

      // verify the required parameter 'marketplaceId' is set
      if (marketplaceId === undefined || marketplaceId === null) {
        throw new Error("Missing the required parameter 'marketplaceId' when calling listCatalogCategories");
      }


      let pathParams = {
      };
      let queryParams = {
        'MarketplaceId': marketplaceId,
        'ASIN': opts['ASIN'],
        'SellerSKU': opts['sellerSKU']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = ListCatalogCategoriesResponse;

      return this.apiClient.callApi(
        '/catalog/v0/categories', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        contentTypes, accepts, returnType
      );
    }

    /**
     * Returns the parent categories to which an item belongs, based on the specified ASIN or SellerSKU.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 2 |  The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](doc:usage-plans-and-rate-limits-in-the-sp-api).
     * @param {String} marketplaceId A marketplace identifier. Specifies the marketplace for the item.
     * @param {Object} opts Optional parameters
     * @param {String} opts.ASIN The Amazon Standard Identification Number (ASIN) of the item.
     * @param {String} opts.sellerSKU Used to identify items in the given marketplace. SellerSKU is qualified by the seller's SellerId, which is included with every operation that you submit.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:catalogItemsV0/js-client.catalogItemsV0.model/ListCatalogCategoriesResponse}
     */
    listCatalogCategories(marketplaceId, opts) {
      return this.listCatalogCategoriesWithHttpInfo(marketplaceId, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
