/*
 * Selling Partner APIs for Fulfillment Outbound
 * The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.
 *
 * OpenAPI spec version: 2020-07-01
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';
import {Decimal} from './Decimal.js';

/**
 * The DeliveryQuantity model module.
 * @module fulfillmentOutbound_2020-07-01/js-client.fulfillmentOutbound_2020-07-01.model/DeliveryQuantity
 * @version 2020-07-01
 */
export class DeliveryQuantity {
  /**
   * Constructs a new <code>DeliveryQuantity</code>.
   * A quantity based on unit of measure.
   * @alias module:fulfillmentOutbound_2020-07-01/js-client.fulfillmentOutbound_2020-07-01.model/DeliveryQuantity
   * @class
   * @param unitOfMeasure {module:fulfillmentOutbound_2020-07-01/js-client.fulfillmentOutbound_2020-07-01.model/DeliveryQuantity.UnitOfMeasureEnum} The unit of measure for the amount.
   * @param amount {module:fulfillmentOutbound_2020-07-01/js-client.fulfillmentOutbound_2020-07-01.model/Decimal} The amount of a product in the associated unit of measure.
   */
  constructor(unitOfMeasure, amount) {
    this.unitOfMeasure = unitOfMeasure;
    this.amount = amount;
  }

  /**
   * Constructs a <code>DeliveryQuantity</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:fulfillmentOutbound_2020-07-01/js-client.fulfillmentOutbound_2020-07-01.model/DeliveryQuantity} obj Optional instance to populate.
   * @return {module:fulfillmentOutbound_2020-07-01/js-client.fulfillmentOutbound_2020-07-01.model/DeliveryQuantity} The populated <code>DeliveryQuantity</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      switch(typeof data) {
        case 'string':
          obj = String(data);
          break;
        case 'number':
          obj = Number(data);
          break;
        case 'boolean':
          obj = Boolean(data);
          break;
      }
      obj = obj || new DeliveryQuantity();
      if (data.hasOwnProperty('unitOfMeasure'))
        obj.unitOfMeasure = ApiClient.convertToType(data['unitOfMeasure'], 'String');
      if (data.hasOwnProperty('amount'))
        obj.amount = Decimal.constructFromObject(data['amount']);
    }
    return obj;
  }
}

/**
 * Allowed values for the <code>unitOfMeasure</code> property.
 * @enum {String}
 * @readonly
 */
DeliveryQuantity.UnitOfMeasureEnum = {
  /**
   * value: "Each"
   * @const
   */
  each: "Each"
};

/**
 * The unit of measure for the amount.
 * @member {module:fulfillmentOutbound_2020-07-01/js-client.fulfillmentOutbound_2020-07-01.model/DeliveryQuantity.UnitOfMeasureEnum} unitOfMeasure
 */
DeliveryQuantity.prototype.unitOfMeasure = undefined;

/**
 * The amount of a product in the associated unit of measure.
 * @member {module:fulfillmentOutbound_2020-07-01/js-client.fulfillmentOutbound_2020-07-01.model/Decimal} amount
 */
DeliveryQuantity.prototype.amount = undefined;


