/*
 * Selling Partner APIs for Fulfillment Outbound
 * The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.
 *
 * OpenAPI spec version: 2020-07-01
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';
import {DeliveryQuantity} from './DeliveryQuantity.js';
import {VariablePrecisionAddress} from './VariablePrecisionAddress.js';

/**
 * The GetDeliveryOfferingsRequest model module.
 * @module fulfillmentOutbound_2020-07-01/js-client.fulfillmentOutbound_2020-07-01.model/GetDeliveryOfferingsRequest
 * @version 2020-07-01
 */
export class GetDeliveryOfferingsRequest {
  /**
   * Constructs a new <code>GetDeliveryOfferingsRequest</code>.
   * The request body schema for the `getDeliveryOfferings` operation.
   * @alias module:fulfillmentOutbound_2020-07-01/js-client.fulfillmentOutbound_2020-07-01.model/GetDeliveryOfferingsRequest
   * @class
   * @param destinationAddress {module:fulfillmentOutbound_2020-07-01/js-client.fulfillmentOutbound_2020-07-01.model/VariablePrecisionAddress} The address for the delivery offering.
   * @param shipFromCountryCode {String} The two digit country code the items should ship from. In ISO 3166-1 alpha-2 format.
   * @param sellerSku {String} The seller SKU of the item.
   */
  constructor(destinationAddress, shipFromCountryCode, sellerSku) {
    this.destinationAddress = destinationAddress;
    this.shipFromCountryCode = shipFromCountryCode;
    this.sellerSku = sellerSku;
  }

  /**
   * Constructs a <code>GetDeliveryOfferingsRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:fulfillmentOutbound_2020-07-01/js-client.fulfillmentOutbound_2020-07-01.model/GetDeliveryOfferingsRequest} obj Optional instance to populate.
   * @return {module:fulfillmentOutbound_2020-07-01/js-client.fulfillmentOutbound_2020-07-01.model/GetDeliveryOfferingsRequest} The populated <code>GetDeliveryOfferingsRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      switch(typeof data) {
        case 'string':
          obj = String(data);
          break;
        case 'number':
          obj = Number(data);
          break;
        case 'boolean':
          obj = Boolean(data);
          break;
      }
      obj = obj || new GetDeliveryOfferingsRequest();
      if (data.hasOwnProperty('destinationAddress'))
        obj.destinationAddress = VariablePrecisionAddress.constructFromObject(data['destinationAddress']);
      if (data.hasOwnProperty('shipFromCountryCode'))
        obj.shipFromCountryCode = ApiClient.convertToType(data['shipFromCountryCode'], 'String');
      if (data.hasOwnProperty('sellerSku'))
        obj.sellerSku = ApiClient.convertToType(data['sellerSku'], 'String');
      if (data.hasOwnProperty('quantity'))
        obj.quantity = DeliveryQuantity.constructFromObject(data['quantity']);
    }
    return obj;
  }
}

/**
 * The address for the delivery offering.
 * @member {module:fulfillmentOutbound_2020-07-01/js-client.fulfillmentOutbound_2020-07-01.model/VariablePrecisionAddress} destinationAddress
 */
GetDeliveryOfferingsRequest.prototype.destinationAddress = undefined;

/**
 * The two digit country code the items should ship from. In ISO 3166-1 alpha-2 format.
 * @member {String} shipFromCountryCode
 */
GetDeliveryOfferingsRequest.prototype.shipFromCountryCode = undefined;

/**
 * The seller SKU of the item.
 * @member {String} sellerSku
 */
GetDeliveryOfferingsRequest.prototype.sellerSku = undefined;

/**
 * The quantity of the request SKU.
 * @member {module:fulfillmentOutbound_2020-07-01/js-client.fulfillmentOutbound_2020-07-01.model/DeliveryQuantity} quantity
 */
GetDeliveryOfferingsRequest.prototype.quantity = undefined;


