/*
 * The Selling Partner API for Amazon Warehousing and Distribution
 * The Selling Partner API for Amazon Warehousing and Distribution (AWD) provides programmatic access to information about AWD shipments and inventory.
 *
 * OpenAPI spec version: 2024-05-09
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';

/**
 * Enum class InboundEligibilityStatus.
 * @enum {String}
 * @readonly
 */
const InboundEligibilityStatus = {
  /**
   * value: "ELIGIBLE"
   * @const
   */
  ELIGIBLE: "ELIGIBLE",

  /**
   * value: "INELIGIBLE"
   * @const
   */
  INELIGIBLE: "INELIGIBLE",

  /**
   * Returns a <code>InboundEligibilityStatus</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
   * @return {module:awd_2024-05-09/js-client.awd_2024-05-09.model/InboundEligibilityStatus} The enum <code>InboundEligibilityStatus</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {InboundEligibilityStatus};
