/*
 * The Selling Partner API for Amazon Warehousing and Distribution
 * The Selling Partner API for Amazon Warehousing and Distribution (AWD) provides programmatic access to information about AWD shipments and inventory.
 *
 * OpenAPI spec version: 2024-05-09
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';

/**
 * Enum class InboundStatus.
 * @enum {String}
 * @readonly
 */
const InboundStatus = {
  /**
   * value: "DRAFT"
   * @const
   */
  DRAFT: "DRAFT",

  /**
   * value: "VALIDATING"
   * @const
   */
  VALIDATING: "VALIDATING",

  /**
   * value: "CONFIRMED"
   * @const
   */
  CONFIRMED: "CONFIRMED",

  /**
   * value: "CLOSED"
   * @const
   */
  CLOSED: "CLOSED",

  /**
   * value: "EXPIRED"
   * @const
   */
  EXPIRED: "EXPIRED",

  /**
   * value: "CANCELLED"
   * @const
   */
  CANCELLED: "CANCELLED",

  /**
   * Returns a <code>InboundStatus</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
   * @return {module:awd_2024-05-09/js-client.awd_2024-05-09.model/InboundStatus} The enum <code>InboundStatus</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {InboundStatus};
