/*
 * The Selling Partner API for Amazon Warehousing and Distribution
 * The Selling Partner API for Amazon Warehousing and Distribution (AWD) provides programmatic access to information about AWD shipments and inventory.
 *
 * OpenAPI spec version: 2024-05-09
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';

/**
 * Enum class PrepCategory.
 * @enum {String}
 * @readonly
 */
const PrepCategory = {
  /**
   * value: "ADULT"
   * @const
   */
  ADULT: "ADULT",

  /**
   * value: "BABY"
   * @const
   */
  BABY: "BABY",

  /**
   * value: "FC_PROVIDED"
   * @const
   */
  FC_PROVIDED: "FC_PROVIDED",

  /**
   * value: "FRAGILE"
   * @const
   */
  FRAGILE: "FRAGILE",

  /**
   * value: "GRANULAR"
   * @const
   */
  GRANULAR: "GRANULAR",

  /**
   * value: "HANGER"
   * @const
   */
  HANGER: "HANGER",

  /**
   * value: "LIQUID"
   * @const
   */
  LIQUID: "LIQUID",

  /**
   * value: "PERFORATED"
   * @const
   */
  PERFORATED: "PERFORATED",

  /**
   * value: "SET"
   * @const
   */
  SET: "SET",

  /**
   * value: "SHARP"
   * @const
   */
  SHARP: "SHARP",

  /**
   * value: "SMALL"
   * @const
   */
  SMALL: "SMALL",

  /**
   * value: "TEXTILE"
   * @const
   */
  TEXTILE: "TEXTILE",

  /**
   * value: "NO_PREP"
   * @const
   */
  NO_PREP: "NO_PREP",

  /**
   * value: "UNKNOWN"
   * @const
   */
  UNKNOWN: "UNKNOWN",

  /**
   * Returns a <code>PrepCategory</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
   * @return {module:awd_2024-05-09/js-client.awd_2024-05-09.model/PrepCategory} The enum <code>PrepCategory</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {PrepCategory};
