/*
 * The Selling Partner API for Amazon Warehousing and Distribution
 * The Selling Partner API for Amazon Warehousing and Distribution (AWD) provides programmatic access to information about AWD shipments and inventory.
 *
 * OpenAPI spec version: 2024-05-09
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';
import {CarrierCode} from './CarrierCode.js';

/**
 * The TrackingDetails model module.
 * @module awd_2024-05-09/js-client.awd_2024-05-09.model/TrackingDetails
 * @version 2024-05-09
 */
export class TrackingDetails {
  /**
   * Constructs a new <code>TrackingDetails</code>.
   * Tracking details for the shipment. If using SPD transportation, this can be for each case. If not using SPD transportation, this is a single tracking entry for the entire shipment.
   * @alias module:awd_2024-05-09/js-client.awd_2024-05-09.model/TrackingDetails
   * @class
   * @param bookingId {String} The identifier that is received from transportation to uniquely identify a booking.
   */
  constructor(bookingId) {
    this.bookingId = bookingId;
  }

  /**
   * Constructs a <code>TrackingDetails</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:awd_2024-05-09/js-client.awd_2024-05-09.model/TrackingDetails} obj Optional instance to populate.
   * @return {module:awd_2024-05-09/js-client.awd_2024-05-09.model/TrackingDetails} The populated <code>TrackingDetails</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      switch(typeof data) {
        case 'string':
          obj = String(data);
          break;
        case 'number':
          obj = Number(data);
          break;
        case 'boolean':
          obj = Boolean(data);
          break;
      }
      obj = obj || new TrackingDetails();
      if (data.hasOwnProperty('carrierCode'))
        obj.carrierCode = CarrierCode.constructFromObject(data['carrierCode']);
      if (data.hasOwnProperty('bookingId'))
        obj.bookingId = ApiClient.convertToType(data['bookingId'], 'String');
    }
    return obj;
  }
}

/**
 * Unique or identifying code for the carrier.
 * @member {module:awd_2024-05-09/js-client.awd_2024-05-09.model/CarrierCode} carrierCode
 */
TrackingDetails.prototype.carrierCode = undefined;

/**
 * The identifier that is received from transportation to uniquely identify a booking.
 * @member {String} bookingId
 */
TrackingDetails.prototype.bookingId = undefined;


