'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'vi';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

type TranslationMap = {
    [key: string]: string;
};

const translations: Record<Language, TranslationMap> = {
  en: {
      // Navigation
      'nav.products': 'Products',
      'nav.orders': 'Orders',
      'nav.bank': 'Bank Management',
      'nav.revenue': 'Revenue',
      'nav.connect_shop': 'Connect Shop',
      'nav.chat': 'Customer Chat',
      'nav.user_management': 'User Management',
      'nav.shop_permissions': 'Shop Permissions',
      'nav.dashboard': 'Dashboard',
      'nav.fraud_alert': 'Fraud Alert',
      
      // Dashboard
      'dashboard.title': 'Dashboard',
      'dashboard.subtitle': 'Overview of your TikTok Shop management system',
      'dashboard.active_shops': 'Active Shops',
      'dashboard.total_orders': 'Total Orders (30d)',
      'dashboard.total_revenue': 'Total Revenue (30d)',
      'dashboard.system_health': 'System Health',
      'dashboard.pending_orders': 'Pending Orders',
      'dashboard.total_payments': 'Total Payments',
      'dashboard.withdrawals': 'Withdrawals',
      'dashboard.pending_payments': 'Pending Payments',
      'dashboard.recent_activity': 'Recent Activity',
      'dashboard.top_shops': 'Top Performing Shops',
      'dashboard.financial_overview': 'Financial Overview (Last 30 Days)',
      'dashboard.total_revenue_label': 'Total Revenue',
      'dashboard.total_withdrawals_label': 'Total Withdrawals',
      'dashboard.net_balance': 'Net Balance',
      'dashboard.excellent': 'Excellent',
      'dashboard.good': 'Good',
      'dashboard.needs_attention': 'Needs Attention',
      'dashboard.no_issues': 'No issues',
      'dashboard.alerts': 'alerts',
      'dashboard.completed': 'completed',
      'dashboard.avg': 'Avg',
      'dashboard.need_fulfillment': 'Need fulfillment',
      'dashboard.last_30_days': 'Last 30 days',
      'dashboard.total_withdrawn': 'Total withdrawn',
      'dashboard.need_processing': 'Need processing',
      'dashboard.no_recent_activity': 'No recent activity',
      'dashboard.no_shop_data': 'No shop performance data available yet',
      
      // Orders
      'orders.title': 'Orders Management',
      'orders.subtitle': 'Manage and sync TikTok orders',
      'orders.total_orders': 'Total Orders',
      'orders.completed': 'Completed',
      'orders.processing': 'Processing',
      'orders.cancelled': 'Cancelled',
      'orders.search': 'Search',
      'orders.search_placeholder': 'Search orders...',
      'orders.shop': 'Shop',
      'orders.all_shops': 'All Shops',
      'orders.status': 'Status',
      'orders.all_status': 'All Status',
      'orders.from_date': 'From Date',
      'orders.to_date': 'To Date',
      'orders.sync_orders': 'Sync Orders',
      'orders.view_details': 'View Details',
      'orders.chat_support': 'Chat Support',
      'orders.account_seller': 'Account/Seller',
      'orders.order': 'Order',
      'orders.order_info': 'Order Info',
      'orders.price': 'Price',
      'orders.actions': 'Actions',
      'orders.items': 'item(s)',
      'orders.track': 'Track',
      'orders.subtotal': 'Subtotal',
      
      // Chat
      'chat.title': 'Customer Chat',
      'chat.shops_messages': 'shops • {unread} unread messages',
      'chat.refresh': 'Refresh',
      'chat.seed_data': 'Seed Sample Data',
      'chat.clear_data': 'Clear Sample Data',
      'chat.search_placeholder': 'Search shops or customers...',
      'chat.loading_conversations': 'Loading conversations...',
      'chat.no_conversations': 'No conversations found',
      'chat.conversations': 'conversations',
      'chat.participants': 'participants',
      'chat.cannot_send': 'Cannot send messages',
      'chat.loading_messages': 'Loading messages...',
      'chat.no_messages': 'No messages in this conversation yet',
      'chat.select_conversation': 'Select a conversation',
      'chat.select_conversation_desc': 'Choose a conversation from the sidebar to view messages',
      'chat.readonly_notice': 'This is a read-only view. Use TikTok Shop Seller Center to reply to messages.',
      'chat.unknown_customer': 'Unknown Customer',
      
      // Common
      'common.loading': 'Loading...',
      'common.search': 'Search',
      'common.refresh': 'Refresh',
      'common.save': 'Save',
      'common.cancel': 'Cancel',
      'common.delete': 'Delete',
      'common.edit': 'Edit',
      'common.view': 'View',
      'common.actions': 'Actions',
      'common.status': 'Status',
      'common.date': 'Date',
      'common.total': 'Total',
      'common.yes': 'Yes',
      'common.no': 'No',
      'common.close': 'Close',
      'common.confirm': 'Confirm',
      // ===== Added keys =====
      // Bank Management
      'bank.description': 'Manage bank accounts and assign to shops',
      'bank.import_bank': 'Import Bank',
      'bank.download_template': 'Download CSV Template',
      'bank.history': 'Action History',
      'bank.search_placeholder': 'Search account number, routing number, swift code...',
      'bank.search_results': 'Found {total} bank accounts',
      'bank.clear': 'Clear',
      'bank.info': 'Bank Info',
      'bank.upload_date': 'Upload Date',
      'bank.uploader': 'Uploader',
      'bank.status': 'Status',
      'bank.shop': 'Shop',
      'bank.setup_date': 'Setup Date',
      'bank.assigned_staff': 'Staff',
      'bank.actions': 'Actions',
      'bank.used': 'Used',
      'bank.unused': 'Unused',
      'bank.no_results_with_search': 'No bank accounts match "{search}". Try another term.',
      'bank.no_banks': 'No bank accounts yet. Start by importing your first accounts.',
      'bank.pagination.showing': 'Showing',
      'bank.pagination.to': 'to',
      'bank.pagination.of': 'of',
      'bank.pagination.accounts': 'accounts',
      'bank.previous': 'Previous',
      'bank.next': 'Next',
      'bank.page': 'Page',
      // Import Bank Modal
      'bank.import.title': 'Import Bank',
      'bank.import.csv_format_title': 'Required CSV format:',
      'bank.import.note_description': 'Note: Account holder name or description',
      'bank.import.bank_name_description': 'Bank Name: Full bank name',
      'bank.import.routing_number_description': 'Routing Number: Full routing number',
      'bank.import.swift_code_description': 'Swift Code: International SWIFT code',
      'bank.import.account_number_description': 'Account Number: Full account number (no scientific notation)',
      'bank.import.type_description': 'Type: Account type (Checking, Savings, Business)',
      'bank.import.download_template': 'Download CSV template',
      'bank.import.download_excel': 'Download Excel/CSV template',
      'bank.import.drop_or_click': 'Drop CSV file here or click to select',
      'bank.import.drop_active': 'Drop the file here...',
      'bank.import.upload_file': 'Import file',
      'bank.import.number_format_warning_title': 'Important number format note:',
      'bank.import.number_format_warning_1': 'Account Number and Routing Number must be fully visible',
      'bank.import.number_format_warning_2': 'Do not shorten to scientific form (e.g. 1.55E+14)',
      'bank.import.number_format_warning_3': 'In Excel: Format cells → Number → 0 decimal places',
      'bank.import.number_format_warning_4': "Or prefix with ' to force text format",
      'bank.import.number_format_warning_5': 'Verify carefully before upload - cannot edit after confirm',
      'bank.import.review_title': 'Review before import',
      'bank.import.file': 'File',
      'bank.import.accounts_count': '{count} accounts',
      'bank.import.confirm': 'Confirm Import ({count} accounts)',
      'bank.import.reupload': 'Re-upload file',
      // Edit Managed Name Modal
      'shop.edit_managed_name.title': 'Update managed name',
      'shop.edit_managed_name.current_shop': 'Current shop:',
      'shop.edit_managed_name.tiktok_name': 'TikTok Name:',
      'shop.edit_managed_name.shop_id': 'Shop ID:',
      'shop.edit_managed_name.new_label': 'New managed name',
      'shop.edit_managed_name.placeholder': 'Enter managed name...',
      'shop.edit_managed_name.helper': 'Helps you identify the shop easily (2-50 characters)',
      'shop.edit_managed_name.min_error': 'Managed name must be at least 2 characters',
      'common.characters_count': '{count}/50',
      'common.saving': 'Saving...',
      'common.save_changes': 'Save Changes',
      // Permissions
      'permissions.title': 'Shop Permissions',
      'permissions.subtitle': 'Manage user access across all shops',
      'permissions.add_user_to_shop': 'Add user to shop',
      'permissions.search_placeholder': 'Search users or shops...',
      'permissions.all_shops': 'All shops',
      'permissions.clear': 'Clear',
      'permissions.results_found': 'Found {total} permissions',
      'permissions.search_results': 'Search results ({total})',
      'permissions.user_access': 'User access ({total})',
      'permissions.items_per_page': 'items per page',
      'permissions.showing_range': 'Showing {from} to {to} of {total} items',
      'permissions.table.user': 'User',
      'permissions.table.shop': 'Shop',
      'permissions.table.role': 'Role',
      'permissions.table.assigned_date': 'Assigned Date',
      'permissions.table.actions': 'Actions',
      'permissions.no_search_results': 'No permissions match your criteria.',
      'permissions.no_permissions': 'No user permissions found. Add a user to a shop to get started.',
      'permissions.edit': 'Edit',
      'permissions.delete': 'Delete',
      'permissions.assign_modal.title': 'Assign user to shop',
      'permissions.assign_modal.user': 'User',
      'permissions.assign_modal.select_user': 'Select user',
      'permissions.assign_modal.shop': 'Shop',
      'permissions.assign_modal.select_shop': 'Select shop',
      'permissions.assign_modal.role_permissions': 'Roles & permissions',
      'permissions.role.owner.label': 'Owner - Owner',
      'permissions.role.owner.desc': 'Full system access to all features',
      'permissions.role.resource.label': 'Resource - Resource Manager',
      'permissions.role.resource.desc': 'Connect and manage shops and system resources (cannot delete shops)',
      'permissions.role.accountant.label': 'Accountant - Accountant',
      'permissions.role.accountant.desc': 'Manage finances, reconciliation, reporting, orders and fulfillment',
      'permissions.role.seller.label': 'Seller - Sales Staff',
      'permissions.role.seller.desc': 'Manage products, orders, listings, promotions, sales activities',
      'permissions.cancel': 'Cancel',
      'permissions.assign': 'Assign',
      'permissions.assigning': 'Assigning...',
      'permissions.edit_modal.title': 'Update user role',
      'permissions.edit_modal.choose_new_role': 'Select new role',
      'permissions.updating': 'Updating...',
      'permissions.update_role': 'Update role',
      'permissions.previous': 'Previous',
      'permissions.next': 'Next',
      'permissions.page': 'Page',
      // Orders (additional / extended)
      'orders.sync_unsettled_transactions': 'Sync Unsettled Transactions',
      'orders.in_progress': 'In Progress',
      'orders.search_placeholder_full': 'Search orders by ID, email, recipient name, or product...',
      'orders.items_images': 'Items Images',
      'orders.customer_info': 'Customer Info',
      'orders.sync_detail': 'Sync Detail',
      'orders.add_tracking': 'Add tracking',
      'orders.split_orders': 'Split orders',
      'orders.view': 'View',
      'orders.no_orders_found': 'No orders found with the selected filters.',
      'orders.mark_delivered': 'Mark Delivered',
      'orders.splitted': 'Order splitted',
      'orders.items_label': 'item(s)',
      'orders.track_label': 'Track: {tracking} - {provider}',

      // Common (missing)
      'common.previous': 'Previous',
      'common.next': 'Next',
      'common.id': 'ID',
      'common.na': 'N/A',
      'common.showing_results': 'Showing {from} to {to} of {total} results',
      'common.page_of': 'Page {current} of {total}',

      // Orders runtime/status (missing)
      'orders.loading_orders': 'Loading orders...',
      'orders.searching_orders': 'Searching orders...',
      'orders.syncing_orders': 'Syncing orders...',
      'orders.syncing_unsettled_transactions': 'Syncing unsettled transactions...',
      'orders.loading_order_details': 'Loading order details...',
      'orders.splitting_order': 'Splitting order...',
      'orders.refreshing': 'Refreshing...',
      'orders.sync_success': 'Orders synced successfully',
      'orders.sync_failed': 'Sync failed',
      'orders.select_shop_sync_unsettled': 'Please select a shop to sync unsettled transactions',
      'orders.unsettled_sync_success': 'Unsettled transactions synced successfully',
      'orders.load_detail_failed': 'Failed to load order details',
      'orders.sync_detail_success': 'Synced detail for {orderId}',
      'orders.sync_detail_failed': 'Sync detail failed',

      // Orders labels (missing)
      'orders.order_status_label': 'Order Status',
      'orders.custom_status': 'Custom Status',
      'orders.page_size': 'Page Size',
      'orders.status_flow': 'Order Status Flow:',
      'orders.shop_id_label': 'Shop ID:',
      'orders.copy_customer_info': 'Copy customer information',
      'orders.mark_as_delivered_title': 'Mark as DELIVERED',
      'orders.add_tracking_title': 'Add tracking information',
      'orders.split_order_title': 'Split order into multiple packages',
      'orders.subtotal_label': 'Subtotal:',
      'orders.estimated_label': 'Est:',
  },
  vi: {
      // Navigation
      'nav.products': 'Sản phẩm',
      'nav.orders': 'Đơn hàng',
      'nav.bank': 'Quản lý bank',
      'nav.revenue': 'Tiền về',
      'nav.connect_shop': 'Kết nối Shop',
      'nav.chat': 'Trò chuyện',
      'nav.user_management': 'Quản lý user',
      'nav.shop_permissions': 'Phân quyền shop',
      'nav.dashboard': 'Bảng điều khiển',
      'nav.fraud_alert': 'Cảnh báo gian lận',
      
      // Dashboard
      'dashboard.title': 'Bảng điều khiển',
      'dashboard.subtitle': 'Tổng quan hệ thống quản lý TikTok Shop',
      'dashboard.active_shops': 'Shop hoạt động',
      'dashboard.total_orders': 'Tổng đơn hàng (30 ngày)',
      'dashboard.total_revenue': 'Tổng doanh thu (30 ngày)',
      'dashboard.system_health': 'Tình trạng hệ thống',
      'dashboard.pending_orders': 'Đơn chờ xử lý',
      'dashboard.total_payments': 'Tổng thanh toán',
      'dashboard.withdrawals': 'Rút tiền',
      'dashboard.pending_payments': 'Thanh toán chờ',
      'dashboard.recent_activity': 'Hoạt động gần đây',
      'dashboard.top_shops': 'Shop hiệu quả nhất',
      'dashboard.financial_overview': 'Tổng quan tài chính (30 ngày qua)',
      'dashboard.total_revenue_label': 'Tổng doanh thu',
      'dashboard.total_withdrawals_label': 'Tổng rút tiền',
      'dashboard.net_balance': 'Số dư ròng',
      'dashboard.excellent': 'Tuyệt vời',
      'dashboard.good': 'Tốt',
      'dashboard.needs_attention': 'Cần chú ý',
      'dashboard.no_issues': 'Không có vấn đề',
      'dashboard.alerts': 'cảnh báo',
      'dashboard.completed': 'hoàn thành',
      'dashboard.avg': 'Trung bình',
      'dashboard.need_fulfillment': 'Cần xử lý',
      'dashboard.last_30_days': '30 ngày qua',
      'dashboard.total_withdrawn': 'Tổng đã rút',
      'dashboard.need_processing': 'Cần xử lý',
      'dashboard.no_recent_activity': 'Không có hoạt động gần đây',
      'dashboard.no_shop_data': 'Chưa có dữ liệu hiệu quả shop',
      
      // Orders
      'orders.title': 'Quản lý đơn hàng',
      'orders.subtitle': 'Quản lý và đồng bộ đơn hàng TikTok',
      'orders.total_orders': 'Tổng đơn hàng',
      'orders.completed': 'Hoàn thành',
      'orders.processing': 'Đang xử lý',
      'orders.cancelled': 'Đã hủy',
      'orders.search': 'Tìm kiếm',
      'orders.search_placeholder': 'Tìm đơn hàng...',
      'orders.shop': 'Cửa hàng',
      'orders.all_shops': 'Tất cả shop',
      'orders.status': 'Trạng thái',
      'orders.all_status': 'Tất cả trạng thái',
      'orders.from_date': 'Từ ngày',
      'orders.to_date': 'Đến ngày',
      'orders.sync_orders': 'Đồng bộ đơn hàng',
      'orders.view_details': 'Xem chi tiết',
      'orders.chat_support': 'Hỗ trợ',
      'orders.account_seller': 'Tài khoản/Người bán',
      'orders.order': 'Đơn hàng',
      'orders.order_info': 'Thông tin đơn',
      'orders.price': 'Giá',
      'orders.actions': 'Thao tác',
      'orders.items': 'sản phẩm',
      'orders.track': 'Theo dõi',
      'orders.subtotal': 'Tạm tính',
      
      // Chat
      'chat.title': 'Trò chuyện khách hàng',
      'chat.shops_messages': 'shop • {unread} tin nhắn chưa đọc',
      'chat.refresh': 'Làm mới',
      'chat.seed_data': 'Tạo dữ liệu mẫu',
      'chat.clear_data': 'Xóa dữ liệu mẫu',
      'chat.search_placeholder': 'Tìm shop hoặc khách hàng...',
      'chat.loading_conversations': 'Đang tải cuộc trò chuyện...',
      'chat.no_conversations': 'Không tìm thấy cuộc trò chuyện',
      'chat.conversations': 'cuộc trò chuyện',
      'chat.participants': 'người tham gia',
      'chat.cannot_send': 'Không thể gửi tin nhắn',
      'chat.loading_messages': 'Đang tải tin nhắn...',
      'chat.no_messages': 'Chưa có tin nhắn trong cuộc trò chuyện',
      'chat.select_conversation': 'Chọn cuộc trò chuyện',
      'chat.select_conversation_desc': 'Chọn cuộc trò chuyện từ thanh bên để xem tin nhắn',
      'chat.readonly_notice': 'Đây là chế độ chỉ đọc. Sử dụng TikTok Shop Seller Center để trả lời tin nhắn.',
      'chat.unknown_customer': 'Khách hàng không xác định',
      
      // Common
      'common.loading': 'Đang tải...',
      'common.search': 'Tìm kiếm',
      'common.refresh': 'Làm mới',
      'common.save': 'Lưu',
      'common.cancel': 'Hủy',
      'common.delete': 'Xóa',
      'common.edit': 'Sửa',
      'common.view': 'Xem',
      'common.actions': 'Thao tác',
      'common.status': 'Trạng thái',
      'common.date': 'Ngày',
      'common.total': 'Tổng',
      'common.yes': 'Có',
      'common.no': 'Không',
      'common.close': 'Đóng',
      'common.confirm': 'Xác nhận',
      // ===== Added keys =====
      'bank.description': 'Quản lý tài khoản ngân hàng và gán cho shop',
      'bank.import_bank': 'Import Bank',
      'bank.download_template': 'Tải mẫu CSV',
      'bank.history': 'Lịch sử hành động',
      'bank.search_placeholder': 'Tìm Account number, Routing number, Swift code...',
      'bank.search_results': 'Tìm thấy {total} tài khoản ngân hàng',
      'bank.clear': 'Xóa',
      'bank.info': 'Thông tin Bank',
      'bank.upload_date': 'Ngày upload',
      'bank.uploader': 'Người upload',
      'bank.status': 'Tình trạng',
      'bank.shop': 'Shop',
      'bank.setup_date': 'Ngày set up',
      'bank.assigned_staff': 'Nhân sự',
      'bank.actions': 'Hành động',
      'bank.used': 'Đã dùng',
      'bank.unused': 'Chưa dùng',
      'bank.no_results_with_search': 'Không có tài khoản trùng với "{search}". Thử từ khóa khác.',
      'bank.no_banks': 'Chưa có tài khoản ngân hàng. Bắt đầu bằng cách import.',
      'bank.pagination.showing': 'Hiển thị',
      'bank.pagination.to': 'đến',
      'bank.pagination.of': 'của',
      'bank.pagination.accounts': 'tài khoản',
      'bank.previous': 'Trước',
      'bank.next': 'Tiếp theo',
      'bank.page': 'Trang',
      // Import Bank Modal
      'bank.import.title': 'Import Bank',
      'bank.import.csv_format_title': 'Định dạng CSV yêu cầu:',
      'bank.import.note_description': 'Note: Ghi chú hoặc tên chủ tài khoản',
      'bank.import.bank_name_description': 'Bank Name: Tên ngân hàng đầy đủ',
      'bank.import.routing_number_description': 'Routing Number: Số định tuyến',
      'bank.import.swift_code_description': 'Swift Code: Mã SWIFT quốc tế',
      'bank.import.account_number_description': 'Account Number: Đầy đủ (không dạng khoa học)',
      'bank.import.type_description': 'Type: Loại tài khoản (Checking, Savings...)',
      'bank.import.download_template': 'Tải file mẫu CSV',
      'bank.import.download_excel': 'Tải mẫu Excel/CSV',
      'bank.import.drop_or_click': 'Kéo thả file CSV hoặc nhấp để chọn',
      'bank.import.drop_active': 'Thả file vào đây...',
      'bank.import.upload_file': 'Import file',
      'bank.import.number_format_warning_title': '⚠️ Lưu ý định dạng số:',
      'bank.import.number_format_warning_1': 'Account Number & Routing Number phải hiển thị đầy đủ',
      'bank.import.number_format_warning_2': 'Không rút gọn dạng 1.55E+14',
      'bank.import.number_format_warning_3': 'Trong Excel: Format cells → Number → 0 decimal',
      'bank.import.number_format_warning_4': "Hoặc thêm dấu ' để thành dạng text",
      'bank.import.number_format_warning_5': 'Kiểm tra kỹ trước khi xác nhận - không thể sửa',
      'bank.import.review_title': 'Kiểm tra trước khi import',
      'bank.import.file': 'File',
      'bank.import.accounts_count': '{count} tài khoản',
      'bank.import.confirm': '✅ Xác nhận Import ({count} tài khoản)',
      'bank.import.reupload': '🔄 Upload lại file',
      // Edit Managed Name Modal
      'shop.edit_managed_name.title': 'Cập nhật tên quản lý',
      'shop.edit_managed_name.current_shop': 'Shop hiện tại:',
      'shop.edit_managed_name.tiktok_name': 'TikTok Name:',
      'shop.edit_managed_name.shop_id': 'Shop ID:',
      'shop.edit_managed_name.new_label': 'Tên quản lý mới',
      'shop.edit_managed_name.placeholder': 'Nhập tên quản lý...',
      'shop.edit_managed_name.helper': 'Giúp bạn nhận diện shop (2-50 ký tự)',
      'shop.edit_managed_name.min_error': 'Tên quản lý phải ít nhất 2 ký tự',
      'common.characters_count': '{count}/50',
      'common.saving': 'Đang lưu...',
      'common.save_changes': 'Lưu thay đổi',
      // Permissions
      'permissions.title': 'Phân quyền cửa hàng',
      'permissions.subtitle': 'Quản lý quyền truy cập người dùng trên tất cả shop',
      'permissions.add_user_to_shop': 'Thêm người dùng vào cửa hàng',
      'permissions.search_placeholder': 'Tìm kiếm người dùng hoặc cửa hàng...',
      'permissions.all_shops': 'Tất cả cửa hàng',
      'permissions.clear': 'Xóa',
      'permissions.results_found': 'Tìm thấy {total} quyền',
      'permissions.search_results': 'Kết quả tìm kiếm ({total})',
      'permissions.user_access': 'Quyền truy cập của người dùng ({total})',
      'permissions.items_per_page': 'mục mỗi trang',
      'permissions.showing_range': 'Hiển thị {from} đến {to} của {total} mục',
      'permissions.table.user': 'Người dùng',
      'permissions.table.shop': 'Cửa hàng',
      'permissions.table.role': 'Quyền',
      'permissions.table.assigned_date': 'Ngày phân công',
      'permissions.table.actions': 'Thao tác',
      'permissions.no_search_results': 'Không có quyền nào khớp tiêu chí tìm kiếm.',
      'permissions.no_permissions': 'Chưa có quyền. Thêm người dùng vào cửa hàng để bắt đầu.',
      'permissions.edit': 'Sửa',
      'permissions.delete': 'Xóa',
      'permissions.assign_modal.title': 'Phân quyền người dùng vào cửa hàng',
      'permissions.assign_modal.user': 'Người dùng',
      'permissions.assign_modal.select_user': 'Chọn người dùng',
      'permissions.assign_modal.shop': 'Cửa hàng',
      'permissions.assign_modal.select_shop': 'Chọn cửa hàng',
      'permissions.assign_modal.role_permissions': 'Vai trò & quyền hạn',
      'permissions.role.owner.label': 'Owner - Chủ sở hữu',
      'permissions.role.owner.desc': 'Toàn quyền hệ thống',
      'permissions.role.resource.label': 'Resource - Quản lý Tài nguyên',
      'permissions.role.resource.desc': 'Kết nối & quản lý shop (không được xóa shop)',
      'permissions.role.accountant.label': 'Accountant - Kế toán',
      'permissions.role.accountant.desc': 'Quản lý tài chính, đối soát, báo cáo, đơn hàng',
      'permissions.role.seller.label': 'Seller - Nhân viên bán hàng',
      'permissions.role.seller.desc': 'Quản lý sản phẩm, đơn hàng, khuyến mãi',
      'permissions.cancel': 'Hủy',
      'permissions.assign': 'Phân quyền',
      'permissions.assigning': 'Đang phân quyền...',
      'permissions.edit_modal.title': 'Cập nhật quyền người dùng',
      'permissions.edit_modal.choose_new_role': 'Chọn vai trò mới',
      'permissions.updating': 'Đang cập nhật...',
      'permissions.update_role': 'Cập nhật quyền',
      'permissions.previous': 'Trước',
      'permissions.next': 'Tiếp theo',
      'permissions.page': 'Trang',
      // Orders additions
      'orders.sync_unsettled_transactions': 'Sync Unsettled Transaction',
      'orders.in_progress': 'Đang xử lý',
      'orders.search_placeholder_full': 'Tìm đơn theo ID, email, tên người nhận hoặc sản phẩm...',
      'orders.items_images': 'Hình ảnh SP',
      'orders.customer_info': 'Thông tin KH',
      'orders.sync_detail': 'Sync Detail',
      'orders.add_tracking': 'Thêm tracking',
      'orders.split_orders': 'Split orders',
      'orders.view': 'Xem',
      'orders.no_orders_found': 'Không có đơn hàng với bộ lọc hiện tại.',
      'orders.mark_delivered': 'Kéo đơn',
      'orders.splitted': 'Đã split order',
      'orders.items_label': ' sản phẩm',
      'orders.track_label': 'Track: {tracking} - {provider}',

      // Common (missing)
      'common.previous': 'Trước',
      'common.next': 'Tiếp theo',
      'common.id': 'ID',
      'common.na': 'N/A',
      'common.showing_results': 'Hiển thị {from} đến {to} của {total} kết quả',
      'common.page_of': 'Trang {current} / {total}',

      // Orders runtime/status (missing)
      'orders.loading_orders': 'Đang tải đơn hàng...',
      'orders.searching_orders': 'Đang tìm kiếm đơn hàng...',
      'orders.syncing_orders': 'Đang đồng bộ đơn hàng...',
      'orders.syncing_unsettled_transactions': 'Đang đồng bộ giao dịch chưa quyết toán...',
      'orders.loading_order_details': 'Đang tải chi tiết đơn hàng...',
      'orders.splitting_order': 'Đang tách đơn...',
      'orders.refreshing': 'Đang làm mới...',
      'orders.sync_success': 'Đồng bộ đơn hàng thành công',
      'orders.sync_failed': 'Đồng bộ thất bại',
      'orders.select_shop_sync_unsettled': 'Vui lòng chọn shop để đồng bộ giao dịch chưa quyết toán',
      'orders.unsettled_sync_success': 'Đồng bộ giao dịch chưa quyết toán thành công',
      'orders.load_detail_failed': 'Tải chi tiết đơn hàng thất bại',
      'orders.sync_detail_success': 'Đã sync chi tiết cho {orderId}',
      'orders.sync_detail_failed': 'Sync chi tiết thất bại',

      // Orders labels (missing)
      'orders.order_status_label': 'Trạng thái đơn',
      'orders.custom_status': 'Trạng thái nội bộ',
      'orders.page_size': 'Số dòng / trang',
      'orders.status_flow': 'Luồng trạng thái đơn:',
      'orders.shop_id_label': 'Shop ID:',
      'orders.copy_customer_info': 'Sao chép thông tin khách hàng',
      'orders.mark_as_delivered_title': 'Đánh dấu đã kéo đơn',
      'orders.add_tracking_title': 'Thêm thông tin tracking',
      'orders.split_order_title': 'Tách đơn thành nhiều kiện',
      'orders.subtotal_label': 'Tạm tính:',
      'orders.estimated_label': 'Est:',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const [language, setLanguageState] = useState<Language>('vi');

    useEffect(() => {
        // Load saved language from localStorage
        const savedLanguage = localStorage.getItem('language') as Language;
        if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'vi')) {
            setLanguageState(savedLanguage);
        }
    }, []);

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
        localStorage.setItem('language', lang);
    };

    const t = (key: string, params?: Record<string, string | number>) => {
        let translation = translations[language][key] || translations['en'][key] || key;
        
        // Replace parameters in translation
        if (params) {
            Object.entries(params).forEach(([paramKey, value]) => {
                translation = translation.replace(`{${paramKey}}`, String(value));
            });
        }
        
        return translation;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
