'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'vi';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string, params?: Record<string, string | number>) => string;
}

type TranslationMap = {
    [key: string]: string;
};

const translations: Record<Language, TranslationMap> = {
    en: {
        // Navigation
        'nav.products': 'Products',
        'nav.orders': 'Orders',
        'nav.bank': 'Bank Management',
        'nav.revenue': 'Revenue',
        'nav.connect_shop': 'Connect Shop',
        'nav.user_management': 'User Management',
        'nav.shop_permissions': 'Shop Permissions',
        'nav.dashboard': 'Dashboard',
        'nav.fraud_alert': 'Fraud Alert',
        'nav.organizations': 'Organizations',

        // Dashboard
        'dashboard.title': 'Dashboard',
        'dashboard.subtitle': 'Overview of your TikTok Shop management system',
        'dashboard.active_shops': 'Active Shops',
        'dashboard.total_orders': 'Total Orders (30d)',
        'dashboard.total_revenue': 'Total Revenue (30d)',
        'dashboard.system_health': 'System Health',
        'dashboard.pending_orders': 'Pending Orders',
        'dashboard.total_payments': 'Total Payments',
        'dashboard.withdrawals': 'Withdrawals',
        'dashboard.pending_payments': 'Pending Payments',
        'dashboard.recent_activity': 'Recent Activity',
        'dashboard.top_shops': 'Top Performing Shops',
        'dashboard.financial_overview': 'Financial Overview (Last 30 Days)',
        'dashboard.total_revenue_label': 'Total Revenue',
        'dashboard.total_withdrawals_label': 'Total Withdrawals',
        'dashboard.net_balance': 'Net Balance',
        'dashboard.excellent': 'Excellent',
        'dashboard.good': 'Good',
        'dashboard.needs_attention': 'Needs Attention',
        'dashboard.no_issues': 'No issues',
        'dashboard.alerts': 'alerts',
        'dashboard.completed': 'completed',
        'dashboard.avg': 'Avg',
        'dashboard.need_fulfillment': 'Need fulfillment',
        'dashboard.last_30_days': 'Last 30 days',
        'dashboard.total_withdrawn': 'Total withdrawn',
        'dashboard.need_processing': 'Need processing',
        'dashboard.no_recent_activity': 'No recent activity',
        'dashboard.no_shop_data': 'No shop performance data available yet',

        // Orders
        'orders.title': 'Orders Management',
        'orders.subtitle': 'Manage and sync TikTok orders',
        'orders.total_orders': 'Total Orders',
        'orders.completed': 'Completed',
        'orders.processing': 'Processing',
        'orders.cancelled': 'Cancelled',
        'orders.search': 'Search',
        'orders.search_placeholder': 'Search orders...',
        'orders.shop': 'Shop',
        'orders.all_shops': 'All Shops',
        'orders.status': 'Status',
        'orders.all_status': 'All Status',
        'orders.from_date': 'From Date',
        'orders.to_date': 'To Date',
        'orders.sync_orders': 'Sync Orders',
        'orders.view_details': 'View Details',
        'orders.chat_support': 'Chat Support',
        'orders.account_seller': 'Account/Seller',
        'orders.order': 'Order',
        'orders.order_info': 'Order Info',
        'orders.price': 'Price',
        'orders.actions': 'Actions',
        'orders.items': 'item(s)',
        'orders.track': 'Track',
        'orders.subtotal': 'Subtotal',

        // Chat
        'chat.title': 'Customer Chat',
        'chat.shops_messages': 'shops • {unread} unread messages',
        'chat.refresh': 'Refresh',
        'chat.seed_data': 'Seed Sample Data',
        'chat.clear_data': 'Clear Sample Data',
        'chat.search_placeholder': 'Search shops or customers...',
        'chat.loading_conversations': 'Loading conversations...',
        'chat.no_conversations': 'No conversations found',
        'chat.conversations': 'conversations',
        'chat.participants': 'participants',
        'chat.cannot_send': 'Cannot send messages',
        'chat.loading_messages': 'Loading messages...',
        'chat.no_messages': 'No messages in this conversation yet',
        'chat.select_conversation': 'Select a conversation',
        'chat.select_conversation_desc': 'Choose a conversation from the sidebar to view messages',
        'chat.readonly_notice': 'This is a read-only view. Use TikTok Shop Seller Center to reply to messages.',
        'chat.unknown_customer': 'Unknown Customer',

        // Common
        'common.loading': 'Loading...',
        'common.search': 'Search',
        'common.refresh': 'Refresh',
        'common.save': 'Save',
        'common.cancel': 'Cancel',
        'common.delete': 'Delete',
        'common.edit': 'Edit',
        'common.view': 'View',
        'common.actions': 'Actions',
        'common.status': 'Status',
        'common.date': 'Date',
        'common.total': 'Total',
        'common.yes': 'Yes',
        'common.no': 'No',
        'common.close': 'Close',
        'common.confirm': 'Confirm',
        // ===== Added keys =====
        // Bank Management
        'bank.description': 'Manage bank accounts and assign to shops',
        'bank.import_bank': 'Import Bank',
        'bank.download_template': 'Download CSV Template',
        'bank.history': 'Action History',
        'bank.search_placeholder': 'Search account number, routing number, swift code...',
        'bank.search_results': 'Found {total} bank accounts',
        'bank.clear': 'Clear',
        'bank.info': 'Bank Info',
        'bank.upload_date': 'Upload Date',
        'bank.uploader': 'Uploader',
        'bank.status': 'Status',
        'bank.shop': 'Shop',
        'bank.setup_date': 'Setup Date',
        'bank.assigned_staff': 'Staff',
        'bank.actions': 'Actions',
        'bank.used': 'Used',
        'bank.unused': 'Unused',
        'bank.no_results_with_search': 'No bank accounts match "{search}". Try another term.',
        'bank.no_banks': 'No bank accounts yet. Start by importing your first accounts.',
        'bank.pagination.showing': 'Showing',
        'bank.pagination.to': 'to',
        'bank.pagination.of': 'of',
        'bank.pagination.accounts': 'accounts',
        'bank.previous': 'Previous',
        'bank.next': 'Next',
        'bank.page': 'Page',
        // Import Bank Modal
        'bank.import.title': 'Import Bank',
        'bank.import.csv_format_title': 'Required CSV format:',
        'bank.import.note_description': 'Note: Account holder name or description',
        'bank.import.bank_name_description': 'Bank Name: Full bank name',
        'bank.import.routing_number_description': 'Routing Number: Full routing number',
        'bank.import.swift_code_description': 'Swift Code: International SWIFT code',
        'bank.import.account_number_description': 'Account Number: Full account number (no scientific notation)',
        'bank.import.type_description': 'Type: Account type (Checking, Savings, Business)',
        'bank.import.download_template': 'Download CSV template',
        'bank.import.download_excel': 'Download Excel/CSV template',
        'bank.import.drop_or_click': 'Drop CSV file here or click to select',
        'bank.import.drop_active': 'Drop the file here...',
        'bank.import.upload_file': 'Import file',
        'bank.import.number_format_warning_title': 'Important number format note:',
        'bank.import.number_format_warning_1': 'Account Number and Routing Number must be fully visible',
        'bank.import.number_format_warning_2': 'Do not shorten to scientific form (e.g. 1.55E+14)',
        'bank.import.number_format_warning_3': 'In Excel: Format cells → Number → 0 decimal places',
        'bank.import.number_format_warning_4': "Or prefix with ' to force text format",
        'bank.import.number_format_warning_5': 'Verify carefully before upload - cannot edit after confirm',
        'bank.import.review_title': 'Review before import',
        'bank.import.file': 'File',
        'bank.import.accounts_count': '{count} accounts',
        'bank.import.confirm': 'Confirm Import ({count} accounts)',
        'bank.import.reupload': 'Re-upload file',
        // Edit Managed Name Modal
        'shop.edit_managed_name.title': 'Update managed name',
        'shop.edit_managed_name.current_shop': 'Current shop:',
        'shop.edit_managed_name.tiktok_name': 'TikTok Name:',
        'shop.edit_managed_name.shop_id': 'Shop ID:',
        'shop.edit_managed_name.new_label': 'New managed name',
        'shop.edit_managed_name.placeholder': 'Enter managed name...',
        'shop.edit_managed_name.helper': 'Helps you identify the shop easily (2-50 characters)',
        'shop.edit_managed_name.min_error': 'Managed name must be at least 2 characters',
        'common.characters_count': '{count}/50',
        'common.saving': 'Saving...',
        'common.save_changes': 'Save Changes',
    'shops.actions.manage_access': 'Manage access',
    'shops.actions.assign_group': 'Assign group',
    'shops.assign_modal.title': 'Manage access for {shop}',
    'shops.assign_modal.group_label': 'Group access',
    'shops.assign_modal.select_group': 'Select group',
    'shops.assign_modal.unassigned': 'Unassigned',
    'shops.assign_modal.save_group': 'Update group',
    'shops.assign_modal.group_help': 'Assign this shop to a group to inherit manager access.',
    'shops.assign_modal.load_failed': 'Failed to load shop groups',
    'shops.assign_modal.save_failed': 'Failed to update shop group',
    'shops.assign_modal.success': 'Shop group updated successfully',
    'shops.assign_modal.user_label': 'Direct user access',
    'shops.assign_modal.select_user': 'Select user',
    'shops.assign_modal.select_role': 'Select role',
    'shops.assign_modal.add_user': 'Add user',
    'shops.assign_modal.current_access': 'Current users',
    'shops.assign_modal.remove_user': 'Remove',
    'shops.group_label': 'Group',
    'shops.no_group': 'No group assigned',
    'shops.no_users': 'No direct users yet',
    'shopGroups.title': 'Shop groups',
    'shopGroups.subtitle': 'Organize shops by manager teams',
    'shopGroups.total_shops': '{count} shops',
    'shopGroups.manager': 'Manager',
    'shopGroups.members': 'Members',
    'shopGroups.add_shop': 'Add shop',
    'shopGroups.remove_shop': 'Remove',
    'shopGroups.current_shops': 'Shops in group',
    'shopGroups.no_shops': 'This group has no shops yet',
    'shopGroups.no_groups': 'No groups found',
    'shopGroups.refresh': 'Refresh',
    'shopGroups.assign_modal.title': 'Add shop to {group}',
    'shopGroups.assign_modal.select_shop': 'Select shop',
    'shopGroups.assign_modal.submit': 'Assign shop',
    'shopGroups.assign_modal.submitting': 'Assigning...',
    'shopGroups.unassigned': 'Unassigned',
        // Permissions
        'permissions.title': 'Shop Permissions',
        'permissions.subtitle': 'Manage user access across all shops',
    'permissions.add_user_to_shop': 'Add user to shop',
    'permissions.add_user_with_group': 'Assign via group',
        'permissions.search_placeholder': 'Search users or shops...',
        'permissions.all_shops': 'All shops',
        'permissions.clear': 'Clear',
        'permissions.results_found': 'Found {total} permissions',
        'permissions.search_results': 'Search results',
        'permissions.user_access': 'User access',
        'permissions.items_per_page': 'items per page',
        'permissions.showing_range': 'Showing {from} to {to} of {total} items',
        'permissions.table.user': 'User',
        'permissions.table.shop': 'Shop',
        'permissions.table.role': 'Role',
        'permissions.table.assigned_date': 'Assigned Date',
        'permissions.table.actions': 'Actions',
        'permissions.no_search_results': 'No permissions match your criteria.',
        'permissions.no_permissions': 'No user permissions found. Add a user to a shop to get started.',
        'permissions.edit': 'Edit',
        'permissions.delete': 'Delete',
        'permissions.assign_modal.title': 'Assign user to shop',
        'permissions.assign_modal.user': 'User',
        'permissions.assign_modal.select_user': 'Select user',
        'permissions.assign_modal.shop': 'Shop',
        'permissions.assign_modal.select_shop': 'Select shop',
        'permissions.assign_modal.role_permissions': 'Roles & permissions',
        'permissions.role.owner.label': 'Owner - Owner',
        'permissions.role.owner.desc': 'Full system access to all features',
        'permissions.role.resource.label': 'Resource - Resource Manager',
        'permissions.role.resource.desc': 'Connect and manage shops and system resources (cannot delete shops)',
        'permissions.role.accountant.label': 'Accountant - Accountant',
        'permissions.role.accountant.desc': 'Manage finances, reconciliation, reporting, orders and fulfillment',
        'permissions.role.seller.label': 'Seller - Sales Staff',
        'permissions.role.seller.desc': 'Manage products, orders, listings, promotions, sales activities',
        'permissions.cancel': 'Cancel',
    'permissions.assign': 'Assign',
    'permissions.assigning': 'Assigning...',
    'permissions.assign_with_group.title': 'Assign user to shop & group',
    'permissions.assign_with_group.user': 'User',
    'permissions.assign_with_group.group': 'Group',
    'permissions.assign_with_group.group_optional_hint': 'Optional — select a group to inherit manager access',
    'permissions.assign_with_group.no_groups': 'No groups available',
    'permissions.assign_with_group.shop': 'Shop',
    'permissions.assign_with_group.no_shops': 'No shops linked to this group',
    'permissions.assign_with_group.role': 'Role',
    'permissions.assign_with_group.submit': 'Assign user',
    'permissions.assign_with_group.submitting': 'Assigning...',
    'permissions.assign_with_group.success': 'User assigned successfully.',
    'permissions.assign_with_group.error_generic': 'Failed to assign user. Please try again.',
    'permissions.groups.title': 'Shop groups',
    'permissions.groups.subtitle': 'Organize shops and members into shared access groups',
    'permissions.groups.table.group': 'Group',
    'permissions.groups.table.manager': 'Manager',
    'permissions.groups.table.members': 'Members',
    'permissions.groups.table.shops': 'Shops',
    'permissions.groups.no_groups': 'No groups yet. Create a group from the shops page to get started.',
    'permissions.groups.no_members': 'No members yet',
    'permissions.groups.no_shops': 'No shops assigned',
    'permissions.groups.more_members': '+{count} more',
    'permissions.groups.more_shops': '+{count} more',
    'permissions.groups.shop_count_summary': '{count} shop(s)',
    'permissions.groups.load_failed': 'Failed to load shop groups',
    'permissions.groups.create_button': 'Create group',
    'permissions.groups.create_modal.title': 'Create shop group',
    'permissions.groups.create_modal.description': 'Create a group to share shop access across managers and members.',
    'permissions.groups.create_modal.name_label': 'Group name',
    'permissions.groups.create_modal.name_placeholder': 'Enter group name',
    'permissions.groups.create_modal.name_required': 'Group name is required',
    'permissions.groups.create_modal.manager_label': 'Group manager',
    'permissions.groups.create_modal.manager_placeholder': 'Select manager',
    'permissions.groups.create_modal.manager_required': 'Group manager is required',
    'permissions.groups.create_modal.no_users': 'No users available. Create users before creating a group.',
    'permissions.groups.create_modal.members_label': 'Additional members',
    'permissions.groups.create_modal.members_placeholder': 'Search and select members…',
    'permissions.groups.create_modal.no_other_users': 'No other users available to add.',
    'permissions.groups.create_modal.members_hint': 'Optional — select additional members to include. They inherit the group access.',
    'permissions.groups.create_modal.description_label': 'Description',
    'permissions.groups.create_modal.description_placeholder': 'Add a short note for this group (optional)',
    'permissions.groups.create_modal.submit': 'Create group',
    'permissions.groups.create_modal.loading': 'Creating...',
    'permissions.groups.create_modal.success': 'Group created successfully',
    'permissions.groups.create_modal.error': 'Failed to create group',
    'permissions.groups.add_user': 'Add user',
    'permissions.groups.add_shop': 'Add shop',
    'permissions.groups.add_user_success': 'User added to group successfully',
    'permissions.groups.add_user_error': 'Failed to add user to group',
    'permissions.groups.add_shop_success': 'Assigned {count} shop(s) to group successfully',
    'permissions.groups.add_shop_error': 'Failed to assign shop to group',
    'permissions.groups.add_user_modal.title': 'Add user to group',
    'permissions.groups.add_user_modal.description': 'Select a user to join "{group}".',
    'permissions.groups.add_user_modal.user_label': 'User',
    'permissions.groups.add_user_modal.user_placeholder': 'Search and select users…',
    'permissions.groups.add_user_modal.no_users': 'All eligible users are already in this group.',
    'permissions.groups.add_user_modal.no_options': 'No matching users.',
    'permissions.groups.add_user_modal.no_selection': 'Select at least one user to continue.',
    'permissions.groups.add_user_modal.shop_label': 'Shops to grant access',
    'permissions.groups.add_user_modal.shop_helper': 'Users will receive access with seller role to selected shops. They must already belong to this group.',
    'permissions.groups.add_user_modal.no_shops': 'This group has no shops assigned yet.',
    'permissions.groups.add_user_modal.shops_placeholder': 'Search shops in this group...',
    'permissions.groups.add_user_modal.shops_no_options': 'No matching shops.',
    'permissions.groups.add_user_modal.submit': 'Add user',
    'permissions.groups.add_user_modal.loading': 'Adding...',
    'permissions.groups.add_shop_modal.title': 'Add shops to group',
    'permissions.groups.add_shop_modal.description': 'Choose one or more shops to associate with "{group}".',
    'permissions.groups.add_shop_modal.shop_label': 'Shops',
    'permissions.groups.add_shop_modal.placeholder': 'Search and select shops…',
    'permissions.groups.add_shop_modal.no_shops': 'No available shops to assign.',
    'permissions.groups.add_shop_modal.no_options': 'No shops match your search.',
    'permissions.groups.add_shop_modal.no_selection': 'Select at least one shop to continue.',
    'permissions.groups.add_shop_modal.submit': 'Add shops',
    'permissions.groups.add_shop_modal.loading': 'Assigning...',
    'permissions.groups.add_shop_modal.current_group_label': 'Current group:',
    'permissions.groups.add_shop_modal.helper': 'Type to search and click to add multiple shops. Press Backspace to remove a selection.',
    'permissions.groups.manage_members.title': 'Current members',
    'permissions.groups.manage_members.no_members': 'This group has no members yet.',
    'permissions.groups.manage_members.remove': 'Remove',
    'permissions.groups.manage_members.default_badge': 'Default',
    'permissions.groups.manage_members.cannot_remove_default': 'The default member cannot be removed.',
    'permissions.groups.remove_user_confirm': 'Remove {name} from this group?',
    'permissions.groups.remove_user_success': '{name} was removed from the group.',
    'permissions.groups.remove_user_error': 'Unable to remove user from the group. Please try again.',
    'permissions.groups.remove_user_cascade_warning': 'Removed {name}, but failed to revoke access for: {shops}. Please review their shop roles.',
    'permissions.groups.add_user_grant_warning': 'Added user but failed to grant access for {shops} shop(s). Please review their shop roles.',
    'permissions.groups.unknown_user': 'Unknown user',
        'permissions.edit_modal.title': 'Update user role',
        'permissions.edit_modal.choose_new_role': 'Select new role',
        'permissions.updating': 'Updating...',
        'permissions.update_role': 'Update role',
        'permissions.previous': 'Previous',
        'permissions.next': 'Next',
        'permissions.page': 'Page',
        // Orders (additional / extended)
        'orders.sync_unsettled_transactions': 'Sync Unsettled Transactions',
        'orders.in_progress': 'In Progress',
        'orders.search_placeholder_full': 'Search orders by ID, email, recipient name, or product...',
        'orders.items_images': 'Items Images',
        'orders.customer_info': 'Customer Info',
        'orders.sync_detail': 'Sync Detail',
        'orders.add_tracking': 'Add tracking',
        'orders.split_orders': 'Split orders',
        'orders.view': 'View',
    'orders.view_tracking': 'View tracking',
    'orders.tracking_modal.title': 'Tracking history',
    'orders.tracking_modal.subtitle': 'Latest carrier updates for this order.',
    'orders.tracking_modal.updated_at': 'Updated',
    'orders.tracking_modal.description': 'Description',
    'orders.tracking_modal.empty': 'No tracking events yet.',
    'orders.tracking_load_failed': 'Failed to load tracking information',
        'orders.no_orders_found': 'No orders found with the selected filters.',
        'orders.mark_delivered': 'Mark Delivered',
        'orders.splitted': 'Order splitted',
        'orders.items_label': 'item(s)',
        'orders.track_label': 'Track: ',
        // Alerts & SLA
        'orders.alert.ship_within_24h': 'Ship within 24h',
        'orders.alert.auto_cancelling_24h': 'Auto-cancelling <24h',
        'orders.alert.shipping_overdue': 'Shipping overdue',
        'orders.alert.cancellation_requested': 'Cancellation requested',
        'orders.alert.logistics_issue': 'Logistics issue',
        'orders.alert.return_refund': 'Return/Refund',
        'orders.sla_column': 'SLA / Due Times',
        'orders.sla.ship_due': 'Ship Due',
        'orders.sla.collection_due': 'Collection Due',
        'orders.sla.delivery_due': 'Delivery Due',
        'orders.sla.cancel_sla': 'Cancel SLA',
        'orders.sla.tts_sla': 'TTS SLA',
        'orders.sla.rts_sla': 'RTS SLA',
        'orders.sla.delivery_sla': 'Delivery SLA',
        'orders.sla.fast_dispatch': 'Fast Dispatch',
        'orders.sla.pickup_cutoff': 'Pickup Cutoff',
        'orders.sla.req_delivery': 'Req. Delivery',
        'orders.sla.rts_at': 'RTS At',
        'orders.sla.collected_at': 'Collected At',
        'orders.sla.cancelled_at': 'Cancelled At',
        'orders.sla.req_cancel_at': 'Req. Cancel At',
        'orders.sla.release_date': 'Release Date',
        // SLA descriptions (EN)
        'orders.sla.desc.rts_sla': 'rts_sla_time: Latest shipping (RTS) time specified by the platform. ',
        'orders.sla.desc.tts_sla': 'tts_sla_time: Automatic cancellation time defined by the platform. ',
        'orders.sla.desc.delivery_sla': 'delivery_sla_time: Order must arrive by this time to be on-time and avoid late delivery penalties.',
        'orders.sla.desc.ship_due': 'shipping_due_time: Deadline to create/confirm shipment before breach.',
        'orders.sla.desc.collection_due': 'collection_due_time: Latest time courier should collect the package.',
        'orders.sla.desc.delivery_due': 'delivery_due_time: Expected delivery due (soft expectation).',
        'orders.sla.desc.cancel_sla': 'cancel_order_sla_time: Platform auto-cancellation cutoff.',
        'orders.sla.desc.fast_dispatch': 'fast_dispatch_sla_time: SLA for fast dispatch orders.',
        'orders.sla.desc.pickup_cutoff': 'pick_up_cut_off_time: Cutoff time for pickup request submission.',
        'orders.sla.desc.req_delivery': 'delivery_option_required_delivery_time: Required delivery time for selected option.',
        'orders.sla.desc.events.generic': 'Event timestamp captured from logistics lifecycle.',

        // Common (missing)
        'common.previous': 'Previous',
        'common.next': 'Next',
        'common.id': 'ID',
        'common.na': 'N/A',
        'common.showing_results': 'Showing {from} to {to} of {total} results',
        'common.page_of': 'Page {current} of {total}',

        // Orders runtime/status (missing)
        'orders.loading_orders': 'Loading orders...',
        'orders.searching_orders': 'Searching orders...',
        'orders.syncing_orders': 'Syncing orders...',
        'orders.syncing_unsettled_transactions': 'Syncing unsettled transactions...',
        'orders.loading_order_details': 'Loading order details...',
        'orders.splitting_order': 'Splitting order...',
        'orders.refreshing': 'Refreshing...',
        'orders.sync_success': 'Orders synced successfully',
        'orders.sync_failed': 'Sync failed',
        'orders.select_shop_sync_unsettled': 'Please select a shop to sync unsettled transactions',
        'orders.unsettled_sync_success': 'Unsettled transactions synced successfully',
        'orders.load_detail_failed': 'Failed to load order details',
        'orders.sync_detail_success': 'Synced detail for {orderId}',
        'orders.sync_detail_failed': 'Sync detail failed',

        // Orders labels (missing)
        'orders.order_status_label': 'Order Status',
        'orders.custom_status': 'Custom Status',
        'orders.page_size': 'Page Size',
        'orders.status_flow': 'Order Status Flow:',
        'orders.shop_id_label': 'Shop ID:',
        'orders.copy_customer_info': 'Copy customer information',
        'orders.mark_as_delivered_title': 'Mark as DELIVERED',
        'orders.add_tracking_title': 'Add tracking information',
        'orders.split_order_title': 'Split order into multiple packages',
        'orders.subtotal_label': 'Subtotal:',
        'orders.estimated_label': 'Est:',
        'orders.split_failed': "Order split failed",
        'orders.split_success': 'Order split successfully',

        // Products Page (EN)
        'products.title': 'Product Catalog',
        'products.subtitle': 'Manage, search & sync TikTok products efficiently.',
        'products.bulk_sync': 'Bulk Sync',
        'products.export': 'Export',
        'products.exporting': 'Exporting...',
        'products.refresh': 'Refresh',
        'products.show_filters': 'Show Filters',
        'products.hide_filters': 'Hide Filters',
        'products.stats.total': 'Total',
        'products.stats.active': 'Active',
        'products.stats.seller_deactivated': 'Seller Deactivated',
        'products.stats.platform_deactivated': 'Platform Deactivated',
        'products.search_placeholder': 'Search by product name, ID, SKU, description...',
        'products.clear': 'Clear',
        'products.filter.shop': 'Shop',
        'products.filter.status': 'Status',
        'products.filter.listing_quality': 'Listing Quality',
        'products.filter.from_date': 'From Date',
        'products.filter.to_date': 'To Date',
        'products.table.images': 'Images',
        'products.table.info': 'Product Info',
        'products.table.listing_quality': 'Listing Quality',
        'products.table.price': 'Price',
        'products.table.status': 'Status',
        'products.table.created_at': 'Created',
        'products.table.updated_at': 'Updated',
        'products.table.actions': 'Actions',
    'products.table.shop': 'Shop',
    'products.table.timestamps': 'Timestamps',
        'products.actions.view': 'View',
        'products.actions.copy_id': 'ID',
        'products.actions.sync': 'Sync',
        'products.no_results': 'No products found with current filters.',
        'products.loading': 'Loading products...',
        'products.searching': 'Searching products...',
        'products.sync.loading_single': 'Syncing product...',
        'products.sync.success_single': 'Product synced',
        'products.sync.failed_single': 'Sync failed',
        'products.export.success': 'Export successful',
        'products.export.failed': 'Export failed',
        'products.export.empty': 'No products to export',
        'products.copy.success': 'Copied',
    'products.detail.title': 'Product Details',
    'products.detail.subtitle': 'Full enriched product data',
    'products.detail.section.media': 'Media & Gallery',
    'products.detail.section.core': 'Core Attributes',
    'products.detail.section.pricing': 'SKUs & Pricing',
    'products.detail.section.metrics': 'Quality & Metrics',
    'products.detail.section.identifiers': 'Identifiers',
    'products.detail.section.description': 'Description',
    'products.detail.no_skus': 'No SKUs available',
    'products.detail.close': 'Close',
        'products.pagination.rows_per_page': 'Rows per page:',
        'products.pagination.range': 'Showing {from}-{to} of {total}',
        'products.pagination.prev': 'Previous',
        'products.pagination.next': 'Next',
        'products.listing_quality.good': 'Good',
        'products.listing_quality.fair': 'Fair',
        'products.listing_quality.poor': 'Poor',
        'products.listing_quality.unknown': 'Unknown',

        // Fraud Alert
        'fraud.title': 'Fraud Alert Management',
        'fraud.subtitle': 'Monitor and manage fraud alerts for your shops',
        'fraud.total_alerts': 'Total Alerts',
        'fraud.bank_mismatches': 'Bank Mismatches',
        'fraud.no_bank_assigned': 'No Bank Assigned',
        'fraud.filters.shop_placeholder': 'Select shop to filter...',
        'fraud.filters.alert_type': 'Alert Type',
        'fraud.filters.alert_type.all': 'All Types',
        'fraud.filters.alert_type.mismatch': 'Bank Mismatch',
        'fraud.filters.alert_type.no_bank': 'No Bank Assigned',
        'fraud.filters.start_date': 'Start Date',
        'fraud.filters.end_date': 'End Date',
        'fraud.table.no': 'No.',
        'fraud.table.detected_date': 'Detected Date',
        'fraud.table.seller': 'Seller',
        'fraud.table.status': 'Status',
        'fraud.table.amount': 'Amount',
        'fraud.table.payment_id': 'Payment ID',
        'fraud.table.paid_date': 'Paid Date',
        'fraud.table.order_bank_account': 'Order Bank Account',
        'fraud.table.configured_bank_account': 'Configured Bank Account',
        'fraud.table.bank_created_date': 'Bank Created Date',
        'fraud.table.shop': 'Shop',
        'fraud.status.mismatch': 'Bank Mismatch',
        'fraud.status.no_bank_assigned': 'No Bank Assigned',
        'fraud.status.matched': 'Matched',
        'fraud.loading': 'Loading fraud alerts...',
        'fraud.error': 'Error loading fraud alerts',
        'fraud.no_results': 'No fraud alerts found',
        'fraud.fetch_error': 'Failed to fetch fraud alerts',

        // Common additions
        'common.clear': 'Clear',
    },
    vi: {
        // Navigation
        'nav.products': 'Sản phẩm',
        'nav.orders': 'Đơn hàng',
        'nav.bank': 'Quản lý bank',
        'nav.revenue': 'Tiền về',
        'nav.connect_shop': 'Kết nối Shop',
        'nav.chat': 'Trò chuyện',
        'nav.user_management': 'Quản lý user',
        'nav.shop_permissions': 'Phân quyền shop',
        'nav.dashboard': 'Bảng điều khiển',
        'nav.fraud_alert': 'Cảnh báo gian lận',
        'nav.organizations': 'Quản lý ứng dụng',

        // Dashboard
        'dashboard.title': 'Bảng điều khiển',
        'dashboard.subtitle': 'Tổng quan hệ thống quản lý TikTok Shop',
        'dashboard.active_shops': 'Shop hoạt động',
        'dashboard.total_orders': 'Tổng đơn hàng (30 ngày)',
        'dashboard.total_revenue': 'Tổng doanh thu (30 ngày)',
        'dashboard.system_health': 'Tình trạng hệ thống',
        'dashboard.pending_orders': 'Đơn chờ xử lý',
        'dashboard.total_payments': 'Tổng thanh toán',
        'dashboard.withdrawals': 'Rút tiền',
        'dashboard.pending_payments': 'Thanh toán chờ',
        'dashboard.recent_activity': 'Hoạt động gần đây',
        'dashboard.top_shops': 'Shop hiệu quả nhất',
        'dashboard.financial_overview': 'Tổng quan tài chính (30 ngày qua)',
        'dashboard.total_revenue_label': 'Tổng doanh thu',
        'dashboard.total_withdrawals_label': 'Tổng rút tiền',
        'dashboard.net_balance': 'Số dư ròng',
        'dashboard.excellent': 'Tuyệt vời',
        'dashboard.good': 'Tốt',
        'dashboard.needs_attention': 'Cần chú ý',
        'dashboard.no_issues': 'Không có vấn đề',
        'dashboard.alerts': 'cảnh báo',
        'dashboard.completed': 'hoàn thành',
        'dashboard.avg': 'Trung bình',
        'dashboard.need_fulfillment': 'Cần xử lý',
        'dashboard.last_30_days': '30 ngày qua',
        'dashboard.total_withdrawn': 'Tổng đã rút',
        'dashboard.need_processing': 'Cần xử lý',
        'dashboard.no_recent_activity': 'Không có hoạt động gần đây',
        'dashboard.no_shop_data': 'Chưa có dữ liệu hiệu quả shop',

        // Orders
        'orders.title': 'Quản lý đơn hàng',
        'orders.subtitle': 'Quản lý và đồng bộ đơn hàng TikTok',
        'orders.total_orders': 'Tổng đơn hàng',
        'orders.completed': 'Hoàn thành',
        'orders.processing': 'Đang xử lý',
        'orders.cancelled': 'Đã hủy',
        'orders.search': 'Tìm kiếm',
        'orders.search_placeholder': 'Tìm đơn hàng...',
        'orders.shop': 'Cửa hàng',
        'orders.all_shops': 'Tất cả shop',
        'orders.status': 'Trạng thái',
        'orders.all_status': 'Tất cả trạng thái',
        'orders.from_date': 'Từ ngày',
        'orders.to_date': 'Đến ngày',
        'orders.sync_orders': 'Đồng bộ đơn hàng',
        'orders.view_details': 'Xem chi tiết',
        'orders.chat_support': 'Hỗ trợ',
        'orders.account_seller': 'Tài khoản/Người bán',
        'orders.order': 'Đơn hàng',
        'orders.order_info': 'Thông tin đơn',
        'orders.price': 'Giá',
        'orders.actions': 'Thao tác',
        'orders.items': 'sản phẩm',
        'orders.track': 'Theo dõi',
        'orders.subtotal': 'Tạm tính',

        // Chat
        'chat.title': 'Trò chuyện khách hàng',
        'chat.shops_messages': 'shop • {unread} tin nhắn chưa đọc',
        'chat.refresh': 'Làm mới',
        'chat.seed_data': 'Tạo dữ liệu mẫu',
        'chat.clear_data': 'Xóa dữ liệu mẫu',
        'chat.search_placeholder': 'Tìm shop hoặc khách hàng...',
        'chat.loading_conversations': 'Đang tải cuộc trò chuyện...',
        'chat.no_conversations': 'Không tìm thấy cuộc trò chuyện',
        'chat.conversations': 'cuộc trò chuyện',
        'chat.participants': 'người tham gia',
        'chat.cannot_send': 'Không thể gửi tin nhắn',
        'chat.loading_messages': 'Đang tải tin nhắn...',
        'chat.no_messages': 'Chưa có tin nhắn trong cuộc trò chuyện',
        'chat.select_conversation': 'Chọn cuộc trò chuyện',
        'chat.select_conversation_desc': 'Chọn cuộc trò chuyện từ thanh bên để xem tin nhắn',
        'chat.readonly_notice': 'Đây là chế độ chỉ đọc. Sử dụng TikTok Shop Seller Center để trả lời tin nhắn.',
        'chat.unknown_customer': 'Khách hàng không xác định',

        // Common
        'common.loading': 'Đang tải...',
        'common.search': 'Tìm kiếm',
        'common.refresh': 'Làm mới',
        'common.save': 'Lưu',
        'common.cancel': 'Hủy',
        'common.delete': 'Xóa',
        'common.edit': 'Sửa',
        'common.view': 'Xem',
        'common.actions': 'Thao tác',
        'common.status': 'Trạng thái',
        'common.date': 'Ngày',
        'common.total': 'Tổng',
        'common.yes': 'Có',
        'common.no': 'Không',
        'common.close': 'Đóng',
        'common.confirm': 'Xác nhận',
        // ===== Added keys =====
        'bank.description': 'Quản lý tài khoản ngân hàng và gán cho shop',
        'bank.import_bank': 'Import Bank',
        'bank.download_template': 'Tải mẫu CSV',
        'bank.history': 'Lịch sử hành động',
        'bank.search_placeholder': 'Tìm Account number, Routing number, Swift code...',
        'bank.search_results': 'Tìm thấy {total} tài khoản ngân hàng',
        'bank.clear': 'Xóa',
        'bank.info': 'Thông tin Bank',
        'bank.upload_date': 'Ngày upload',
        'bank.uploader': 'Người upload',
        'bank.status': 'Tình trạng',
        'bank.shop': 'Shop',
        'bank.setup_date': 'Ngày set up',
        'bank.assigned_staff': 'Nhân sự',
        'bank.actions': 'Hành động',
        'bank.used': 'Đã dùng',
        'bank.unused': 'Chưa dùng',
        'bank.no_results_with_search': 'Không có tài khoản trùng với "{search}". Thử từ khóa khác.',
        'bank.no_banks': 'Chưa có tài khoản ngân hàng. Bắt đầu bằng cách import.',
        'bank.pagination.showing': 'Hiển thị',
        'bank.pagination.to': 'đến',
        'bank.pagination.of': 'của',
        'bank.pagination.accounts': 'tài khoản',
        'bank.previous': 'Trước',
        'bank.next': 'Tiếp theo',
        'bank.page': 'Trang',
        // Import Bank Modal
        'bank.import.title': 'Import Bank',
        'bank.import.csv_format_title': 'Định dạng CSV yêu cầu:',
        'bank.import.note_description': 'Note: Ghi chú hoặc tên chủ tài khoản',
        'bank.import.bank_name_description': 'Bank Name: Tên ngân hàng đầy đủ',
        'bank.import.routing_number_description': 'Routing Number: Số định tuyến',
        'bank.import.swift_code_description': 'Swift Code: Mã SWIFT quốc tế',
        'bank.import.account_number_description': 'Account Number: Đầy đủ (không dạng khoa học)',
        'bank.import.type_description': 'Type: Loại tài khoản (Checking, Savings...)',
        'bank.import.download_template': 'Tải file mẫu CSV',
        'bank.import.download_excel': 'Tải mẫu Excel/CSV',
        'bank.import.drop_or_click': 'Kéo thả file CSV hoặc nhấp để chọn',
        'bank.import.drop_active': 'Thả file vào đây...',
        'bank.import.upload_file': 'Import file',
        'bank.import.number_format_warning_title': '⚠️ Lưu ý định dạng số:',
        'bank.import.number_format_warning_1': 'Account Number & Routing Number phải hiển thị đầy đủ',
        'bank.import.number_format_warning_2': 'Không rút gọn dạng 1.55E+14',
        'bank.import.number_format_warning_3': 'Trong Excel: Format cells → Number → 0 decimal',
        'bank.import.number_format_warning_4': "Hoặc thêm dấu ' để thành dạng text",
        'bank.import.number_format_warning_5': 'Kiểm tra kỹ trước khi xác nhận - không thể sửa',
        'bank.import.review_title': 'Kiểm tra trước khi import',
        'bank.import.file': 'File',
        'bank.import.accounts_count': '{count} tài khoản',
        'bank.import.confirm': '✅ Xác nhận Import ({count} tài khoản)',
        'bank.import.reupload': '🔄 Upload lại file',
        // Edit Managed Name Modal
        'shop.edit_managed_name.title': 'Cập nhật tên quản lý',
        'shop.edit_managed_name.current_shop': 'Shop hiện tại:',
        'shop.edit_managed_name.tiktok_name': 'TikTok Name:',
        'shop.edit_managed_name.shop_id': 'Shop ID:',
        'shop.edit_managed_name.new_label': 'Tên quản lý mới',
        'shop.edit_managed_name.placeholder': 'Nhập tên quản lý...',
        'shop.edit_managed_name.helper': 'Giúp bạn nhận diện shop (2-50 ký tự)',
        'shop.edit_managed_name.min_error': 'Tên quản lý phải ít nhất 2 ký tự',
        'common.characters_count': '{count}/50',
        'common.saving': 'Đang lưu...',
        'common.save_changes': 'Lưu thay đổi',
    'shops.actions.manage_access': 'Quản lý quyền truy cập',
    'shops.actions.assign_group': 'Gán vào nhóm',
    'shops.assign_modal.title': 'Quản lý quyền truy cập cho {shop}',
    'shops.assign_modal.group_label': 'Quyền theo nhóm',
    'shops.assign_modal.select_group': 'Chọn nhóm',
    'shops.assign_modal.unassigned': 'Chưa gán nhóm',
    'shops.assign_modal.save_group': 'Cập nhật nhóm',
    'shops.assign_modal.group_help': 'Gán shop vào nhóm để kế thừa quyền của người quản lý.',
    'shops.assign_modal.load_failed': 'Không thể tải danh sách nhóm',
    'shops.assign_modal.save_failed': 'Không thể cập nhật nhóm cho shop',
    'shops.assign_modal.success': 'Cập nhật nhóm cho shop thành công',
    'shops.assign_modal.user_label': 'Quyền trực tiếp',
    'shops.assign_modal.select_user': 'Chọn người dùng',
    'shops.assign_modal.select_role': 'Chọn vai trò',
    'shops.assign_modal.add_user': 'Thêm người dùng',
    'shops.assign_modal.current_access': 'Người dùng hiện tại',
    'shops.assign_modal.remove_user': 'Gỡ',
    'shops.group_label': 'Nhóm',
    'shops.no_group': 'Chưa có nhóm',
    'shops.no_users': 'Chưa có người dùng trực tiếp',
    'shopGroups.title': 'Nhóm Shop',
    'shopGroups.subtitle': 'Quản lý shop theo từng nhóm quản lý',
    'shopGroups.total_shops': '{count} shop',
    'shopGroups.manager': 'Quản lý',
    'shopGroups.members': 'Thành viên',
    'shopGroups.add_shop': 'Thêm shop',
    'shopGroups.remove_shop': 'Gỡ',
    'shopGroups.current_shops': 'Shop trong nhóm',
    'shopGroups.no_shops': 'Nhóm chưa có shop nào',
    'shopGroups.no_groups': 'Chưa có nhóm nào',
    'shopGroups.refresh': 'Làm mới',
    'shopGroups.assign_modal.title': 'Thêm shop vào {group}',
    'shopGroups.assign_modal.select_shop': 'Chọn shop',
    'shopGroups.assign_modal.submit': 'Thêm shop',
    'shopGroups.assign_modal.submitting': 'Đang thêm...',
    'shopGroups.unassigned': 'Chưa gán',
        // Permissions
        'permissions.title': 'Phân quyền cửa hàng',
        'permissions.subtitle': 'Quản lý quyền truy cập người dùng trên tất cả shop',
    'permissions.add_user_to_shop': 'Thêm người dùng vào cửa hàng',
    'permissions.add_user_with_group': 'Thêm người dùng qua nhóm',
        'permissions.search_placeholder': 'Tìm kiếm người dùng hoặc cửa hàng...',
        'permissions.all_shops': 'Tất cả cửa hàng',
        'permissions.clear': 'Xóa',
        'permissions.results_found': 'Tìm thấy {total} quyền',
        'permissions.search_results': 'Kết quả tìm kiếm',
        'permissions.user_access': 'Quyền truy cập của người dùng',
        'permissions.items_per_page': 'mục mỗi trang',
        'permissions.showing_range': 'Hiển thị {from} đến {to} của {total} mục',
        'permissions.table.user': 'Người dùng',
        'permissions.table.shop': 'Cửa hàng',
        'permissions.table.role': 'Quyền',
        'permissions.table.assigned_date': 'Ngày phân công',
        'permissions.table.actions': 'Thao tác',
        'permissions.no_search_results': 'Không có quyền nào khớp tiêu chí tìm kiếm.',
        'permissions.no_permissions': 'Chưa có quyền. Thêm người dùng vào cửa hàng để bắt đầu.',
        'permissions.edit': 'Sửa',
        'permissions.delete': 'Xóa',
        'permissions.assign_modal.title': 'Phân quyền người dùng vào cửa hàng',
        'permissions.assign_modal.user': 'Người dùng',
        'permissions.assign_modal.select_user': 'Chọn người dùng',
        'permissions.assign_modal.shop': 'Cửa hàng',
        'permissions.assign_modal.select_shop': 'Chọn cửa hàng',
        'permissions.assign_modal.role_permissions': 'Vai trò & quyền hạn',
        'permissions.role.owner.label': 'Owner - Chủ sở hữu',
        'permissions.role.owner.desc': 'Toàn quyền hệ thống',
        'permissions.role.resource.label': 'Resource - Quản lý Tài nguyên',
        'permissions.role.resource.desc': 'Kết nối & quản lý shop (không được xóa shop)',
        'permissions.role.accountant.label': 'Accountant - Kế toán',
        'permissions.role.accountant.desc': 'Quản lý tài chính, đối soát, báo cáo, đơn hàng',
        'permissions.role.seller.label': 'Seller - Nhân viên bán hàng',
        'permissions.role.seller.desc': 'Quản lý sản phẩm, đơn hàng, khuyến mãi',
        'permissions.cancel': 'Hủy',
    'permissions.assign': 'Phân quyền',
    'permissions.assigning': 'Đang phân quyền...',
    'permissions.assign_with_group.title': 'Phân quyền người dùng theo nhóm',
    'permissions.assign_with_group.user': 'Người dùng',
    'permissions.assign_with_group.group': 'Nhóm',
    'permissions.assign_with_group.group_optional_hint': 'Tùy chọn – chọn nhóm để kế thừa quyền quản lý',
    'permissions.assign_with_group.no_groups': 'Chưa có nhóm khả dụng',
    'permissions.assign_with_group.shop': 'Cửa hàng',
    'permissions.assign_with_group.no_shops': 'Nhóm này chưa có cửa hàng',
    'permissions.assign_with_group.role': 'Vai trò',
    'permissions.assign_with_group.submit': 'Phân quyền',
    'permissions.assign_with_group.submitting': 'Đang phân quyền...',
    'permissions.assign_with_group.success': 'Phân quyền thành công.',
    'permissions.assign_with_group.error_generic': 'Không thể phân quyền. Vui lòng thử lại.',
    'permissions.groups.title': 'Nhóm cửa hàng',
    'permissions.groups.subtitle': 'Quản lý nhóm cửa hàng và thành viên chia sẻ quyền truy cập',
    'permissions.groups.table.group': 'Nhóm',
    'permissions.groups.table.manager': 'Quản lý',
    'permissions.groups.table.members': 'Thành viên',
    'permissions.groups.table.shops': 'Cửa hàng',
    'permissions.groups.no_groups': 'Chưa có nhóm nào. Tạo nhóm từ trang cửa hàng để bắt đầu.',
    'permissions.groups.no_members': 'Chưa có thành viên',
    'permissions.groups.no_shops': 'Chưa có cửa hàng',
    'permissions.groups.more_members': '+{count} thành viên khác',
    'permissions.groups.more_shops': '+{count} cửa hàng khác',
    'permissions.groups.shop_count_summary': '{count} cửa hàng',
    'permissions.groups.load_failed': 'Không thể tải danh sách nhóm cửa hàng',
    'permissions.groups.create_button': 'Tạo nhóm',
    'permissions.groups.create_modal.title': 'Tạo nhóm cửa hàng',
    'permissions.groups.create_modal.description': 'Tạo nhóm để chia sẻ quyền truy cập cửa hàng cho nhiều thành viên.',
    'permissions.groups.create_modal.name_label': 'Tên nhóm',
    'permissions.groups.create_modal.name_placeholder': 'Nhập tên nhóm',
    'permissions.groups.create_modal.name_required': 'Vui lòng nhập tên nhóm',
    'permissions.groups.create_modal.manager_label': 'Quản lý nhóm',
    'permissions.groups.create_modal.manager_placeholder': 'Chọn quản lý',
    'permissions.groups.create_modal.manager_required': 'Vui lòng chọn quản lý nhóm',
    'permissions.groups.create_modal.no_users': 'Chưa có người dùng nào. Hãy tạo người dùng trước khi tạo nhóm.',
    'permissions.groups.create_modal.members_label': 'Thành viên thêm',
    'permissions.groups.create_modal.members_placeholder': 'Tìm và chọn thành viên…',
    'permissions.groups.create_modal.no_other_users': 'Không còn người dùng nào khác để thêm.',
    'permissions.groups.create_modal.members_hint': 'Tùy chọn – thêm thành viên để cùng kế thừa quyền truy cập nhóm.',
    'permissions.groups.create_modal.description_label': 'Mô tả',
    'permissions.groups.create_modal.description_placeholder': 'Thêm ghi chú cho nhóm (không bắt buộc)',
    'permissions.groups.create_modal.submit': 'Tạo nhóm',
    'permissions.groups.create_modal.loading': 'Đang tạo...',
    'permissions.groups.create_modal.success': 'Tạo nhóm thành công',
    'permissions.groups.create_modal.error': 'Không thể tạo nhóm',
    'permissions.groups.add_user': 'Thêm thành viên',
    'permissions.groups.add_shop': 'Thêm cửa hàng',
    'permissions.groups.add_user_success': 'Đã thêm người dùng vào nhóm thành công',
    'permissions.groups.add_user_error': 'Không thể thêm người dùng vào nhóm',
    'permissions.groups.add_shop_success': 'Đã gán {count} cửa hàng vào nhóm thành công',
    'permissions.groups.add_shop_error': 'Không thể gán cửa hàng vào nhóm',
    'permissions.groups.add_user_modal.title': 'Thêm thành viên vào nhóm',
    'permissions.groups.add_user_modal.description': 'Chọn người dùng để tham gia "{group}".',
    'permissions.groups.add_user_modal.user_label': 'Người dùng',
    'permissions.groups.add_user_modal.user_placeholder': 'Tìm và chọn người dùng…',
    'permissions.groups.add_user_modal.no_users': 'Tất cả người dùng đủ điều kiện đều đã ở trong nhóm này.',
    'permissions.groups.add_user_modal.no_options': 'Không tìm thấy người dùng phù hợp.',
    'permissions.groups.add_user_modal.no_selection': 'Vui lòng chọn ít nhất một người dùng.',
    'permissions.groups.add_user_modal.shop_label': 'Cửa hàng cấp quyền',
    'permissions.groups.add_user_modal.shop_helper': 'Thành viên sẽ được cấp quyền với vai trò bán hàng tại các cửa hàng đã chọn. Họ phải thuộc nhóm này.',
    'permissions.groups.add_user_modal.no_shops': 'Nhóm này chưa có cửa hàng nào.',
    'permissions.groups.add_user_modal.shops_placeholder': 'Tìm cửa hàng trong nhóm...',
    'permissions.groups.add_user_modal.shops_no_options': 'Không tìm thấy cửa hàng phù hợp.',
    'permissions.groups.add_user_modal.submit': 'Thêm thành viên',
    'permissions.groups.add_user_modal.loading': 'Đang thêm...',
    'permissions.groups.add_shop_modal.title': 'Thêm nhiều cửa hàng vào nhóm',
    'permissions.groups.add_shop_modal.description': 'Chọn một hoặc nhiều cửa hàng để gán vào "{group}".',
    'permissions.groups.add_shop_modal.shop_label': 'Cửa hàng',
    'permissions.groups.add_shop_modal.placeholder': 'Tìm và chọn cửa hàng…',
    'permissions.groups.add_shop_modal.no_shops': 'Không còn cửa hàng nào để gán.',
    'permissions.groups.add_shop_modal.no_options': 'Không tìm thấy cửa hàng phù hợp.',
    'permissions.groups.add_shop_modal.no_selection': 'Vui lòng chọn ít nhất một cửa hàng.',
    'permissions.groups.add_shop_modal.submit': 'Thêm cửa hàng',
    'permissions.groups.add_shop_modal.loading': 'Đang gán...',
    'permissions.groups.add_shop_modal.current_group_label': 'Nhóm hiện tại:',
    'permissions.groups.add_shop_modal.helper': 'Gõ để tìm kiếm và nhấp để thêm nhiều cửa hàng. Nhấn Backspace để bỏ chọn.',
    'permissions.groups.manage_members.title': 'Thành viên hiện tại',
    'permissions.groups.manage_members.no_members': 'Nhóm này chưa có thành viên nào.',
    'permissions.groups.manage_members.remove': 'Xóa khỏi nhóm',
    'permissions.groups.manage_members.default_badge': 'Mặc định',
    'permissions.groups.manage_members.cannot_remove_default': 'Không thể xóa thành viên mặc định.',
    'permissions.groups.remove_user_confirm': 'Xóa {name} khỏi nhóm này?',
    'permissions.groups.remove_user_success': '{name} đã được xóa khỏi nhóm.',
    'permissions.groups.remove_user_error': 'Không thể xóa thành viên khỏi nhóm. Vui lòng thử lại.',
    'permissions.groups.remove_user_cascade_warning': 'Đã xóa {name} khỏi nhóm nhưng không thể thu hồi quyền ở các cửa hàng: {shops}. Vui lòng kiểm tra lại quyền truy cập.',
    'permissions.groups.add_user_grant_warning': 'Đã thêm thành viên nhưng không thể cấp quyền cho {shops} cửa hàng. Vui lòng kiểm tra lại quyền truy cập.',
    'permissions.groups.unknown_user': 'Chưa rõ người dùng',
        'permissions.edit_modal.title': 'Cập nhật quyền người dùng',
        'permissions.edit_modal.choose_new_role': 'Chọn vai trò mới',
        'permissions.updating': 'Đang cập nhật...',
        'permissions.update_role': 'Cập nhật quyền',
        'permissions.previous': 'Trước',
        'permissions.next': 'Tiếp theo',
        'permissions.page': 'Trang',
        // Orders additions
        'orders.sync_unsettled_transactions': 'Sync Unsettled Transaction',
        'orders.in_progress': 'Đang xử lý',
        'orders.search_placeholder_full': 'Tìm đơn theo ID, email, tên người nhận hoặc sản phẩm...',
        'orders.items_images': 'Hình ảnh SP',
        'orders.customer_info': 'Thông tin KH',
        'orders.sync_detail': 'Sync Detail',
        'orders.add_tracking': 'Thêm tracking',
        'orders.split_orders': 'Split orders',
        'orders.view': 'Xem',
    'orders.view_tracking': 'Xem hành trình',
    'orders.tracking_modal.title': 'Lịch sử vận chuyển',
    'orders.tracking_modal.subtitle': 'Các cập nhật mới nhất từ đơn vị vận chuyển.',
    'orders.tracking_modal.updated_at': 'Thời gian',
    'orders.tracking_modal.description': 'Mô tả',
    'orders.tracking_modal.empty': 'Chưa có dữ liệu vận chuyển.',
    'orders.tracking_load_failed': 'Không thể tải thông tin vận chuyển',
        'orders.no_orders_found': 'Không có đơn hàng với bộ lọc hiện tại.',
        'orders.mark_delivered': 'Kéo đơn',
        'orders.splitted': 'Đã split order',
        'orders.items_label': ' sản phẩm',
        'orders.track_label': 'Track: ',
        // Alerts & SLA
        'orders.alert.ship_within_24h': 'Cần giao trong 24h',
        'orders.alert.auto_cancelling_24h': 'Sắp tự hủy <24h',
        'orders.alert.shipping_overdue': 'Quá hạn giao hàng',
        'orders.alert.cancellation_requested': 'Khách yêu cầu hủy',
        'orders.alert.logistics_issue': 'Vấn đề vận chuyển',
        'orders.alert.return_refund': 'Hoàn/Trả hàng',
        'orders.sla_column': 'SLA / Hạn xử lý',
        'orders.sla.ship_due': 'Hạn tạo vận đơn',
        'orders.sla.collection_due': 'Hạn lấy hàng',
        'orders.sla.delivery_due': 'Hạn giao',
        'orders.sla.cancel_sla': 'Hạn auto hủy',
        'orders.sla.tts_sla': 'TTS SLA',
        'orders.sla.rts_sla': 'RTS SLA',
        'orders.sla.delivery_sla': 'SLA giao',
        'orders.sla.fast_dispatch': 'Nhanh',
        'orders.sla.pickup_cutoff': 'Cutoff lấy',
        'orders.sla.req_delivery': 'Yêu cầu giao',
        'orders.sla.rts_at': 'RTS lúc',
        'orders.sla.collected_at': 'Lấy lúc',
        'orders.sla.cancelled_at': 'Hủy lúc',
        'orders.sla.req_cancel_at': 'Y/c hủy lúc',
        'orders.sla.release_date': 'Ngày phát hành',
        // SLA descriptions (VI)
        'orders.sla.desc.rts_sla': 'rts_sla_time: Thời hạn cuối cùng phải giao (RTS) do nền tảng quy định. ',
        'orders.sla.desc.tts_sla': 'tts_sla_time: Thời điểm hệ thống tự hủy đơn nếu chưa xử lý. ',
        'orders.sla.desc.delivery_sla': 'delivery_sla_time: Đơn phải được giao trước thời điểm này để không bị phạt giao trễ.',
        'orders.sla.desc.ship_due': 'shipping_due_time: Hạn cuối tạo/xác nhận vận đơn trước khi vi phạm.',
        'orders.sla.desc.collection_due': 'collection_due_time: Thời hạn cuối cùng đơn vị vận chuyển phải qua lấy hàng.',
        'orders.sla.desc.delivery_due': 'delivery_due_time: Thời điểm dự kiến giao (mốc tham chiếu mềm).',
        'orders.sla.desc.cancel_sla': 'cancel_order_sla_time: Thời điểm hệ thống tự hủy nếu chưa xử lý.',
        'orders.sla.desc.fast_dispatch': 'fast_dispatch_sla_time: SLA dành cho đơn giao nhanh.',
        'orders.sla.desc.pickup_cutoff': 'pick_up_cut_off_time: Giới hạn thời gian gửi yêu cầu lấy hàng.',
        'orders.sla.desc.req_delivery': 'delivery_option_required_delivery_time: Thời gian giao bắt buộc theo tùy chọn đã chọn.',
        'orders.sla.desc.events.generic': 'Mốc sự kiện ghi nhận từ vòng đời logistics.',

        // Common (missing)
        'common.previous': 'Trước',
        'common.next': 'Tiếp theo',
        'common.id': 'ID',
        'common.na': 'N/A',
        'common.showing_results': 'Hiển thị {from} đến {to} của {total} kết quả',
        'common.page_of': 'Trang {current} / {total}',

        // Orders runtime/status (missing)
        'orders.loading_orders': 'Đang tải đơn hàng...',
        'orders.searching_orders': 'Đang tìm kiếm đơn hàng...',
        'orders.syncing_orders': 'Đang đồng bộ đơn hàng...',
        'orders.syncing_unsettled_transactions': 'Đang đồng bộ giao dịch chưa quyết toán...',
        'orders.loading_order_details': 'Đang tải chi tiết đơn hàng...',
        'orders.splitting_order': 'Đang tách đơn...',
        'orders.refreshing': 'Đang làm mới...',
        'orders.sync_success': 'Đồng bộ đơn hàng thành công',
        'orders.sync_failed': 'Đồng bộ thất bại',
        'orders.select_shop_sync_unsettled': 'Vui lòng chọn shop để đồng bộ giao dịch chưa quyết toán',
        'orders.unsettled_sync_success': 'Đồng bộ giao dịch chưa quyết toán thành công',
        'orders.load_detail_failed': 'Tải chi tiết đơn hàng thất bại',
        'orders.sync_detail_success': 'Đã sync chi tiết cho {orderId}',
        'orders.sync_detail_failed': 'Sync chi tiết thất bại',

        // Orders labels (missing)
        'orders.order_status_label': 'Trạng thái đơn',
        'orders.custom_status': 'Trạng thái nội bộ',
        'orders.page_size': 'Số dòng / trang',
        'orders.status_flow': 'Luồng trạng thái đơn:',
        'orders.shop_id_label': 'Shop ID:',
        'orders.copy_customer_info': 'Sao chép thông tin khách hàng',
        'orders.mark_as_delivered_title': 'Đánh dấu đã kéo đơn',
        'orders.add_tracking_title': 'Thêm thông tin tracking',
        'orders.split_order_title': 'Tách đơn thành nhiều kiện',
        'orders.subtotal_label': 'Tạm tính:',
        'orders.estimated_label': 'Est:',
        "orders.split_failed": "Tách đơn thất bại",
        'orders.split_success': 'Tách đơn thành công',

        // Products Page (VI)
        'products.title': 'Quản lý Sản phẩm',
        'products.subtitle': 'Quản lý, tìm kiếm & đồng bộ sản phẩm TikTok hiệu quả.',
        'products.bulk_sync': 'Đồng bộ hàng loạt',
        'products.export': 'Xuất',
        'products.exporting': 'Đang xuất...',
        'products.refresh': 'Làm mới',
        'products.show_filters': 'Hiện bộ lọc',
        'products.hide_filters': 'Ẩn bộ lọc',
        'products.stats.total': 'Tổng',
        'products.stats.active': 'Hoạt động',
        'products.stats.seller_deactivated': 'Người bán khóa',
        'products.stats.platform_deactivated': 'Nền tảng khóa',
        'products.search_placeholder': 'Tìm kiếm theo tên sản phẩm, ID, SKU, mô tả...',
        'products.clear': 'Xóa',
        'products.filter.shop': 'Cửa hàng',
        'products.filter.status': 'Trạng thái',
        'products.filter.listing_quality': 'Chất lượng listing',
        'products.filter.from_date': 'Từ ngày',
        'products.filter.to_date': 'Đến ngày',
        'products.table.images': 'Ảnh',
        'products.table.info': 'Thông tin sản phẩm',
        'products.table.listing_quality': 'Chất lượng',
        'products.table.price': 'Giá bán',
        'products.table.status': 'Trạng thái',
        'products.table.created_at': 'Ngày tạo',
        'products.table.updated_at': 'Cập nhật',
        'products.table.actions': 'Hành động',
    'products.table.shop': 'Cửa hàng',
    'products.table.timestamps': 'Thời gian',
        'products.actions.view': 'Xem',
        'products.actions.copy_id': 'Mã',
        'products.actions.sync': 'Đồng bộ',
        'products.no_results': 'Không tìm thấy sản phẩm nào với bộ lọc hiện tại.',
        'products.loading': 'Đang tải sản phẩm...',
        'products.searching': 'Đang tìm kiếm sản phẩm...',
        'products.sync.loading_single': 'Đang đồng bộ sản phẩm...',
        'products.sync.success_single': 'Đồng bộ sản phẩm thành công',
        'products.sync.failed_single': 'Đồng bộ thất bại',
        'products.export.success': 'Xuất Excel thành công',
        'products.export.failed': 'Xuất Excel thất bại',
        'products.export.empty': 'Không có sản phẩm để xuất',
        'products.copy.success': 'Đã sao chép',
    'products.detail.title': 'Chi tiết sản phẩm',
    'products.detail.subtitle': 'Dữ liệu sản phẩm đầy đủ',
    'products.detail.section.media': 'Hình ảnh',
    'products.detail.section.core': 'Thuộc tính chính',
    'products.detail.section.pricing': 'SKU & Giá',
    'products.detail.section.metrics': 'Chất lượng & Chỉ số',
    'products.detail.section.identifiers': 'Định danh',
    'products.detail.section.description': 'Mô tả',
    'products.detail.no_skus': 'Không có SKU',
    'products.detail.close': 'Đóng',
        'products.pagination.rows_per_page': 'Số hàng mỗi trang:',
        'products.pagination.range': 'Hiển thị {from}-{to} trên tổng {total}',
        'products.pagination.prev': 'Trước',
        'products.pagination.next': 'Sau',
        'products.listing_quality.good': 'Tốt',
        'products.listing_quality.fair': 'Khá',
        'products.listing_quality.poor': 'Kém',
        'products.listing_quality.unknown': 'Không rõ',

        // Fraud Alert
        'fraud.title': 'Quản lý Cảnh báo Gian lận',
        'fraud.subtitle': 'Giám sát và quản lý các cảnh báo gian lận cho các shop của bạn',
        'fraud.total_alerts': 'Tổng Cảnh báo',
        'fraud.bank_mismatches': 'Lỗi Ngân hàng Không khớp',
        'fraud.no_bank_assigned': 'Chưa Gán Ngân hàng',
        'fraud.filters.shop_placeholder': 'Chọn shop để lọc...',
        'fraud.filters.alert_type': 'Loại Cảnh báo',
        'fraud.filters.alert_type.all': 'Tất cả Loại',
        'fraud.filters.alert_type.mismatch': 'Ngân hàng Không khớp',
        'fraud.filters.alert_type.no_bank': 'Chưa Gán Ngân hàng',
        'fraud.filters.start_date': 'Ngày Bắt đầu',
        'fraud.filters.end_date': 'Ngày Kết thúc',
        'fraud.table.no': 'STT',
        'fraud.table.detected_date': 'Ngày Phát hiện',
        'fraud.table.seller': 'Người bán',
        'fraud.table.status': 'Trạng thái',
        'fraud.table.amount': 'Số tiền',
        'fraud.table.payment_id': 'Mã Thanh toán',
        'fraud.table.paid_date': 'Ngày Thanh toán',
        'fraud.table.order_bank_account': 'TK Ngân hàng Đơn hàng',
        'fraud.table.configured_bank_account': 'TK Ngân hàng Cấu hình',
        'fraud.table.bank_created_date': 'Ngày Tạo Ngân hàng',
        'fraud.table.shop': 'Shop',
        'fraud.status.mismatch': 'Ngân hàng Không khớp',
        'fraud.status.no_bank_assigned': 'Chưa Gán Ngân hàng',
        'fraud.status.matched': 'Khớp',
        'fraud.loading': 'Đang tải cảnh báo gian lận...',
        'fraud.error': 'Lỗi tải cảnh báo gian lận',
        'fraud.no_results': 'Không tìm thấy cảnh báo gian lận nào',
        'fraud.fetch_error': 'Không thể tải cảnh báo gian lận',

        // Common additions
        'common.clear': 'Xóa',
    }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const [language, setLanguageState] = useState<Language>('vi');

    useEffect(() => {
        // Load saved language from localStorage
        const savedLanguage = localStorage.getItem('language') as Language;
        if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'vi')) {
            setLanguageState(savedLanguage);
        }
    }, []);

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
        localStorage.setItem('language', lang);
    };

    const t = (key: string, params?: Record<string, string | number>) => {
        let translation = translations[language][key] || translations['en'][key] || key;

        // Replace parameters in translation
        if (params) {
            Object.entries(params).forEach(([paramKey, value]) => {
                translation = translation.replace(`{${paramKey}}`, String(value));
            });
        }

        return translation;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
