/*
 * Amazon Shipping API
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * OpenAPI spec version: v2
 * Contact: swa-api-core@amazon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';
import {AccountId} from './AccountId.js';
import {CarrierId} from './CarrierId.js';

/**
 * The CarrierAccount model module.
 * @module shippingV2/js-client.shippingV2.model/CarrierAccount
 * @version v2
 */
export class CarrierAccount {
  /**
   * Constructs a new <code>CarrierAccount</code>.
   * Carrier Account details used to fetch rates.
   * @alias module:shippingV2/js-client.shippingV2.model/CarrierAccount
   * @class
   * @param carrierAccountId {module:shippingV2/js-client.shippingV2.model/AccountId} 
   * @param carrierId {module:shippingV2/js-client.shippingV2.model/CarrierId} 
   */
  constructor(carrierAccountId, carrierId) {
    this.carrierAccountId = carrierAccountId;
    this.carrierId = carrierId;
  }

  /**
   * Constructs a <code>CarrierAccount</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:shippingV2/js-client.shippingV2.model/CarrierAccount} obj Optional instance to populate.
   * @return {module:shippingV2/js-client.shippingV2.model/CarrierAccount} The populated <code>CarrierAccount</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      switch(typeof data) {
        case 'string':
          obj = String(data);
          break;
        case 'number':
          obj = Number(data);
          break;
        case 'boolean':
          obj = Boolean(data);
          break;
      }
      obj = obj || new CarrierAccount();
      if (data.hasOwnProperty('carrierAccountId'))
        obj.carrierAccountId = AccountId.constructFromObject(data['carrierAccountId']);
      if (data.hasOwnProperty('carrierId'))
        obj.carrierId = CarrierId.constructFromObject(data['carrierId']);
    }
    return obj;
  }
}

/**
 * @member {module:shippingV2/js-client.shippingV2.model/AccountId} carrierAccountId
 */
CarrierAccount.prototype.carrierAccountId = undefined;

/**
 * @member {module:shippingV2/js-client.shippingV2.model/CarrierId} carrierId
 */
CarrierAccount.prototype.carrierId = undefined;


