/*
 * Amazon Shipping API
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * OpenAPI spec version: v2
 * Contact: swa-api-core@amazon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';

/**
 * Enum class ClaimReason.
 * @enum {String}
 * @readonly
 */
const ClaimReason = {
  /**
   * value: "LOST_IN_TRANSIT"
   * @const
   */
  LOST_IN_TRANSIT: "LOST_IN_TRANSIT",

  /**
   * value: "DAMAGED_IN_TRANSIT"
   * @const
   */
  DAMAGED_IN_TRANSIT: "DAMAGED_IN_TRANSIT",

  /**
   * value: "DELIVERED_NOT_RECEIVED"
   * @const
   */
  DELIVERED_NOT_RECEIVED: "DELIVERED_NOT_RECEIVED",

  /**
   * value: "ITEM_MISSING_SWITCHEROO"
   * @const
   */
  ITEM_MISSING_SWITCHEROO: "ITEM_MISSING_SWITCHEROO",

  /**
   * value: "COD_ABUSE"
   * @const
   */
  COD_ABUSE: "COD_ABUSE",

  /**
   * Returns a <code>ClaimReason</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
   * @return {module:shippingV2/js-client.shippingV2.model/ClaimReason} The enum <code>ClaimReason</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {ClaimReason};
