/*
 * Amazon Shipping API
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * OpenAPI spec version: v2
 * Contact: swa-api-core@amazon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';
import {ClaimProofURLs} from './ClaimProofURLs.js';
import {ClaimReason} from './ClaimReason.js';
import {Currency} from './Currency.js';
import {SettlementType} from './SettlementType.js';
import {TrackingId} from './TrackingId.js';

/**
 * The CreateClaimRequest model module.
 * @module shippingV2/js-client.shippingV2.model/CreateClaimRequest
 * @version v2
 */
export class CreateClaimRequest {
  /**
   * Constructs a new <code>CreateClaimRequest</code>.
   * The request schema for the CreateClaim operation
   * @alias module:shippingV2/js-client.shippingV2.model/CreateClaimRequest
   * @class
   * @param trackingId {module:shippingV2/js-client.shippingV2.model/TrackingId} 
   * @param claimReason {module:shippingV2/js-client.shippingV2.model/ClaimReason} 
   * @param settlementType {module:shippingV2/js-client.shippingV2.model/SettlementType} 
   */
  constructor(trackingId, claimReason, settlementType) {
    this.trackingId = trackingId;
    this.claimReason = claimReason;
    this.settlementType = settlementType;
  }

  /**
   * Constructs a <code>CreateClaimRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:shippingV2/js-client.shippingV2.model/CreateClaimRequest} obj Optional instance to populate.
   * @return {module:shippingV2/js-client.shippingV2.model/CreateClaimRequest} The populated <code>CreateClaimRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      switch(typeof data) {
        case 'string':
          obj = String(data);
          break;
        case 'number':
          obj = Number(data);
          break;
        case 'boolean':
          obj = Boolean(data);
          break;
      }
      obj = obj || new CreateClaimRequest();
      if (data.hasOwnProperty('trackingId'))
        obj.trackingId = TrackingId.constructFromObject(data['trackingId']);
      if (data.hasOwnProperty('declaredValue'))
        obj.declaredValue = Currency.constructFromObject(data['declaredValue']);
      if (data.hasOwnProperty('claimReason'))
        obj.claimReason = ClaimReason.constructFromObject(data['claimReason']);
      if (data.hasOwnProperty('isReplacementPackageSent'))
        obj.isReplacementPackageSent = ApiClient.convertToType(data['isReplacementPackageSent'], 'Boolean');
      if (data.hasOwnProperty('proofs'))
        obj.proofs = ClaimProofURLs.constructFromObject(data['proofs']);
      if (data.hasOwnProperty('settlementType'))
        obj.settlementType = SettlementType.constructFromObject(data['settlementType']);
    }
    return obj;
  }
}

/**
 * @member {module:shippingV2/js-client.shippingV2.model/TrackingId} trackingId
 */
CreateClaimRequest.prototype.trackingId = undefined;

/**
 * This is required for off-Amazon shipments to determine value of shipments
 * @member {module:shippingV2/js-client.shippingV2.model/Currency} declaredValue
 */
CreateClaimRequest.prototype.declaredValue = undefined;

/**
 * @member {module:shippingV2/js-client.shippingV2.model/ClaimReason} claimReason
 */
CreateClaimRequest.prototype.claimReason = undefined;

/**
 * Applicable for only On Amazon shipments to identify if replacement was sent
 * @member {Boolean} isReplacementPackageSent
 */
CreateClaimRequest.prototype.isReplacementPackageSent = undefined;

/**
 * @member {module:shippingV2/js-client.shippingV2.model/ClaimProofURLs} proofs
 */
CreateClaimRequest.prototype.proofs = undefined;

/**
 * @member {module:shippingV2/js-client.shippingV2.model/SettlementType} settlementType
 */
CreateClaimRequest.prototype.settlementType = undefined;


