/*
 * Amazon Shipping API
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * OpenAPI spec version: v2
 * Contact: swa-api-core@amazon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';
import {LabelAttribute} from './LabelAttribute.js';

/**
 * The RequestAttributes model module.
 * @module shippingV2/js-client.shippingV2.model/RequestAttributes
 * @version v2
 */
export class RequestAttributes extends Array {
  /**
   * Constructs a new <code>RequestAttributes</code>.
   * Specify the type of attributes to be added on a label.
   * @alias module:shippingV2/js-client.shippingV2.model/RequestAttributes
   * @class
   * @extends Array
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>RequestAttributes</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:shippingV2/js-client.shippingV2.model/RequestAttributes} obj Optional instance to populate.
   * @return {module:shippingV2/js-client.shippingV2.model/RequestAttributes} The populated <code>RequestAttributes</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      switch(typeof data) {
        case 'string':
          obj = String(data);
          break;
        case 'number':
          obj = Number(data);
          break;
        case 'boolean':
          obj = Boolean(data);
          break;
      }
      obj = obj || new RequestAttributes();
      ApiClient.constructFromObject(data, obj, 'LabelAttribute');
    }
    return obj;
  }
}

